import type { GuideArticle } from '@/types/guide';

const article: GuideArticle = {
  slug: 'how-to-split-pdf-online',
  category: 'split-pdf',
  title: {
    pl: 'Jak podzielić plik PDF na mniejsze części',
    en: 'How to Split a PDF into Smaller Files',
    de: 'Wie man eine PDF-Datei in kleinere Teile aufteilt',
    es: 'Cómo dividir un archivo PDF en partes más pequeñas',
    fr: 'Comment diviser un fichier PDF en plusieurs fichiers',
    it: 'Come dividere un file PDF in parti più piccole',
    pt: 'Como dividir um ficheiro PDF em partes mais pequenas',
    sv: 'Hur man delar upp en PDF-fil i mindre delar',
    no: 'Hvordan dele en PDF-fil i mindre deler',
    is: 'Hvernig á að skipta PDF skrá í smærri hluta',
    tr: 'Bir PDF dosyası nasıl daha küçük parçalara bölünür',
    ar: 'كيفية تقسيم ملف PDF إلى أجزاء أصغر',
    fa: 'چگونه یک فایل PDF را به بخش‌های کوچکتر تقسیم کنیم',
    hi: 'PDF फ़ाइल को छोटे भागों में कैसे विभाजित करें',
    ja: 'PDFファイルを小さなファイルに分割する方法',
    zh: '如何将PDF文件分割成较小的部分',
  },
  excerpt: {
    pl: 'Dowiedz się, jak dzielić PDF na osobne dokumenty — co N stron, zakresy niestandardowe lub wybór konkretnych stron. W pełni lokalnie i za darmo.',
    en: 'Learn how to split a PDF into separate documents — every N pages, custom ranges, or selecting specific pages. Fully local and free.',
    de: 'Erfahren Sie, wie Sie ein PDF in separate Dokumente aufteilen — alle N Seiten, benutzerdefinierte Bereiche oder Auswahl bestimmter Seiten.',
    es: 'Aprenda a dividir un PDF en documentos separados — cada N páginas, rangos personalizados o seleccionando páginas específicas.',
    fr: 'Apprenez à diviser un PDF en documents séparés — toutes les N pages, plages personnalisées ou sélection de pages spécifiques.',
    it: 'Impara a dividere un PDF in documenti separati — ogni N pagine, intervalli personalizzati o selezione di pagine specifiche.',
    pt: 'Aprenda a dividir um PDF em documentos separados — a cada N páginas, intervalos personalizados ou selecionando páginas específicas.',
    sv: 'Lär dig hur du delar upp en PDF i separata dokument — var N:te sida, anpassade intervall eller val av specifika sidor.',
    no: 'Lær hvordan du deler en PDF i separate dokumenter — hver N side, egendefinerte områder eller valg av bestemte sider.',
    is: 'Lærðu hvernig á að skipta PDF í aðskilin skjöl — á hverri N síðu, sérsniðin svið eða val á tilteknum síðum.',
    tr: 'Bir PDF\'yi ayrı belgelere nasıl böleceğinizi öğrenin — her N sayfada bir, özel aralıklar veya belirli sayfaları seçme.',
    ar: 'تعلم كيفية تقسيم PDF إلى مستندات منفصلة — كل N صفحة، نطاقات مخصصة أو اختيار صفحات محددة.',
    fa: 'بیاموزید چگونه یک PDF را به اسناد جداگانه تقسیم کنید — هر N صفحه، محدوده‌های سفارشی یا انتخاب صفحات خاص.',
    hi: 'PDF को अलग-अलग दस्तावेज़ों में विभाजित करना सीखें — हर N पृष्ठ, कस्टम रेंज, या विशिष्ट पृष्ठ चुनना।',
    ja: 'PDFを個別の文書に分割する方法を学びます — Nページごと、カスタム範囲、または特定のページを選択。',
    zh: '了解如何将PDF分割为单独的文档 — 每N页、自定义范围或选择特定页面。',
  },
  body: [
    { type: 'paragraph', text: {
      pl: 'Dzielenie PDF przydaje się, gdy masz duży dokument i potrzebujesz tylko kilku stron, albo gdy chcesz podzielić skan wielostronicowy na osobne pliki. OptimaPDF oferuje trzy tryby dzielenia, dzięki czemu dostosujesz operację do swoich potrzeb.',
      en: 'Splitting a PDF is useful when you have a large document and need only a few pages, or when you want to divide a multi-page scan into separate files. OptimaPDF offers three split modes to suit your needs.',
      de: 'Das Aufteilen einer PDF ist nützlich, wenn Sie ein großes Dokument haben und nur wenige Seiten benötigen oder einen mehrseitigen Scan in einzelne Dateien aufteilen möchten.',
      es: 'Dividir un PDF es útil cuando tienes un documento grande y solo necesitas unas páginas, o cuando quieres dividir un escaneo de varias páginas.',
      fr: 'Diviser un PDF est utile lorsque vous avez un document volumineux et n\'avez besoin que de quelques pages, ou pour diviser un scan multipage en fichiers séparés.',
      it: 'Dividere un PDF è utile quando hai un documento grande e ti servono solo poche pagine, o quando vuoi dividere una scansione multipagina in file separati.',
      pt: 'Dividir um PDF é útil quando tem um documento grande e precisa apenas de algumas páginas, ou quando quer dividir uma digitalização de várias páginas.',
      sv: 'Att dela upp en PDF är användbart när du har ett stort dokument och bara behöver några sidor, eller när du vill dela upp en flersidig skanning.',
      no: 'Å dele en PDF er nyttig når du har et stort dokument og bare trenger noen sider, eller når du vil dele en flersidig skanning.',
      is: 'Að skipta PDF er gagnlegt þegar þú ert með stórt skjal og þarft aðeins nokkrar síður, eða vilt skipta fjölside skönnun í aðskildar skrár.',
      tr: 'Büyük bir belgeniz olduğunda ve yalnızca birkaç sayfaya ihtiyacınız olduğunda veya çok sayfalı bir taramayı ayrı dosyalara bölmek istediğinizde PDF bölme kullanışlıdır.',
      ar: 'تقسيم PDF مفيد عندما يكون لديك مستند كبير وتحتاج فقط إلى بضع صفحات، أو عندما تريد تقسيم مسح ضوئي متعدد الصفحات إلى ملفات منفصلة.',
      fa: 'تقسیم PDF زمانی مفید است که سند بزرگی دارید و فقط به چند صفحه نیاز دارید، یا می‌خواهید یک اسکن چند صفحه‌ای را به فایل‌های جداگانه تقسیم کنید.',
      hi: 'PDF को विभाजित करना तब उपयोगी होता है जब आपके पास एक बड़ा दस्तावेज़ हो और आपको केवल कुछ पृष्ठों की आवश्यकता हो, या जब आप बहु-पृष्ठ स्कैन को अलग-अलग फ़ाइलों में विभाजित करना चाहते हों।',
      ja: 'PDFの分割は、大きな文書から数ページだけが必要な場合や、マルチページのスキャンを個別のファイルに分割したい場合に便利です。',
      zh: '当您有一个大文档只需要几页，或者想要将多页扫描件拆分为单独的文件时，PDF拆分非常有用。',
    }},
    { type: 'cta', tool: 'split' },
    { type: 'heading', level: 2, text: {
      pl: 'Tryby dzielenia PDF',
      en: 'PDF Split Modes',
      de: 'PDF-Teilungsmodi',
      es: 'Modos de división de PDF',
      fr: 'Modes de division PDF',
      it: 'Modalità di divisione PDF',
      pt: 'Modos de divisão de PDF',
      sv: 'PDF-delningslägen',
      no: 'PDF-delingsmoduser',
      is: 'Skiptihamir PDF',
      tr: 'PDF Bölme Modları',
      ar: 'أنواع تقسيم PDF',
      fa: 'حالت‌های تقسیم PDF',
      hi: 'PDF विभाजन मोड',
      ja: 'PDF分割モード',
      zh: 'PDF拆分模式',
    }},
    { type: 'step', title: {
      pl: 'Tryb "Co N stron"',
      en: '"Every N Pages" Mode',
      de: 'Modus "Alle N Seiten"',
      es: 'Modo "Cada N páginas"',
      fr: 'Mode "Toutes les N pages"',
      it: 'Modalità "Ogni N pagine"',
      pt: 'Modo "A cada N páginas"',
      sv: 'Läge "Var N:te sida"',
      no: 'Modus "Hver N side"',
      is: 'Hamur "Á hverri N síðu"',
      tr: '"Her N Sayfada Bir" Modu',
      ar: 'وضع "كل N صفحة"',
      fa: 'حالت "هر N صفحه"',
      hi: '"हर N पृष्ठ" मोड',
      ja: '「Nページごと」モード',
      zh: '"每N页"模式',
    }, text: {
      pl: 'Dzieli dokument na części po określonej liczbie stron. Na przykład PDF z 20 stronami i ustawieniem "co 5 stron" utworzy 4 pliki po 5 stron każdy. Idealne do dzielenia skanów.',
      en: 'Splits the document into parts of a specified page count. For example, a 20-page PDF with "every 5 pages" creates 4 files of 5 pages each. Ideal for dividing scans.',
      de: 'Teilt das Dokument in Teile mit einer bestimmten Seitenanzahl. Ein 20-seitiges PDF mit "alle 5 Seiten" erstellt 4 Dateien mit je 5 Seiten.',
      es: 'Divide el documento en partes con un número de páginas específico. Un PDF de 20 páginas con "cada 5 páginas" crea 4 archivos de 5 páginas.',
      fr: 'Divise le document en parties d\'un nombre de pages spécifié. Un PDF de 20 pages avec "toutes les 5 pages" crée 4 fichiers de 5 pages.',
      it: 'Divide il documento in parti con un numero di pagine specificato. Un PDF di 20 pagine con "ogni 5 pagine" crea 4 file da 5 pagine ciascuno.',
      pt: 'Divide o documento em partes com um número de páginas especificado. Um PDF de 20 páginas com "a cada 5 páginas" cria 4 ficheiros de 5 páginas.',
      sv: 'Delar upp dokumentet i delar med ett specificerat sidantal. En 20-sidig PDF med "var 5:e sida" skapar 4 filer med 5 sidor var.',
      no: 'Deler dokumentet i deler med et angitt antall sider. En 20-siders PDF med "hver 5 side" oppretter 4 filer med 5 sider hver.',
      is: 'Skiptir skjalinu í hluta með tilteknum fjölda síðna. 20 síðna PDF með "á hverri 5 síðu" býr til 4 skrár með 5 síðum hver.',
      tr: 'Belgeyi belirtilen sayfa sayısına göre parçalara ayırır. "Her 5 sayfada bir" ile 20 sayfalık bir PDF, her biri 5 sayfalık 4 dosya oluşturur.',
      ar: 'يقسم المستند إلى أجزاء بعدد محدد من الصفحات. PDF مكون من 20 صفحة مع "كل 5 صفحات" ينشئ 4 ملفات كل منها 5 صفحات.',
      fa: 'سند را به بخش‌هایی با تعداد صفحات مشخص تقسیم می‌کند. یک PDF 20 صفحه‌ای با "هر 5 صفحه" 4 فایل 5 صفحه‌ای ایجاد می‌کند.',
      hi: 'दस्तावेज़ को निर्दिष्ट पृष्ठ संख्या वाले भागों में विभाजित करता है। "हर 5 पृष्ठ" के साथ 20-पृष्ठ का PDF 5 पृष्ठों की 4 फ़ाइलें बनाता है।',
      ja: '指定されたページ数で文書を分割します。「5ページごと」で20ページのPDFは、それぞれ5ページのファイルを4つ作成します。',
      zh: '将文档按指定页数分成多个部分。例如，20页的PDF设置"每5页"将创建4个文件，每个5页。',
    }},
    { type: 'step', title: {
      pl: 'Tryb "Zakresy niestandardowe"',
      en: '"Custom Ranges" Mode',
      de: 'Modus "Benutzerdefinierte Bereiche"',
      es: 'Modo "Rangos personalizados"',
      fr: 'Mode "Plages personnalisées"',
      it: 'Modalità "Intervalli personalizzati"',
      pt: 'Modo "Intervalos personalizados"',
      sv: 'Läge "Anpassade intervall"',
      no: 'Modus "Egendefinerte områder"',
      is: 'Hamur "Sérsniðin svið"',
      tr: '"Özel Aralıklar" Modu',
      ar: 'وضع "نطاقات مخصصة"',
      fa: 'حالت "محدوده‌های سفارشی"',
      hi: '"कस्टम रेंज" मोड',
      ja: '「カスタム範囲」モード',
      zh: '"自定义范围"模式',
    }, text: {
      pl: 'Wpisz konkretne zakresy stron, np. "1-5, 8, 10-15". Każdy zakres stanie się osobnym plikiem. Możesz mieszać pojedyncze strony z zakresami.',
      en: 'Enter specific page ranges, e.g. "1-5, 8, 10-15". Each range becomes a separate file. You can mix single pages with ranges.',
      de: 'Geben Sie bestimmte Seitenbereiche ein, z.B. "1-5, 8, 10-15". Jeder Bereich wird zu einer separaten Datei. Sie können einzelne Seiten mit Bereichen mischen.',
      es: 'Introduzca rangos de páginas específicos, por ejemplo "1-5, 8, 10-15". Cada rango se convierte en un archivo separado.',
      fr: 'Entrez des plages de pages spécifiques, ex. "1-5, 8, 10-15". Chaque plage devient un fichier séparé. Vous pouvez mélanger pages uniques et plages.',
      it: 'Inserisci intervalli di pagine specifici, ad es. "1-5, 8, 10-15". Ogni intervallo diventa un file separato. Puoi mescolare pagine singole e intervalli.',
      pt: 'Insira intervalos de páginas específicos, ex. "1-5, 8, 10-15". Cada intervalo torna-se um ficheiro separado. Pode misturar páginas únicas com intervalos.',
      sv: 'Ange specifika sidintervall, t.ex. "1-5, 8, 10-15". Varje intervall blir en separat fil. Du kan blanda enstaka sidor med intervall.',
      no: 'Angi bestemte sideområder, f.eks. "1-5, 8, 10-15". Hvert område blir en separat fil. Du kan blande enkeltsider med områder.',
      is: 'Sláðu inn tiltekin bilsvið, t.d. "1-5, 8, 10-15". Hvert bilsvið verður aðskilin skrá. Þú getur blandað einstökum síðum við bilsvið.',
      tr: 'Belirli sayfa aralıkları girin, örn. "1-5, 8, 10-15". Her aralık ayrı bir dosya haline gelir. Tek sayfaları aralıklarla karıştırabilirsiniz.',
      ar: 'أدخل نطاقات صفحات محددة، على سبيل المثال "1-5، 8، 10-15". يصبح كل نطاق ملفًا منفصلاً. يمكنك خلط الصفحات الفردية مع النطاقات.',
      fa: 'محدوده‌های صفحات خاص را وارد کنید، مثلاً "1-5, 8, 10-15". هر محدوده یک فایل جداگانه می‌شود. می‌توانید صفحات تکی را با محدوده‌ها ترکیب کنید.',
      hi: 'विशिष्ट पृष्ठ श्रेणियां दर्ज करें, जैसे "1-5, 8, 10-15"। प्रत्येक श्रेणी एक अलग फ़ाइल बन जाती है। आप एकल पृष्ठों को श्रेणियों के साथ मिश्रित कर सकते हैं।',
      ja: '特定のページ範囲を入力します（例：「1-5, 8, 10-15」）。各範囲が個別のファイルになります。単一ページと範囲を混在させることができます。',
      zh: '输入特定的页码范围，例如"1-5, 8, 10-15"。每个范围成为一个单独的文件。您可以混合单页和范围。',
    }},
    { type: 'step', title: {
      pl: 'Tryb "Wybierz strony"',
      en: '"Select Pages" Mode',
      de: 'Modus "Seiten auswählen"',
      es: 'Modo "Seleccionar páginas"',
      fr: 'Mode "Sélectionner des pages"',
      it: 'Modalità "Seleziona pagine"',
      pt: 'Modo "Selecionar páginas"',
      sv: 'Läge "Välj sidor"',
      no: 'Modus "Velg sider"',
      is: 'Hamur "Velja síður"',
      tr: '"Sayfa Seç" Modu',
      ar: 'وضع "تحديد صفحات"',
      fa: 'حالت "انتخاب صفحات"',
      hi: '"पृष्ठ चुनें" मोड',
      ja: '「ページ選択」モード',
      zh: '"选择页面"模式',
    }, text: {
      pl: 'Zobacz miniatury wszystkich stron i zaznacz te, które chcesz wyodrębnić. Wybrane strony zostaną zapisane jako osobny plik PDF. Idealne do wyciągnięcia konkretnych stron.',
      en: 'View thumbnails of all pages and select the ones you want to extract. Selected pages will be saved as a separate PDF file. Perfect for pulling out specific pages.',
      de: 'Sehen Sie sich Miniaturen aller Seiten an und wählen Sie die gewünschten aus. Die ausgewählten Seiten werden als separate PDF-Datei gespeichert.',
      es: 'Vea las miniaturas de todas las páginas y seleccione las que desea extraer. Las páginas seleccionadas se guardan como un archivo PDF separado.',
      fr: 'Visualisez les vignettes de toutes les pages et sélectionnez celles à extraire. Les pages sélectionnées sont enregistrées dans un fichier PDF séparé.',
      it: 'Visualizza le miniature di tutte le pagine e seleziona quelle da estrarre. Le pagine selezionate vengono salvate come file PDF separato.',
      pt: 'Veja as miniaturas de todas as páginas e selecione as que pretende extrair. As páginas selecionadas são guardadas como um ficheiro PDF separado.',
      sv: 'Visa miniatyrer av alla sidor och välj de du vill extrahera. Valda sidor sparas som en separat PDF-fil.',
      no: 'Vis miniatyrbilder av alle sider og velg sidene du vil trekke ut. Valgte sider lagres som en separat PDF-fil.',
      is: 'Skoða smámyndir allra síðna og veldu þær sem þú vilt draga út. Valdar síður verða vistaðar sem aðskilin PDF skrá.',
      tr: 'Tüm sayfaların küçük resimlerini görüntüleyin ve çıkarmak istediklerinizi seçin. Seçilen sayfalar ayrı bir PDF dosyası olarak kaydedilir.',
      ar: 'عرض صور مصغرة لجميع الصفحات واختيار الصفحات التي تريد استخراجها. يتم حفظ الصفحات المحددة كملف PDF منفصل.',
      fa: 'تصویرهای بندانگشتی همه صفحات را مشاهده کنید و صفحاتی را که می‌خواهید استخراج کنید انتخاب کنید. صفحات انتخاب شده به عنوان یک فایل PDF جداگانه ذخیره می‌شوند.',
      hi: 'सभी पृष्ठों की थंबनेल देखें और जिन्हें आप निकालना चाहते हैं उन्हें चुनें। चयनित पृष्ठ एक अलग PDF फ़ाइल के रूप में सहेजे जाते हैं।',
      ja: 'すべてのページのサムネイルを表示し、抽出したいページを選択します。選択したページは別のPDFファイルとして保存されます。',
      zh: '查看所有页面的缩略图，然后选择要提取的页面。所选页面将保存为单独的PDF文件。',
    }},
    { type: 'cta', tool: 'split' },
  ],
  relatedTool: 'split',
  faq: [
    { q: {
      pl: 'Czy mogę wybrać wiele zakresów?',
      en: 'Can I select multiple ranges?',
      de: 'Kann ich mehrere Bereiche auswählen?',
      es: '¿Puedo seleccionar varios rangos?',
      fr: 'Puis-je sélectionner plusieurs plages ?',
      it: 'Posso selezionare più intervalli?',
      pt: 'Posso selecionar vários intervalos?',
      sv: 'Kan jag välja flera intervall?',
      no: 'Kan jeg velge flere områder?',
      is: 'Get ég valið mörg bilsvið?',
      tr: 'Birden fazla aralık seçebilir miyim?',
      ar: 'هل يمكنني تحديد نطاقات متعددة؟',
      fa: 'آیا می‌توانم چندین محدوده را انتخاب کنم؟',
      hi: 'क्या मैं कई श्रेणियां चुन सकता हूँ?',
      ja: '複数の範囲を選択できますか？',
      zh: '我可以选择多个范围吗？',
    }, a: {
      pl: 'Tak, w trybie "Zakresy niestandardowe" możesz wpisać wiele zakresów oddzielonych przecinkami. Każdy zakres zostanie zapisany jako osobny plik. Przykład: "1-3, 5, 7-9" utworzy trzy pliki.',
      en: 'Yes, in "Custom Ranges" mode you can enter multiple ranges separated by commas. Each range becomes a separate file. Example: "1-3, 5, 7-9" creates three files.',
      de: 'Ja, im Modus "Benutzerdefinierte Bereiche" können Sie mehrere durch Kommas getrennte Bereiche eingeben. Jeder Bereich wird eine separate Datei.',
      es: 'Sí, en el modo "Rangos personalizados" puede introducir varios rangos separados por comas. Cada rango se convierte en un archivo separado.',
      fr: 'Oui, en mode "Plages personnalisées" vous pouvez entrer plusieurs plages séparées par des virgules. Chaque plage devient un fichier séparé.',
      it: 'Sì, in modalità "Intervalli personalizzati" puoi inserire più intervalli separati da virgole. Ogni intervallo diventa un file separato.',
      pt: 'Sim, no modo "Intervalos personalizados" pode inserir vários intervalos separados por vírgulas. Cada intervalo torna-se um ficheiro separado.',
      sv: 'Ja, i läget "Anpassade intervall" kan du ange flera intervall separerade med kommatecken. Varje intervall blir en separat fil.',
      no: 'Ja, i modus "Egendefinerte områder" kan du angi flere områder atskilt med komma. Hvert område blir en separat fil.',
      is: 'Já, í ham "Sérsniðin bilsvið" getur þú slegið inn mörg bilsvið aðskilin með kommum. Hvert bilsvið verður aðskilin skrá.',
      tr: 'Evet, "Özel Aralıklar" modunda virgülle ayrılmış birden fazla aralık girebilirsiniz. Her aralık ayrı bir dosya haline gelir.',
      ar: 'نعم، في وضع "النطاقات المخصصة" يمكنك إدخال نطاقات متعددة مفصولة بفواصل. يصبح كل نطاق ملفًا منفصلًا.',
      fa: 'بله، در حالت "محدوده‌های سفارشی" می‌توانید چندین محدوده را با کاما از هم جدا کنید. هر محدوده یک فایل جداگانه می‌شود.',
      hi: 'हाँ, "कस्टम रेंज" मोड में आप अल्पविराम से अलग की गई कई श्रेणियां दर्ज कर सकते हैं। प्रत्येक श्रेणी एक अलग फ़ाइल बन जाती है।',
      ja: 'はい、「カスタム範囲」モードでは、カンマ区切りで複数の範囲を入力できます。各範囲が個別のファイルになります。',
      zh: '可以。在"自定义范围"模式下，您可以输入多个以逗号分隔的范围。每个范围成为一个单独的文件。',
    }},
  ],
  canonicalOverride: undefined,
  publishedAt: '2025-06-18',
  updatedAt: '2025-07-02',
};

export default article;
