import type { GuideArticle } from '@/types/guide';

const article: GuideArticle = {
  slug: 'how-to-split-pdf-online',
  category: 'split-pdf',
  title: {
    pl: 'Jak podzielić plik PDF na mniejsze części',
    en: 'How to Split a PDF into Smaller Files',
    de: 'Wie man eine PDF-Datei in kleinere Teile aufteilt',
    es: 'Cómo dividir un archivo PDF en partes más pequeñas',
    fr: 'Comment diviser un fichier PDF en plusieurs fichiers',
    it: 'Come dividere un file PDF in parti più piccole',
    pt: 'Como dividir um ficheiro PDF em partes mais pequenas',
    sv: 'Hur man delar upp en PDF-fil i mindre delar',
    no: 'Hvordan dele en PDF-fil i mindre deler',
    is: 'Hvernig á að skipta PDF skrá í smærri hluta',
    tr: 'Bir PDF dosyası nasıl daha küçük parçalara bölünür',
    ar: 'كيفية تقسيم ملف PDF إلى أجزاء أصغر',
    fa: 'چگونه یک فایل PDF را به بخش‌های کوچکتر تقسیم کنیم',
    hi: 'PDF फ़ाइल को छोटे भागों में कैसे विभाजित करें',
    ja: 'PDFファイルを小さなファイルに分割する方法',
    zh: '如何将PDF文件分割成较小的部分',
  },
  excerpt: {
      pl: 'Dowiedz się, jak dzielić PDF na osobne dokumenty — strona po stronie, zakresy niestandardowe lub wybór konkretnych stron. W pełni lokalnie i za darmo.',
      en: 'Learn how to split a PDF into separate documents — page by page, custom ranges, or by selecting specific pages. Fully local and free.',
      de: 'Erfahren Sie, wie Sie ein PDF in separate Dokumente aufteilen — Seite für Seite, benutzerdefinierte Bereiche oder Auswahl bestimmter Seiten.',
      es: 'Aprenda a dividir un PDF en documentos separados — página por página, rangos personalizados o seleccionando páginas específicas.',
      fr: 'Apprenez à diviser un PDF en documents séparés — page par page, plages personnalisées ou sélection de pages spécifiques.',
      it: 'Impara a dividere un PDF in documenti separati — pagina per pagina, intervalli personalizzati o selezione di pagine specifiche.',
      pt: 'Aprenda a dividir um PDF em documentos separados — página a página, intervalos personalizados ou selecionando páginas específicas.',
      sv: 'Lär dig hur du delar upp en PDF i separata dokument — sida för sida, anpassade intervall eller val av specifika sidor.',
      no: 'Lær hvordan du deler en PDF i separate dokumenter — side for side, egendefinerte områder eller valg av bestemte sider.',
      is: 'Lærðu hvernig á að skipta PDF í aðskilin skjöl — síðu fyrir síðu, sérsniðin svið eða val á tilteknum síðum.',
      tr: 'Bir PDF\'yi ayrı belgelere nasıl böleceğinizi öğrenin — sayfa sayfa, özel aralıklar veya belirli sayfaları seçerek.',
      ar: 'تعلم كيفية تقسيم PDF إلى مستندات منفصلة — صفحة بصفحة، نطاقات مخصصة أو اختيار صفحات محددة.',
      fa: 'بیاموزید چگونه یک PDF را به اسناد جداگانه تقسیم کنید — صفحه به صفحه، محدوده‌های سفارشی یا انتخاب صفحات خاص.',
      hi: 'PDF को अलग-अलग दस्तावेज़ों में विभाजित करना सीखें — पृष्ठ-दर-पृष्ठ, कस्टम रेंज, या विशिष्ट पृष्ठ चुनकर।',
      ja: 'PDFを個別の文書に分割する方法を学びます — 1ページずつ、カスタム範囲、または特定のページを選択。',
      zh: '了解如何将PDF分割为单独的文档 — 逐页、自定义范围或选择特定页面。',
  },
  body: [
    { type: 'paragraph', text: {
      pl: 'Dzielenie PDF przydaje się, gdy masz duży dokument i potrzebujesz tylko kilku stron, albo gdy chcesz podzielić skan wielostronicowy na osobne pliki. OptimaPDF oferuje trzy tryby dzielenia, dzięki czemu dostosujesz operację do swoich potrzeb.',
      en: 'Splitting a PDF is useful when you have a large document and need only a few pages, or when you want to divide a multi-page scan into separate files. OptimaPDF offers three split modes to suit your needs.',
      de: 'Das Aufteilen einer PDF ist nützlich, wenn Sie ein großes Dokument haben und nur wenige Seiten benötigen oder einen mehrseitigen Scan in einzelne Dateien aufteilen möchten.',
      es: 'Dividir un PDF es útil cuando tienes un documento grande y solo necesitas unas páginas, o cuando quieres dividir un escaneo de varias páginas.',
      fr: 'Diviser un PDF est utile lorsque vous avez un document volumineux et n\'avez besoin que de quelques pages, ou pour diviser un scan multipage en fichiers séparés.',
      it: 'Dividere un PDF è utile quando hai un documento grande e ti servono solo poche pagine, o quando vuoi dividere una scansione multipagina in file separati.',
      pt: 'Dividir um PDF é útil quando tem um documento grande e precisa apenas de algumas páginas, ou quando quer dividir uma digitalização de várias páginas.',
      sv: 'Att dela upp en PDF är användbart när du har ett stort dokument och bara behöver några sidor, eller när du vill dela upp en flersidig skanning.',
      no: 'Å dele en PDF er nyttig når du har et stort dokument og bare trenger noen sider, eller når du vil dele en flersidig skanning.',
      is: 'Að skipta PDF er gagnlegt þegar þú ert með stórt skjal og þarft aðeins nokkrar síður, eða vilt skipta fjölside skönnun í aðskildar skrár.',
      tr: 'Büyük bir belgeniz olduğunda ve yalnızca birkaç sayfaya ihtiyacınız olduğunda veya çok sayfalı bir taramayı ayrı dosyalara bölmek istediğinizde PDF bölme kullanışlıdır.',
      ar: 'تقسيم PDF مفيد عندما يكون لديك مستند كبير وتحتاج فقط إلى بضع صفحات، أو عندما تريد تقسيم مسح ضوئي متعدد الصفحات إلى ملفات منفصلة.',
      fa: 'تقسیم PDF زمانی مفید است که سند بزرگی دارید و فقط به چند صفحه نیاز دارید، یا می‌خواهید یک اسکن چند صفحه‌ای را به فایل‌های جداگانه تقسیم کنید.',
      hi: 'PDF को विभाजित करना तब उपयोगी होता है जब आपके पास एक बड़ा दस्तावेज़ हो और आपको केवल कुछ पृष्ठों की आवश्यकता हो, या जब आप बहु-पृष्ठ स्कैन को अलग-अलग फ़ाइलों में विभाजित करना चाहते हों।',
      ja: 'PDFの分割は、大きな文書から数ページだけが必要な場合や、マルチページのスキャンを個別のファイルに分割したい場合に便利です。',
      zh: '当您有一个大文档只需要几页，或者想要将多页扫描件拆分为单独的文件时，PDF拆分非常有用。',
    }},
    { type: 'cta', tool: 'split' },
    { type: 'heading', level: 2, text: {
      pl: 'Tryby dzielenia PDF',
      en: 'PDF Split Modes',
      de: 'PDF-Teilungsmodi',
      es: 'Modos de división de PDF',
      fr: 'Modes de division PDF',
      it: 'Modalità di divisione PDF',
      pt: 'Modos de divisão de PDF',
      sv: 'PDF-delningslägen',
      no: 'PDF-delingsmoduser',
      is: 'Skiptihamir PDF',
      tr: 'PDF Bölme Modları',
      ar: 'أنواع تقسيم PDF',
      fa: 'حالت‌های تقسیم PDF',
      hi: 'PDF विभाजन मोड',
      ja: 'PDF分割モード',
      zh: 'PDF拆分模式',
    }},
    { type: 'step', title: {
      pl: 'Tryb "Strona po stronie"',
      en: '"Page by Page" Mode',
      de: 'Modus "Seite für Seite"',
      es: 'Modo "Página por página"',
      fr: 'Mode "Page par page"',
      it: 'Modalità "Pagina per pagina"',
      pt: 'Modo "Página a página"',
      sv: 'Läge "Sida för sida"',
      no: 'Modus "Side for side"',
      is: 'Hamur "Síðu fyrir síðu"',
      tr: '"Sayfa Sayfa" Modu',
      ar: 'وضع "صفحة بصفحة"',
      fa: 'حالت "صفحه به صفحه"',
      hi: '"पृष्ठ-दर-पृष्ठ" मोड',
      ja: '「1ページずつ」モード',
      zh: '"逐页"模式',
    }, text: {
      pl: 'Zapisuje każdą stronę jako osobny plik PDF. Na przykład PDF z 20 stronami utworzy 20 plików jednostronicowych. Idealne do rozdzielania skanów.',
      en: 'Saves every page as its own PDF file. For example, a 20-page PDF creates 20 single-page files. Ideal for breaking up scans.',
      de: 'Speichert jede Seite als eigene PDF-Datei. Ein 20-seitiges PDF erstellt beispielsweise 20 einseitige Dateien. Ideal zum Zerlegen von Scans.',
      es: 'Guarda cada página como un archivo PDF independiente. Por ejemplo, un PDF de 20 páginas crea 20 archivos de una página. Ideal para separar escaneos.',
      fr: 'Enregistre chaque page dans son propre fichier PDF. Par exemple, un PDF de 20 pages crée 20 fichiers d\'une page. Idéal pour découper des scans.',
      it: 'Salva ogni pagina come file PDF a sé stante. Ad esempio, un PDF di 20 pagine crea 20 file di una pagina. Ideale per suddividere le scansioni.',
      pt: 'Guarda cada página como um ficheiro PDF independente. Por exemplo, um PDF de 20 páginas cria 20 ficheiros de uma página. Ideal para separar digitalizações.',
      sv: 'Sparar varje sida som en egen PDF-fil. En 20-sidig PDF skapar till exempel 20 enkelsidiga filer. Perfekt för att dela upp skanningar.',
      no: 'Lagrer hver side som en egen PDF-fil. En PDF på 20 sider oppretter for eksempel 20 énsides filer. Ideelt for å dele opp skanninger.',
      is: 'Vistar hverja síðu sem sérstaka PDF skrá. Til dæmis býr 20 síðna PDF til 20 eins síðu skrár. Tilvalið til að skipta upp skönnunum.',
      tr: 'Her sayfayı ayrı bir PDF dosyası olarak kaydeder. Örneğin 20 sayfalık bir PDF, tek sayfalık 20 dosya oluşturur. Taramaları ayırmak için idealdir.',
      ar: 'يحفظ كل صفحة كملف PDF مستقل. على سبيل المثال، ينشئ PDF مكون من 20 صفحة 20 ملفًا من صفحة واحدة. مثالي لتقسيم المسوحات الضوئية.',
      fa: 'هر صفحه را به صورت یک فایل PDF جداگانه ذخیره می‌کند. برای مثال، یک PDF 20 صفحه‌ای 20 فایل تک‌صفحه‌ای ایجاد می‌کند. مناسب برای تفکیک اسکن‌ها.',
      hi: 'हर पृष्ठ को उसकी अपनी अलग PDF फ़ाइल के रूप में सहेजता है। उदाहरण के लिए, 20-पृष्ठ का PDF 20 एकल-पृष्ठ फ़ाइलें बनाता है। स्कैन को अलग करने के लिए आदर्श।',
      ja: '各ページを個別のPDFファイルとして保存します。たとえば20ページのPDFからは、1ページずつのファイルが20個作成されます。スキャンの分割に最適です。',
      zh: '将每一页保存为单独的PDF文件。例如，20页的PDF将创建20个单页文件。非常适合拆分扫描件。',
    }},
    { type: 'step', title: {
      pl: 'Tryb "Zakresy niestandardowe"',
      en: '"Custom Ranges" Mode',
      de: 'Modus "Benutzerdefinierte Bereiche"',
      es: 'Modo "Rangos personalizados"',
      fr: 'Mode "Plages personnalisées"',
      it: 'Modalità "Intervalli personalizzati"',
      pt: 'Modo "Intervalos personalizados"',
      sv: 'Läge "Anpassade intervall"',
      no: 'Modus "Egendefinerte områder"',
      is: 'Hamur "Sérsniðin svið"',
      tr: '"Özel Aralıklar" Modu',
      ar: 'وضع "نطاقات مخصصة"',
      fa: 'حالت "محدوده‌های سفارشی"',
      hi: '"कस्टम रेंज" मोड',
      ja: '「カスタム範囲」モード',
      zh: '"自定义范围"模式',
    }, text: {
      pl: 'Wpisz konkretne zakresy stron, np. "1-5, 8, 10-15". Każdy zakres stanie się osobnym plikiem. Możesz mieszać pojedyncze strony z zakresami.',
      en: 'Enter specific page ranges, e.g. "1-5, 8, 10-15". Each range becomes a separate file. You can mix single pages with ranges.',
      de: 'Geben Sie bestimmte Seitenbereiche ein, z.B. "1-5, 8, 10-15". Jeder Bereich wird zu einer separaten Datei. Sie können einzelne Seiten mit Bereichen mischen.',
      es: 'Introduzca rangos de páginas específicos, por ejemplo "1-5, 8, 10-15". Cada rango se convierte en un archivo separado.',
      fr: 'Entrez des plages de pages spécifiques, ex. "1-5, 8, 10-15". Chaque plage devient un fichier séparé. Vous pouvez mélanger pages uniques et plages.',
      it: 'Inserisci intervalli di pagine specifici, ad es. "1-5, 8, 10-15". Ogni intervallo diventa un file separato. Puoi mescolare pagine singole e intervalli.',
      pt: 'Insira intervalos de páginas específicos, ex. "1-5, 8, 10-15". Cada intervalo torna-se um ficheiro separado. Pode misturar páginas únicas com intervalos.',
      sv: 'Ange specifika sidintervall, t.ex. "1-5, 8, 10-15". Varje intervall blir en separat fil. Du kan blanda enstaka sidor med intervall.',
      no: 'Angi bestemte sideområder, f.eks. "1-5, 8, 10-15". Hvert område blir en separat fil. Du kan blande enkeltsider med områder.',
      is: 'Sláðu inn tiltekin bilsvið, t.d. "1-5, 8, 10-15". Hvert bilsvið verður aðskilin skrá. Þú getur blandað einstökum síðum við bilsvið.',
      tr: 'Belirli sayfa aralıkları girin, örn. "1-5, 8, 10-15". Her aralık ayrı bir dosya haline gelir. Tek sayfaları aralıklarla karıştırabilirsiniz.',
      ar: 'أدخل نطاقات صفحات محددة، على سبيل المثال "1-5، 8، 10-15". يصبح كل نطاق ملفًا منفصلاً. يمكنك خلط الصفحات الفردية مع النطاقات.',
      fa: 'محدوده‌های صفحات خاص را وارد کنید، مثلاً "1-5, 8, 10-15". هر محدوده یک فایل جداگانه می‌شود. می‌توانید صفحات تکی را با محدوده‌ها ترکیب کنید.',
      hi: 'विशिष्ट पृष्ठ श्रेणियां दर्ज करें, जैसे "1-5, 8, 10-15"। प्रत्येक श्रेणी एक अलग फ़ाइल बन जाती है। आप एकल पृष्ठों को श्रेणियों के साथ मिश्रित कर सकते हैं।',
      ja: '特定のページ範囲を入力します（例：「1-5, 8, 10-15」）。各範囲が個別のファイルになります。単一ページと範囲を混在させることができます。',
      zh: '输入特定的页码范围，例如"1-5, 8, 10-15"。每个范围成为一个单独的文件。您可以混合单页和范围。',
    }},
    { type: 'step', title: {
      pl: 'Tryb "Podział według zaznaczenia"',
      en: '"Split by Selection" Mode',
      de: 'Modus "Nach Auswahl teilen"',
      es: 'Modo "Dividir por selección"',
      fr: 'Mode "Diviser par sélection"',
      it: 'Modalità "Dividi per selezione"',
      pt: 'Modo "Dividir por seleção"',
      sv: 'Läge "Dela efter val"',
      no: 'Modus "Del etter utvalg"',
      is: 'Hamur "Skipta eftir vali"',
      tr: '"Seçime Göre Böl" Modu',
      ar: 'وضع "التقسيم حسب التحديد"',
      fa: 'حالت "تقسیم بر اساس انتخاب"',
      hi: '"चयन के अनुसार विभाजन" मोड',
      ja: '「選択で分割」モード',
      zh: '"按选择拆分"模式',
    }, text: {
      pl: 'Zobacz miniatury wszystkich stron i zaznacz te, które chcesz. Otrzymasz dwa pliki: jeden z zaznaczonymi stronami i drugi ze wszystkimi pozostałymi. Idealne do wyciągnięcia konkretnych stron z dokumentu.',
      en: 'View thumbnails of all pages and select the ones you want. You get two files: one with the selected pages and one with all the remaining pages. Perfect for pulling specific pages out of a document.',
      de: 'Sehen Sie sich Miniaturen aller Seiten an und wählen Sie die gewünschten aus. Sie erhalten zwei Dateien: eine mit den ausgewählten Seiten und eine mit allen übrigen Seiten. Perfekt, um bestimmte Seiten aus einem Dokument herauszulösen.',
      es: 'Vea las miniaturas de todas las páginas y seleccione las que desee. Obtendrá dos archivos: uno con las páginas seleccionadas y otro con todas las páginas restantes. Perfecto para sacar páginas concretas de un documento.',
      fr: 'Visualisez les vignettes de toutes les pages et sélectionnez celles que vous voulez. Vous obtenez deux fichiers : l\'un avec les pages sélectionnées et l\'autre avec toutes les pages restantes. Parfait pour extraire des pages précises d\'un document.',
      it: 'Visualizza le miniature di tutte le pagine e seleziona quelle che desideri. Ottieni due file: uno con le pagine selezionate e uno con tutte le pagine rimanenti. Perfetto per estrarre pagine specifiche da un documento.',
      pt: 'Veja as miniaturas de todas as páginas e selecione as que pretende. Obtém dois ficheiros: um com as páginas selecionadas e outro com todas as páginas restantes. Perfeito para retirar páginas específicas de um documento.',
      sv: 'Visa miniatyrer av alla sidor och välj de du vill ha. Du får två filer: en med de valda sidorna och en med alla återstående sidor. Perfekt för att plocka ut specifika sidor ur ett dokument.',
      no: 'Vis miniatyrbilder av alle sider og velg de du vil ha. Du får to filer: én med de valgte sidene og én med alle gjenværende sider. Perfekt for å hente ut bestemte sider fra et dokument.',
      is: 'Skoðaðu smámyndir allra síðna og veldu þær sem þú vilt. Þú færð tvær skrár: eina með völdu síðunum og aðra með öllum öðrum síðum. Fullkomið til að draga tilteknar síður út úr skjali.',
      tr: 'Tüm sayfaların küçük resimlerini görüntüleyin ve istediklerinizi seçin. İki dosya elde edersiniz: biri seçilen sayfalarla, diğeri kalan tüm sayfalarla. Belgeden belirli sayfaları ayırmak için mükemmel.',
      ar: 'اعرض صورًا مصغرة لجميع الصفحات وحدد الصفحات التي تريدها. ستحصل على ملفين: أحدهما يحتوي على الصفحات المحددة والآخر على جميع الصفحات المتبقية. مثالي لاستخراج صفحات محددة من مستند.',
      fa: 'تصویرهای بندانگشتی همه صفحات را مشاهده کنید و صفحات مورد نظر را انتخاب کنید. دو فایل دریافت می‌کنید: یکی شامل صفحات انتخاب‌شده و دیگری شامل همه صفحات باقی‌مانده. مناسب برای جدا کردن صفحات خاص از یک سند.',
      hi: 'सभी पृष्ठों की थंबनेल देखें और अपनी पसंद के पृष्ठ चुनें। आपको दो फ़ाइलें मिलती हैं: एक चयनित पृष्ठों वाली और दूसरी बाकी सभी पृष्ठों वाली। दस्तावेज़ से विशिष्ट पृष्ठ निकालने के लिए बिल्कुल सही।',
      ja: 'すべてのページのサムネイルを表示し、必要なページを選択します。選択したページのファイルと、残りのすべてのページのファイルの2つが作成されます。文書から特定のページを取り出すのに最適です。',
      zh: '查看所有页面的缩略图，然后选择所需页面。您将得到两个文件：一个包含所选页面，另一个包含所有其余页面。非常适合从文档中提取特定页面。',
    }},
    { type: 'cta', tool: 'split' },
  ],
  relatedTool: 'split',
  faq: [
    { q: {
      pl: 'Czy mogę wybrać wiele zakresów?',
      en: 'Can I select multiple ranges?',
      de: 'Kann ich mehrere Bereiche auswählen?',
      es: '¿Puedo seleccionar varios rangos?',
      fr: 'Puis-je sélectionner plusieurs plages ?',
      it: 'Posso selezionare più intervalli?',
      pt: 'Posso selecionar vários intervalos?',
      sv: 'Kan jag välja flera intervall?',
      no: 'Kan jeg velge flere områder?',
      is: 'Get ég valið mörg bilsvið?',
      tr: 'Birden fazla aralık seçebilir miyim?',
      ar: 'هل يمكنني تحديد نطاقات متعددة؟',
      fa: 'آیا می‌توانم چندین محدوده را انتخاب کنم؟',
      hi: 'क्या मैं कई श्रेणियां चुन सकता हूँ?',
      ja: '複数の範囲を選択できますか？',
      zh: '我可以选择多个范围吗？',
    }, a: {
      pl: 'Tak, w trybie "Zakresy niestandardowe" możesz wpisać wiele zakresów oddzielonych przecinkami. Każdy zakres zostanie zapisany jako osobny plik. Przykład: "1-3, 5, 7-9" utworzy trzy pliki.',
      en: 'Yes, in "Custom Ranges" mode you can enter multiple ranges separated by commas. Each range becomes a separate file. Example: "1-3, 5, 7-9" creates three files.',
      de: 'Ja, im Modus "Benutzerdefinierte Bereiche" können Sie mehrere durch Kommas getrennte Bereiche eingeben. Jeder Bereich wird eine separate Datei.',
      es: 'Sí, en el modo "Rangos personalizados" puede introducir varios rangos separados por comas. Cada rango se convierte en un archivo separado.',
      fr: 'Oui, en mode "Plages personnalisées" vous pouvez entrer plusieurs plages séparées par des virgules. Chaque plage devient un fichier séparé.',
      it: 'Sì, in modalità "Intervalli personalizzati" puoi inserire più intervalli separati da virgole. Ogni intervallo diventa un file separato.',
      pt: 'Sim, no modo "Intervalos personalizados" pode inserir vários intervalos separados por vírgulas. Cada intervalo torna-se um ficheiro separado.',
      sv: 'Ja, i läget "Anpassade intervall" kan du ange flera intervall separerade med kommatecken. Varje intervall blir en separat fil.',
      no: 'Ja, i modus "Egendefinerte områder" kan du angi flere områder atskilt med komma. Hvert område blir en separat fil.',
      is: 'Já, í ham "Sérsniðin bilsvið" getur þú slegið inn mörg bilsvið aðskilin með kommum. Hvert bilsvið verður aðskilin skrá.',
      tr: 'Evet, "Özel Aralıklar" modunda virgülle ayrılmış birden fazla aralık girebilirsiniz. Her aralık ayrı bir dosya haline gelir.',
      ar: 'نعم، في وضع "النطاقات المخصصة" يمكنك إدخال نطاقات متعددة مفصولة بفواصل. يصبح كل نطاق ملفًا منفصلًا.',
      fa: 'بله، در حالت "محدوده‌های سفارشی" می‌توانید چندین محدوده را با کاما از هم جدا کنید. هر محدوده یک فایل جداگانه می‌شود.',
      hi: 'हाँ, "कस्टम रेंज" मोड में आप अल्पविराम से अलग की गई कई श्रेणियां दर्ज कर सकते हैं। प्रत्येक श्रेणी एक अलग फ़ाइल बन जाती है।',
      ja: 'はい、「カスタム範囲」モードでは、カンマ区切りで複数の範囲を入力できます。各範囲が個別のファイルになります。',
      zh: '可以。在"自定义范围"模式下，您可以输入多个以逗号分隔的范围。每个范围成为一个单独的文件。',
    }},
  ],
  canonicalOverride: undefined,
  publishedAt: '2025-06-18',
  updatedAt: '2025-07-02',
};

export default article;
