import type { GuideArticle } from '@/types/guide';

const article: GuideArticle = {
  slug: 'how-to-compress-pdf-online',
  category: 'compress-pdf',
  title: {
    pl: 'Jak skutecznie skompresować PDF online',
    en: 'How to Effectively Compress a PDF Online',
    de: 'Wie man eine PDF-Datei online effektiv komprimiert',
    es: 'Cómo comprimir un PDF en línea de forma eficaz',
    fr: 'Comment compresser efficacement un PDF en ligne',
    it: 'Come comprimere efficacemente un PDF online',
    pt: 'Como compactar um PDF online de forma eficaz',
    sv: 'Hur man effektivt komprimerar en PDF online',
    no: 'Hvordan komprimere en PDF effektivt online',
    is: 'Hvernig á að þjappa PDF skrá á netinu á áhrifaríkan hátt',
    tr: 'Çevrimiçi bir PDF nasıl etkili bir şekilde sıkıştırılır',
    ar: 'كيفية ضغط ملف PDF عبر الإنترنت بفعالية',
    fa: 'چگونه یک PDF را به صورت آنلاین به طور مؤثر فشرده کنیم',
    hi: 'ऑनलाइन PDF को प्रभावी ढंग से कैसे संपीड़ित करें',
    ja: 'オンラインでPDFを効果的に圧縮する方法',
    zh: '如何有效地在線壓縮PDF',
  },
  excerpt: {
    pl: 'Dowiedz się, jak zmniejszyć rozmiar pliku PDF bez utraty jakości. Porównaj poziomy kompresji i wybierz najlepszy dla swoich potrzeb.',
    en: 'Learn how to reduce PDF file size without losing quality. Compare compression levels and choose the best one for your needs.',
    de: 'Erfahren Sie, wie Sie die PDF-Dateigröße reduzieren können, ohne an Qualität zu verlieren. Vergleichen Sie Komprimierungsstufen.',
    es: 'Aprenda a reducir el tamaño del archivo PDF sin perder calidad. Compare los niveles de compresión y elija el mejor.',
    fr: 'Apprenez à réduire la taille du fichier PDF sans perte de qualité. Comparez les niveaux de compression.',
    it: 'Scopri come ridurre le dimensioni del file PDF senza perdere qualità. Confronta i livelli di compressione.',
    pt: 'Aprenda a reduzir o tamanho do arquivo PDF sem perder qualidade. Compare os níveis de compressão.',
    sv: 'Lär dig hur du minskar PDF-filstorleken utan att förlora kvalitet. Jämför kompressionsnivåer.',
    no: 'Lær hvordan du reduserer PDF-filstørrelsen uten å miste kvalitet. Sammenlign kompresjonsnivåer.',
    is: 'Lærðu hvernig á að minnka PDF skráarstærð án þess að tapa gæðum. Berðu saman þjöppunarstig.',
    tr: 'Kaliteden ödün vermeden PDF dosya boyutunu nasıl azaltacağınızı öğrenin. Sıkıştırma seviyelerini karşılaştırın.',
    ar: 'تعلم كيفية تقليل حجم ملف PDF دون فقدان الجودة. قارن مستويات الضغط واختر الأفضل لاحتياجاتك.',
    fa: 'بیاموزید چگونه بدون کاهش کیفیت، اندازه فایل PDF را کاهش دهید. سطوح فشرده‌سازی را مقایسه کنید.',
    hi: 'गुणवत्ता खोए बिना PDF फ़ाइल का आकार कम करना सीखें। संपीड़न स्तरों की तुलना करें और अपनी आवश्यकताओं के लिए सर्वश्रेष्ठ चुनें।',
    ja: '品質を損なうことなくPDFファイルサイズを削減する方法を学びます。圧縮レベルを比較して最適なものを選びましょう。',
    zh: '了解如何在保持质量的同时减小PDF文件大小。比较压缩级别并选择最适合您需求的级别。',
  },
  body: [
    {
      type: 'paragraph',
      text: {
        pl: 'Pliki PDF bywają bardzo duże, szczególnie gdy zawierają obrazy o wysokiej rozdzielczości, zeskanowane dokumenty lub osadzone czcionki. Kompresja PDF pozwala zmniejszyć rozmiar pliku nawet o 80%, co ułatwia wysyłanie e-mailem, przechowywanie w chmurze i udostępnianie. W tym przewodniku pokażemy Ci, jak skutecznie kompresować pliki PDF za pomocą darmowego narzędzia OptimaPDF.',
        en: 'PDF files can get very large, especially when they contain high-resolution images, scanned documents or embedded fonts. PDF compression can reduce file size by up to 80%, making it easier to email, store in the cloud and share. In this guide we will show you how to effectively compress PDF files using the free OptimaPDF tool.',
        de: 'PDF-Dateien können sehr groß werden, insbesondere wenn sie hochauflösende Bilder, gescannte Dokumente oder eingebettete Schriftarten enthalten. Die PDF-Komprimierung kann die Dateigröße um bis zu 80 % reduzieren, was das Versenden per E-Mail, die Speicherung in der Cloud und das Teilen erleichtert.',
        es: 'Los archivos PDF pueden ser muy grandes, especialmente cuando contienen imágenes de alta resolución, documentos escaneados o fuentes incrustadas. La compresión PDF puede reducir el tamaño del archivo hasta en un 80%.',
        fr: 'Les fichiers PDF peuvent devenir très volumineux, surtout lorsqu\'ils contiennent des images haute résolution, des documents scannés ou des polices intégrées. La compression PDF peut réduire la taille du fichier jusqu\'à 80 %.',
        it: 'I file PDF possono diventare molto grandi, specialmente quando contengono immagini ad alta risoluzione, documenti scansionati o font incorporati. La compressione PDF può ridurre le dimensioni del file fino all\'80%.',
        pt: 'Os arquivos PDF podem ficar muito grandes, especialmente quando contêm imagens de alta resolução, documentos digitalizados ou fontes incorporadas. A compressão PDF pode reduzir o tamanho do arquivo em até 80%.',
        sv: 'PDF-filer kan bli mycket stora, särskilt när de innehåller högupplösta bilder, skannade dokument eller inbäddade typsnitt. PDF-komprimering kan minska filstorleken med upp till 80 %.',
        no: 'PDF-filer kan bli veldig store, spesielt når de inneholder høyoppløselige bilder, skannede dokumenter eller innebygde skrifter. PDF-komprimering kan redusere filstørrelsen med opptil 80 %.',
        is: 'PDF skrár geta orðið mjög stórar, sérstaklega þegar þær innihalda háskerpu myndir, skönnuð skjöl eða innfelldar leturgerðir. PDF þjöppun getur minnkað skráarstærð um allt að 80%.',
        tr: 'PDF dosyaları, özellikle yüksek çözünürlüklü görüntüler, taranmış belgeler veya gömülü yazı tipleri içerdiklerinde çok büyük olabilir. PDF sıkıştırma, dosya boyutunu %80\'e kadar azaltabilir.',
        ar: 'يمكن أن تصبح ملفات PDF كبيرة جدًا، خاصة عندما تحتوي على صور عالية الدقة أو مستندات ممسوحة ضوئيًا أو خطوط مضمنة. يمكن أن يقلل ضغط PDF من حجم الملف بنسبة تصل إلى 80%.',
        fa: 'فایل‌های PDF می‌توانند بسیار بزرگ شوند، به خصوص زمانی که شامل تصاویر با وضوح بالا، اسناد اسکن شده یا فونت‌های جاسازی شده باشند. فشرده‌سازی PDF می‌تواند اندازه فایل را تا ۸۰٪ کاهش دهد.',
        hi: 'PDF फ़ाइलें बहुत बड़ी हो सकती हैं, खासकर जब उनमें उच्च-रिज़ॉल्यूशन वाली छवियां, स्कैन किए गए दस्तावेज़ या एम्बेडेड फ़ॉन्ट हों। PDF संपीड़न फ़ाइल आकार को 80% तक कम कर सकता है।',
        ja: 'PDFファイルは、高解像度の画像、スキャン文書、埋め込みフォントが含まれている場合、非常に大きくなることがあります。PDF圧縮により、ファイルサイズを最大80%削減できます。',
        zh: 'PDF文件可能会变得非常大，尤其是当它们包含高分辨率图像、扫描文档或嵌入字体时。PDF压缩可以将文件大小减少多达80%。',
      },
    },
    {
      type: 'cta',
      tool: 'compress',
    },
    {
      type: 'heading',
      level: 2,
      text: {
        pl: 'Czym jest kompresja PDF?',
        en: 'What is PDF Compression?',
        de: 'Was ist PDF-Komprimierung?',
        es: '¿Qué es la compresión PDF?',
        fr: 'Qu\'est-ce que la compression PDF ?',
        it: 'Cos\'è la compressione PDF?',
        pt: 'O que é compressão de PDF?',
        sv: 'Vad är PDF-komprimering?',
        no: 'Hva er PDF-komprimering?',
        is: 'Hvað er PDF þjöppun?',
        tr: 'PDF Sıkıştırma Nedir?',
        ar: 'ما هو ضغط PDF؟',
        fa: 'فشرده‌سازی PDF چیست؟',
        hi: 'PDF संपीड़न क्या है?',
        ja: 'PDF圧縮とは？',
        zh: '什么是PDF压缩？',
      },
    },
    {
      type: 'paragraph',
      text: {
        pl: 'Kompresja PDF to proces zmniejszania rozmiaru pliku PDF poprzez optymalizację obrazów, usuwanie zbędnych metadanych i stosowanie wydajniejszych metod kodowania. OptimaPDF oferuje trzy poziomy kompresji — od lekkiej optymalizacji po agresywne zmniejszanie rozmiaru.',
        en: 'PDF compression is the process of reducing PDF file size by optimizing images, removing unnecessary metadata and applying more efficient encoding methods. OptimaPDF offers three compression levels — from light optimization to aggressive size reduction.',
        de: 'PDF-Komprimierung ist der Prozess der Reduzierung der PDF-Dateigröße durch Optimierung von Bildern, Entfernen unnötiger Metadaten und Anwendung effizienterer Kodierungsmethoden.',
        es: 'La compresión PDF es el proceso de reducir el tamaño del archivo PDF optimizando imágenes, eliminando metadatos innecesarios y aplicando métodos de codificación más eficientes.',
        fr: 'La compression PDF est le processus de réduction de la taille du fichier PDF en optimisant les images, en supprimant les métadonnées inutiles et en appliquant des méthodes de codage plus efficaces.',
        it: 'La compressione PDF è il processo di riduzione delle dimensioni del file PDF ottimizzando le immagini, rimuovendo metadati non necessari e applicando metodi di codifica più efficienti.',
        pt: 'A compressão PDF é o processo de redução do tamanho do arquivo PDF através da otimização de imagens, remoção de metadados desnecessários e aplicação de métodos de codificação mais eficientes.',
        sv: 'PDF-komprimering är processen att minska PDF-filstorleken genom att optimera bilder, ta bort onödig metadata och tillämpa effektivare kodningsmetoder.',
        no: 'PDF-komprimering er prosessen med å redusere PDF-filstørrelsen ved å optimalisere bilder, fjerne unødvendige metadata og bruke mer effektive kodingsmetoder.',
        is: 'PDF þjöppun er ferlið við að minnka PDF skráarstærð með því að hámarka myndir, fjarlægja óþarfa lýsigögn og beita skilvirkari kótunaraðferðum.',
        tr: 'PDF sıkıştırma, görüntüleri optimize ederek, gereksiz meta verileri kaldırarak ve daha verimli kodlama yöntemleri uygulayarak PDF dosya boyutunu azaltma işlemidir.',
        ar: 'ضغط PDF هو عملية تقليل حجم ملف PDF عن طريق تحسين الصور وإزالة البيانات الوصفية غير الضرورية وتطبيق طرق ترميز أكثر كفاءة.',
        fa: 'فشرده‌سازی PDF فرآیند کاهش اندازه فایل PDF با بهینه‌سازی تصاویر، حذف فراداده‌های غیرضروری و اعمال روش‌های کدگذاری کارآمدتر است.',
        hi: 'PDF संपीड़न छवियों को अनुकूलित करके, अनावश्यक मेटाडेटा हटाकर और अधिक कुशल एन्कोडिंग विधियों को लागू करके PDF फ़ाइल आकार को कम करने की प्रक्रिया है।',
        ja: 'PDF圧縮とは、画像の最適化、不要なメタデータの削除、より効率的なエンコード方法の適用により、PDFファイルサイズを削減するプロセスです。',
        zh: 'PDF压缩是通过优化图像、删除不必要的元数据和应用更高效的编码方法来减小PDF文件大小的过程。',
      },
    },
    {
      type: 'heading',
      level: 2,
      text: {
        pl: 'Jak skompresować PDF krok po kroku',
        en: 'How to Compress a PDF Step by Step',
        de: 'Wie man eine PDF Schritt für Schritt komprimiert',
        es: 'Cómo comprimir un PDF paso a paso',
        fr: 'Comment compresser un PDF étape par étape',
        it: 'Come comprimere un PDF passo dopo passo',
        pt: 'Como comprimir um PDF passo a passo',
        sv: 'Hur man komprimerar en PDF steg för steg',
        no: 'Hvordan komprimere en PDF trinn for trinn',
        is: 'Hvernig á að þjappa PDF skref fyrir skref',
        tr: 'PDF Nasıl Adım Adım Sıkıştırılır',
        ar: 'كيفية ضغط PDF خطوة بخطوة',
        fa: 'نحوه فشرده‌سازی PDF گام به گام',
        hi: 'चरण दर चरण PDF कैसे संपीड़ित करें',
        ja: 'ステップバイステップでPDFを圧縮する方法',
        zh: '如何逐步压缩PDF',
      },
    },
    {
      type: 'step',
      title: {
        pl: 'Wybierz poziom kompresji',
        en: 'Choose the Compression Level',
        de: 'Wählen Sie die Komprimierungsstufe',
        es: 'Elija el nivel de compresión',
        fr: 'Choisissez le niveau de compression',
        it: 'Scegli il livello di compressione',
        pt: 'Escolha o nível de compressão',
        sv: 'Välj kompressionsnivå',
        no: 'Velg kompresjonsnivå',
        is: 'Veldu þjöppunarstig',
        tr: 'Sıkıştırma seviyesini seçin',
        ar: 'اختر مستوى الضغط',
        fa: 'سطح فشرده‌سازی را انتخاب کنید',
        hi: 'संपीड़न स्तर चुनें',
        ja: '圧縮レベルを選択',
        zh: '选择压缩级别',
      },
      text: {
        pl: 'Niski — minimalna utrata jakości, umiarkowane zmniejszenie rozmiaru. Zalecany — zbalansowany stosunek jakości do rozmiaru, najlepszy do codziennego użytku. Ekstremalny — maksymalne zmniejszenie, dla plików które muszą być jak najmniejsze. Domyślnie wybrany jest poziom Zalecany i w większości przypadków jest to optymalny wybór.',
        en: 'Low — minimal quality loss, moderate size reduction. Recommended — balanced quality-to-size ratio, best for everyday use. Extreme — maximum reduction, for files that need to be as small as possible. Recommended is selected by default and is the optimal choice in most cases.',
        de: 'Niedrig — minimaler Qualitätsverlust, moderate Größenreduzierung. Empfohlen — ausgewogenes Verhältnis von Qualität zu Größe, am besten für den täglichen Gebrauch. Extrem — maximale Reduzierung.',
        es: 'Bajo: pérdida de calidad mínima, reducción de tamaño moderada. Recomendado: relación calidad-tamaño equilibrada, ideal para uso diario. Extremo: reducción máxima.',
        fr: 'Faible – perte de qualité minimale, réduction de taille modérée. Recommandé – rapport qualité/taille équilibré, idéal pour un usage quotidien. Extrême – réduction maximale.',
        it: 'Basso – perdita di qualità minima, riduzione moderata. Consigliato – rapporto qualità/dimensioni bilanciato, ideale per l\'uso quotidiano. Estremo – riduzione massima.',
        pt: 'Baixo – perda de qualidade mínima, redução moderada de tamanho. Recomendado – relação qualidade/tamanho equilibrada, ideal para uso diário. Extremo – redução máxima.',
        sv: 'Låg – minimal kvalitetsförlust, måttlig storleksminskning. Rekommenderas – balanserat kvalitets-/storleksförhållande, bäst för dagligt bruk. Extrem – maximal minskning.',
        no: 'Lav – minimalt kvalitetstap, moderat størrelsesreduksjon. Anbefalt – balansert forhold mellom kvalitet og størrelse, best for daglig bruk. Ekstrem – maksimal reduksjon.',
        is: 'Lágt – lágmarks gæðatap, hófleg stærðarminnkun. Mælt með – jafnvægi milli gæða og stærðar, best fyrir daglega notkun. Öfgafullt – hámarksminnkun.',
        tr: 'Düşük – minimum kalite kaybı, orta düzeyde boyut azaltma. Önerilen – dengeli kalite/boyut oranı, günlük kullanım için en iyisi. Aşırı – maksimum azaltma.',
        ar: 'منخفض — فقدان بسيط في الجودة، تقليل معتدل في الحجم. موصى به — نسبة متوازنة بين الجودة والحجم، الأفضل للاستخدام اليومي. شديد — أقصى تقليل.',
        fa: 'کم — حداقل افت کیفیت، کاهش متوسط اندازه. توصیه شده — نسبت متوازن کیفیت به اندازه، بهترین برای استفاده روزانه. شدید — حداکثر کاهش.',
        hi: 'निम्न — न्यूनतम गुणवत्ता हानि, मध्यम आकार कमी। अनुशंसित — संतुलित गुणवत्ता-आकार अनुपात, दैनिक उपयोग के लिए सर्वश्रेष्ठ। अत्यधिक — अधिकतम कमी।',
        ja: '低 — 最小限の品質低下、適度なサイズ削減。推奨 — 品質とサイズのバランスが取れた最適解。最大 — 最大限の削減。',
        zh: '低 — 质量损失最小，大小适度减小。推荐 — 质量与大小的平衡比例，最适合日常使用。极致 — 最大程度减小。',
      },
    },
    {
      type: 'step',
      title: {
        pl: 'Przeciągnij plik PDF w pole wyboru',
        en: 'Drop the PDF File into the Upload Area',
        de: 'Ziehen Sie die PDF-Datei in den Upload-Bereich',
        es: 'Arrastre el archivo PDF al área de carga',
        fr: 'Déposez le fichier PDF dans la zone de téléchargement',
        it: 'Trascina il file PDF nell\'area di caricamento',
        pt: 'Arraste o ficheiro PDF para a área de carregamento',
        sv: 'Släpp PDF-filen i uppladdningsområdet',
        no: 'Slipp PDF-filen i opplastingsområdet',
        is: 'Slepptu PDF skránni í hleðslusvæðið',
        tr: 'PDF dosyasını yükleme alanına bırakın',
        ar: 'أسقط ملف PDF في منطقة التحميل',
        fa: 'فایل PDF را در منطقه بارگذاری رها کنید',
        hi: 'PDF फ़ाइल को अपलोड क्षेत्र में छोड़ें',
        ja: 'アップロードエリアにPDFファイルをドロップ',
        zh: '将PDF文件拖放到上传区域',
      },
      text: {
        pl: 'Możesz też kliknąć w pole wyboru, aby otworzyć okno dialogowe i wybrać plik z dysku. Obsługiwane są pliki PDF o dowolnym rozmiarze — wszystkie operacje wykonywane są lokalnie w Twojej przeglądarce.',
        en: 'You can also click the upload area to open a dialog and select a file from your disk. PDF files of any size are supported — all operations are performed locally in your browser.',
        de: 'Sie können auch auf den Upload-Bereich klicken, um einen Dialog zu öffnen und eine Datei von Ihrer Festplatte auszuwählen. PDF-Dateien beliebiger Größe werden unterstützt.',
        es: 'También puede hacer clic en el área de carga para abrir un diálogo y seleccionar un archivo. Se admiten archivos PDF de cualquier tamaño.',
        fr: 'Vous pouvez également cliquer sur la zone de téléchargement pour ouvrir une boîte de dialogue et sélectionner un fichier. Les fichiers PDF de toutes tailles sont pris en charge.',
        it: 'Puoi anche cliccare sull\'area di caricamento per aprire una finestra di dialogo e selezionare un file dal disco. Sono supportati file PDF di qualsiasi dimensione.',
        pt: 'Também pode clicar na área de carregamento para abrir um diálogo e selecionar um ficheiro. São suportados ficheiros PDF de qualquer tamanho.',
        sv: 'Du kan också klicka på uppladdningsområdet för att öppna en dialogruta och välja en fil från din disk. PDF-filer av alla storlekar stöds.',
        no: 'Du kan også klikke på opplastingsområdet for å åpne en dialog og velge en fil fra disken. PDF-filer av alle størrelser støttes.',
        is: 'Þú getur líka smellt á hleðslusvæðið til að opna glugga og velja skrá af disknum þínum. PDF skrár af hvaða stærð sem er eru studdar.',
        tr: 'Ayrıca yükleme alanına tıklayarak bir iletişim kutusu açabilir ve diskinizden bir dosya seçebilirsiniz. Her boyuttaki PDF dosyası desteklenir.',
        ar: 'يمكنك أيضًا النقر فوق منطقة التحميل لفتح مربع حوار وتحديد ملف من القرص. يتم دعم ملفات PDF بأي حجم.',
        fa: 'همچنین می‌توانید روی منطقه بارگذاری کلیک کنید تا یک کادر محاوره‌ای باز کرده و فایلی را از دیسک خود انتخاب کنید. فایل‌های PDF در هر اندازه‌ای پشتیبانی می‌شوند.',
        hi: 'आप अपलोड क्षेत्र पर क्लिक करके एक डायलॉग खोल सकते हैं और अपनी डिस्क से एक फ़ाइल चुन सकते हैं। किसी भी आकार की PDF फ़ाइलें समर्थित हैं।',
        ja: 'アップロードエリアをクリックしてダイアログを開き、ディスクからファイルを選択することもできます。あらゆるサイズのPDFファイルに対応しています。',
        zh: '您也可以点击上传区域打开对话框，从磁盘中选择文件。支持任何大小的PDF文件。',
      },
    },
    {
      type: 'step',
      title: {
        pl: 'Kliknij "Kompresuj PDF"',
        en: 'Click "Compress PDF"',
        de: 'Klicken Sie auf "PDF komprimieren"',
        es: 'Haga clic en "Comprimir PDF"',
        fr: 'Cliquez sur "Compresser le PDF"',
        it: 'Clicca su "Comprimi PDF"',
        pt: 'Clique em "Comprimir PDF"',
        sv: 'Klicka på "Komprimera PDF"',
        no: 'Klikk på "Komprimer PDF"',
        is: 'Smelltu á "Þjappa PDF"',
        tr: '"PDF Sıkıştır"a tıklayın',
        ar: 'انقر على "ضغط PDF"',
        fa: 'روی "فشرده‌سازی PDF" کلیک کنید',
        hi: '"PDF संपीड़ित करें" पर क्लिक करें',
        ja: '「PDFを圧縮」をクリック',
        zh: '点击"压缩PDF"',
      },
      text: {
        pl: 'Proces kompresji trwa zwykle kilka sekund. Po zakończeniu zobaczysz podgląd z informacją o stopniu zmniejszenia pliku. Możesz od razu pobrać skompresowany PDF, klikając przycisk pobierania.',
        en: 'The compression process usually takes a few seconds. Once complete you will see a preview with information about the file size reduction. You can download the compressed PDF immediately by clicking the download button.',
        de: 'Der Komprimierungsvorgang dauert in der Regel einige Sekunden. Nach Abschluss sehen Sie eine Vorschau mit Informationen zur Dateigrößenreduzierung. Sie können die komprimierte PDF sofort herunterladen.',
        es: 'El proceso de compresión suele tardar unos segundos. Al finalizar verá una vista previa con información sobre la reducción del tamaño. Puede descargar el PDF comprimido inmediatamente.',
        fr: 'Le processus de compression prend généralement quelques secondes. Une fois terminé, vous verrez un aperçu avec des informations sur la réduction de taille. Vous pouvez télécharger le PDF compressé immédiatement.',
        it: 'Il processo di compressione richiede solitamente alcuni secondi. Al termine vedrai un\'anteprima con informazioni sulla riduzione delle dimensioni. Puoi scaricare il PDF compresso immediatamente.',
        pt: 'O processo de compressão normalmente leva alguns segundos. Após a conclusão verá uma pré-visualização com informações sobre a redução do tamanho. Pode descarregar o PDF comprimido imediatamente.',
        sv: 'Komprimeringsprocessen tar vanligtvis några sekunder. När den är klar ser du en förhandsvisning med information om storleksminskningen. Du kan ladda ner den komprimerade PDF:en omedelbart.',
        no: 'Kompresjonsprosessen tar vanligvis noen sekunder. Når den er ferdig ser du en forhåndsvisning med informasjon om størrelsesreduksjonen. Du kan laste ned den komprimerte PDF-en umiddelbart.',
        is: 'Þjöppunarferlið tekur venjulega nokkrar sekúndur. Þegar því er lokið sérðu forskoðun með upplýsingum um minnkun skráarstærðar. Þú getur hlaðið niður þjöppuðu PDF skránni strax.',
        tr: 'Sıkıştırma işlemi genellikle birkaç saniye sürer. Tamamlandığında, dosya boyutu küçültme hakkında bilgi içeren bir önizleme göreceksiniz. Sıkıştırılmış PDF\'i hemen indirebilirsiniz.',
        ar: 'عملية الضغط تستغرق عادة بضع ثوانٍ. عند الانتهاء، سترى معاينة مع معلومات حول تقليل حجم الملف. يمكنك تنزيل PDF المضغوط فورًا.',
        fa: 'فرآیند فشرده‌سازی معمولاً چند ثانیه طول می‌کشد. پس از اتمام، پیش‌نمایشی با اطلاعات کاهش اندازه فایل مشاهده خواهید کرد. می‌توانید بلافاصله PDF فشرده شده را دانلود کنید.',
        hi: 'संपीड़न प्रक्रिया में आमतौर पर कुछ सेकंड लगते हैं। पूरा होने पर, आप फ़ाइल आकार में कमी के बारे में जानकारी के साथ एक पूर्वावलोकन देखेंगे। आप तुरंत संपीड़ित PDF डाउनलोड कर सकते हैं।',
        ja: '圧縮処理は通常数秒で完了します。完了すると、ファイルサイズの削減に関する情報を含むプレビューが表示されます。圧縮されたPDFをすぐにダウンロードできます。',
        zh: '压缩过程通常需要几秒钟。完成后，您将看到预览，其中包含文件大小减少的信息。您可以立即下载压缩后的PDF。',
      },
    },
    {
      type: 'cta',
      tool: 'compress',
    },
    {
      type: 'heading',
      level: 3,
      text: {
        pl: 'Kiedy użyć poszczególnych poziomów kompresji?',
        en: 'When to Use Each Compression Level?',
        de: 'Wann sollte man welche Komprimierungsstufe verwenden?',
        es: '¿Cuándo usar cada nivel de compresión?',
        fr: 'Quand utiliser chaque niveau de compression ?',
        it: 'Quando utilizzare ciascun livello di compressione?',
        pt: 'Quando usar cada nível de compressão?',
        sv: 'När ska man använda varje kompressionsnivå?',
        no: 'Når skal man bruke hvert kompresjonsnivå?',
        is: 'Hvenær á að nota hvert þjöppunarstig?',
        tr: 'Her sıkıştırma seviyesi ne zaman kullanılmalı?',
        ar: 'متى تستخدم كل مستوى ضغط؟',
        fa: 'چه زمانی از هر سطح فشرده‌سازی استفاده کنیم؟',
        hi: 'प्रत्येक संपीड़न स्तर का उपयोग कब करें?',
        ja: '各圧縮レベルはいつ使うべきか？',
        zh: '何时使用每个压缩级别？',
      },
    },
    {
      type: 'list',
      items: [
        {
          pl: 'Niski: dokumenty tekstowe, które będą drukowane — jakość pozostaje niemal identyczna z oryginałem',
          en: 'Low: text documents that will be printed — quality remains nearly identical to the original',
          de: 'Niedrig: Textdokumente zum Drucken – die Qualität bleibt nahezu identisch zum Original',
          es: 'Bajo: documentos de texto que se imprimirán: la calidad sigue siendo casi idéntica al original',
          fr: 'Faible : documents texte à imprimer — la qualité reste quasi identique à l\'original',
          it: 'Basso: documenti di testo da stampare — la qualità rimane pressoché identica all\'originale',
          pt: 'Baixo: documentos de texto que serão impressos — a qualidade permanece quase idêntica ao original',
          sv: 'Låg: textdokument som ska skrivas ut — kvaliteten förblir nästan identisk med originalet',
          no: 'Lav: tekstdokumenter som skal skrives ut — kvaliteten forblir nesten identisk med originalen',
          is: 'Lágt: textaskjöl sem verða prentuð — gæðin haldast næstum óbreytt frá frumritinu',
          tr: 'Düşük: yazdırılacak metin belgeleri — kalite orijinaline neredeyse aynı kalır',
          ar: 'منخفض: المستندات النصية التي ستتم طباعتها — تظل الجودة مطابقة تقريبًا للأصل',
          fa: 'کم: اسناد متنی که چاپ خواهند شد — کیفیت تقریباً مشابه اصلی باقی می‌ماند',
          hi: 'निम्न: मुद्रित किए जाने वाले टेक्स्ट दस्तावेज़ — गुणवत्ता मूल के लगभग समान रहती है',
          ja: '低: 印刷するテキスト文書 — 品質はオリジナルとほぼ同じ',
          zh: '低: 将要打印的文本文档 — 质量与原始文件几乎相同',
        },
        {
          pl: 'Zalecany: codzienne udostępnianie plików — dobry balans między rozmiarem a jakością',
          en: 'Recommended: everyday file sharing — good balance between size and quality',
          de: 'Empfohlen: tägliches Teilen von Dateien – gute Balance zwischen Größe und Qualität',
          es: 'Recomendado: uso diario: buen equilibrio entre tamaño y calidad',
          fr: 'Recommandé : partage quotidien de fichiers — bon équilibre entre taille et qualité',
          it: 'Consigliato: condivisione quotidiana di file — buon equilibrio tra dimensioni e qualità',
          pt: 'Recomendado: partilha diária de ficheiros — bom equilíbrio entre tamanho e qualidade',
          sv: 'Rekommenderad: vardaglig fildelning — bra balans mellan storlek och kvalitet',
          no: 'Anbefalt: daglig fildeling — god balanse mellom størrelse og kvalitet',
          is: 'Mælt með: dagleg skráadeild — gott jafnvægi milli stærðar og gæða',
          tr: 'Önerilen: günlük dosya paylaşımı — boyut ve kalite arasında iyi denge',
          ar: 'موصى به: مشاركة الملفات اليومية — توازن جيد بين الحجم والجودة',
          fa: 'توصیه شده: اشتراک‌گذاری روزانه فایل — تعادل خوب بین اندازه و کیفیت',
          hi: 'अनुशंसित: दैनिक फ़ाइल साझाकरण — आकार और गुणवत्ता के बीच अच्छा संतुलन',
          ja: '推奨: 日常的なファイル共有 — サイズと品質のバランスが良い',
          zh: '推荐: 日常文件共享 — 大小和质量之间的良好平衡',
        },
        {
          pl: 'Ekstremalny: załączniki e-mail i archiwizacja — największe zmniejszenie kosztem jakości obrazów',
          en: 'Extreme: email attachments and archiving — greatest reduction at the cost of image quality',
          de: 'Extrem: E-Mail-Anhänge und Archivierung – größte Reduzierung auf Kosten der Bildqualität',
          es: 'Extremo: archivos adjuntos de correo electrónico y archivado: la mayor reducción a costa de la calidad de imagen',
          fr: 'Extrême : pièces jointes et archivage — la plus grande réduction au détriment de la qualité d\'image',
          it: 'Estremo: allegati email e archiviazione — massima riduzione a scapito della qualità delle immagini',
          pt: 'Extremo: anexos de e-mail e arquivo — maior redução em troca da qualidade das imagens',
          sv: 'Extrem: e-postbilagor och arkivering — störst minskning på bekostnad av bildkvalitet',
          no: 'Ekstrem: e-postvedlegg og arkivering — størst reduksjon på bekostning av bildekvalitet',
          is: 'Öfgafullt: tölvupóstviðhengi og skjalasafn — mesta minnkun á kostnað myndgæða',
          tr: 'Aşırı: e-posta ekleri ve arşivleme — görüntü kalitesi pahasına en büyük azaltma',
          ar: 'شديد: مرفقات البريد الإلكتروني والأرشفة — أكبر تقليل على حساب جودة الصور',
          fa: 'شدید: پیوست‌های ایمیل و بایگانی — بیشترین کاهش به قیمت کیفیت تصاویر',
          hi: 'अत्यधिक: ईमेल अटैचमेंट और आर्काइविंग — छवि गुणवत्ता की कीमत पर सबसे बड़ी कमी',
          ja: '最大: メール添付とアーカイブ — 画質を犠牲に最大の削減',
          zh: '极致: 电子邮件附件和归档 — 以图像质量为代价的最大减小',
        },
      ],
    },
    {
      type: 'cta',
      tool: 'compress',
    },
  ],
  relatedTool: 'compress',
  faq: [
    {
      q: {
        pl: 'Czy kompresja PDF obniża jakość tekstu?',
        en: 'Does PDF compression reduce text quality?',
        de: 'Verschlechtert die PDF-Komprimierung die Textqualität?',
        es: '¿La compresión de PDF reduce la calidad del texto?',
        fr: 'La compression PDF réduit-elle la qualité du texte ?',
        it: 'La compressione PDF riduce la qualità del testo?',
        pt: 'A compressão de PDF reduz a qualidade do texto?',
        sv: 'Minskar PDF-komprimering textkvaliteten?',
        no: 'Reduserer PDF-komprimering tekstkvaliteten?',
        is: 'Dregur PDF þjöppun úr gæðum texta?',
        tr: 'PDF sıkıştırma metin kalitesini düşürür mü?',
        ar: 'هل يقلل ضغط PDF من جودة النص؟',
        fa: 'آیا فشرده‌سازی PDF کیفیت متن را کاهش می‌دهد؟',
        hi: 'क्या PDF संपीड़न से टेक्स्ट की गुणवत्ता कम होती है?',
        ja: 'PDF圧縮はテキストの品質を低下させますか？',
        zh: 'PDF压缩会降低文本质量吗？',
      },
      a: {
        pl: 'Nie, kompresja PDF wpływa głównie na obrazy i osadzone grafiki. Tekst i wektory pozostają ostre, ponieważ są kompresowane bezstratnie przy użyciu algorytmu FlateDecode. Nawet przy ekstremalnym poziomie kompresji tekst pozostaje w pełni czytelny i wyszukiwalny.',
        en: 'No, PDF compression mainly affects images and embedded graphics. Text and vectors remain sharp because they are compressed losslessly using the FlateDecode algorithm. Even at extreme compression level the text remains fully readable and searchable.',
        de: 'Nein, die PDF-Komprimierung wirkt sich hauptsächlich auf Bilder und eingebettete Grafiken aus. Text und Vektoren bleiben scharf, da sie verlustfrei mit dem FlateDecode-Algorithmus komprimiert werden.',
        es: 'No, la compresión de PDF afecta principalmente a las imágenes y gráficos incrustados. El texto y los vectores permanecen nítidos porque se comprimen sin pérdida.',
        fr: 'Non, la compression PDF affecte principalement les images et les graphiques intégrés. Le texte et les vecteurs restent nets car ils sont compressés sans perte.',
        it: 'No, la compressione PDF influisce principalmente su immagini e grafica incorporata. Il testo e i vettori rimangono nitidi perché vengono compressi senza perdita.',
        pt: 'Não, a compressão de PDF afeta principalmente imagens e gráficos incorporados. O texto e os vetores permanecem nítidos porque são comprimidos sem perda.',
        sv: 'Nej, PDF-komprimering påverkar främst bilder och inbäddad grafik. Text och vektorer förblir skarpa eftersom de komprimeras förlustfritt.',
        no: 'Nei, PDF-komprimering påvirker hovedsakelig bilder og innebygget grafikk. Tekst og vektorer forblir skarpe fordi de komprimeres uten tap.',
        is: 'Nei, PDF þjöppun hefur aðallega áhrif á myndir og innfellda grafík. Texti og vektorar haldast skörp þar sem þeir eru þjappaðir án taps.',
        tr: 'Hayır, PDF sıkıştırma esas olarak görüntüleri ve gömülü grafikleri etkiler. Metin ve vektörler kayıpsız sıkıştırıldıkları için net kalır.',
        ar: 'لا، ضغط PDF يؤثر بشكل رئيسي على الصور والرسومات المضمنة. النص والمتجهات تبقى حادة لأنها مضغوطة بدون فقدان.',
        fa: 'خیر، فشرده‌سازی PDF عمدتاً بر تصاویر و گرافیک‌های جاسازی شده تأثیر می‌گذارد. متن و بردارها به دلیل فشرده‌سازی بدون اتلاف تیز باقی می‌مانند.',
        hi: 'नहीं, PDF संपीड़न मुख्य रूप से छवियों और एम्बेडेड ग्राफिक्स को प्रभावित करता है। टेक्स्ट और वेक्टर तेज बने रहते हैं क्योंकि वे दोषरहित संपीड़ित होते हैं।',
        ja: 'いいえ、PDF圧縮は主に画像と埋め込みグラフィックに影響します。テキストとベクターは可逆圧縮されるため、鮮明なままです。',
        zh: '不会。PDF压缩主要影响图像和嵌入的图形。文本和矢量由于采用无损压缩，依然保持清晰。',
      },
    },
    {
      q: {
        pl: 'Jaki poziom kompresji wybrać do skanowanych dokumentów?',
        en: 'Which compression level should I choose for scanned documents?',
        de: 'Welche Komprimierungsstufe sollte ich für gescannte Dokumente wählen?',
        es: '¿Qué nivel de compresión elegir para documentos escaneados?',
        fr: 'Quel niveau de compression choisir pour les documents scannés ?',
        it: 'Quale livello di compressione scegliere per i documenti scansionati?',
        pt: 'Qual nível de compressão escolher para documentos digitalizados?',
        sv: 'Vilken kompressionsnivå ska jag välja för skannade dokument?',
        no: 'Hvilket kompresjonsnivå bør jeg velge for skannede dokumenter?',
        is: 'Hvaða þjöppunarstig ætti ég að velja fyrir skönnuð skjöl?',
        tr: 'Taranmış belgeler için hangi sıkıştırma seviyesini seçmeliyim?',
        ar: 'ما مستوى الضغط الذي يجب اختياره للمستندات الممسوحة ضوئيًا؟',
        fa: 'برای اسناد اسکن شده کدام سطح فشرده‌سازی را انتخاب کنم؟',
        hi: 'स्कैन किए गए दस्तावेज़ों के लिए मुझे कौन सा संपीड़न स्तर चुनना चाहिए?',
        ja: 'スキャン文書にはどの圧縮レベルを選ぶべきですか？',
        zh: '我应该为扫描文档选择哪个压缩级别？',
      },
      a: {
        pl: 'Do skanów polecamy poziom "Zalecany" — skutecznie redukuje rozmiar przy zachowaniu dobrej czytelności. Jeśli skany są wysokiej jakości i potrzebujesz zachować szczegóły, wybierz "Niski". Poziom "Ekstremalny" może znacząco obniżyć jakość skanów - używaj go tylko do archiwizacji, gdzie liczy się przede wszystkim mały rozmiar.',
        en: 'For scans we recommend the "Recommended" level — it effectively reduces size while maintaining good readability. If scans are high quality and you need to preserve details choose "Low". The "Extreme" level may significantly reduce scan quality — use it only for archiving where small size matters most.',
        de: 'Für Scans empfehlen wir die Stufe "Empfohlen" — sie reduziert die Größe effektiv bei guter Lesbarkeit. Bei hochwertigen Scans wählen Sie "Niedrig". "Extrem" kann die Scanqualität deutlich reduzieren.',
        es: 'Para escaneos recomendamos el nivel "Recomendado": reduce el tamaño de forma eficaz manteniendo una buena legibilidad. Para escaneos de alta calidad, elija "Bajo".',
        fr: 'Pour les scans, nous recommandons le niveau "Recommandé" — il réduit efficacement la taille tout en conservant une bonne lisibilité. Pour les scans de haute qualité, choisissez "Faible".',
        it: 'Per le scansioni consigliamo il livello "Consigliato" — riduce efficacemente le dimensioni mantenendo una buona leggibilità. Per scansioni di alta qualità scegli "Basso".',
        pt: 'Para digitalizações recomendamos o nível "Recomendado" — reduz eficazmente o tamanho mantendo uma boa legibilidade. Para digitalizações de alta qualidade escolha "Baixo".',
        sv: 'För skanningar rekommenderar vi nivån "Rekommenderad" — den minskar storleken effektivt med bibehållen god läsbarhet. För högkvalitativa skanningar välj "Låg".',
        no: 'For skanninger anbefaler vi nivået "Anbefalt" — det reduserer størrelsen effektivt med god lesbarhet. For høykvalitetsskanninger velg "Lav".',
        is: 'Fyrir skannanir mælum við með stiginu "Mælt með" — það minnkar stærðina á áhrifaríkan hátt en heldur góðum læsileika. Fyrir hágæða skannanir veldu "Lágt".',
        tr: 'Taramalar için "Önerilen" seviyesini öneririz — iyi okunabilirliği korurken boyutu etkili bir şekilde azaltır. Yüksek kaliteli taramalar için "Düşük" seçin.',
        ar: 'للمسح الضوئي، نوصي بمستوى "موصى به" — يقلل الحجم بشكل فعال مع الحفاظ على قابلية قراءة جيدة. للمسح عالي الجودة، اختر "منخفض".',
        fa: 'برای اسناد اسکن شده سطح "توصیه شده" را پیشنهاد می‌کنیم — اندازه را به طور مؤثر کاهش می‌دهد در حالی که خوانایی خوبی حفظ می‌کند. برای اسکن‌های با کیفیت بالا "کم" را انتخاب کنید.',
        hi: 'स्कैन के लिए हम "अनुशंसित" स्तर की सलाह देते हैं — यह अच्छी पठनीयता बनाए रखते हुए आकार को प्रभावी ढंग से कम करता है। उच्च गुणवत्ता वाले स्कैन के लिए "निम्न" चुनें।',
        ja: 'スキャンには「推奨」レベルをお勧めします — 読みやすさを維持しながら効果的にサイズを削減します。高品質スキャンの場合は「低」を選択してください。',
        zh: '对于扫描件，我们推荐"推荐"级别 — 它在保持良好可读性的同时有效减小大小。对于高质量扫描件，请选择"低"。',
      },
    },
    {
      q: {
        pl: 'Czy mogę skompresować wiele plików PDF jednocześnie?',
        en: 'Can I compress multiple PDF files at once?',
        de: 'Kann ich mehrere PDF-Dateien gleichzeitig komprimieren?',
        es: '¿Puedo comprimir varios archivos PDF a la vez?',
        fr: 'Puis-je compresser plusieurs fichiers PDF à la fois ?',
        it: 'Posso comprimere più file PDF contemporaneamente?',
        pt: 'Posso comprimir vários ficheiros PDF ao mesmo tempo?',
        sv: 'Kan jag komprimera flera PDF-filer samtidigt?',
        no: 'Kan jeg komprimere flere PDF-filer samtidig?',
        is: 'Get ég þjappað mörgum PDF skrám í einu?',
        tr: 'Aynı anda birden fazla PDF dosyasını sıkıştırabilir miyim?',
        ar: 'هل يمكنني ضغط عدة ملفات PDF في وقت واحد؟',
        fa: 'آیا می‌توانم چندین فایل PDF را همزمان فشرده کنم؟',
        hi: 'क्या मैं एक साथ कई PDF फ़ाइलों को संपीड़ित कर सकता हूँ?',
        ja: '複数のPDFファイルを同時に圧縮できますか？',
        zh: '我可以同时压缩多个PDF文件吗？',
      },
      a: {
        pl: 'Tak, OptimaPDF obsługuje kompresję wielu plików jednocześnie. Wystarczy przeciągnąć wszystkie pliki PDF w pole wyboru. Każdy plik zostanie skompresowany osobno, a wyniki zapakowane w jeden plik ZIP do pobrania.',
        en: 'Yes, OptimaPDF supports compressing multiple files at once. Simply drag all PDF files into the upload area. Each file will be compressed individually and the results packed into a single ZIP file for download.',
        de: 'Ja, OptimaPDF unterstützt die gleichzeitige Komprimierung mehrerer Dateien. Ziehen Sie einfach alle PDF-Dateien in den Upload-Bereich. Jede Datei wird einzeln komprimiert und die Ergebnisse in einer ZIP-Datei verpackt.',
        es: 'Sí, OptimaPDF admite la compresión de varios archivos a la vez. Simplemente arrastre todos los archivos PDF al área de carga. Cada archivo se comprimirá individualmente y los resultados se empaquetarán en un solo archivo ZIP.',
        fr: 'Oui, OptimaPDF prend en charge la compression de plusieurs fichiers à la fois. Il suffit de glisser tous les fichiers PDF dans la zone de téléchargement. Chaque fichier sera compressé individuellement et les résultats emballés dans un seul fichier ZIP.',
        it: 'Sì, OptimaPDF supporta la compressione di più file contemporaneamente. Basta trascinare tutti i file PDF nell\'area di caricamento. Ogni file verrà compresso singolarmente e i risultati impacchettati in un singolo file ZIP.',
        pt: 'Sim, o OptimaPDF suporta a compressão de vários ficheiros ao mesmo tempo. Basta arrastar todos os ficheiros PDF para a área de carregamento. Cada ficheiro será comprimido individualmente e os resultados embalados num único ficheiro ZIP.',
        sv: 'Ja, OptimaPDF stöder komprimering av flera filer samtidigt. Dra helt enkelt alla PDF-filer till uppladdningsområdet. Varje fil komprimeras individuellt och resultaten packas i en enda ZIP-fil.',
        no: 'Ja, OptimaPDF støtter komprimering av flere filer samtidig. Bare dra alle PDF-filer til opplastingsområdet. Hver fil komprimeres individuelt og resultatene pakkes i en enkelt ZIP-fil.',
        is: 'Já, OptimaPDF styður þjöppun margra skráa í einu. Dragðu einfaldlega allar PDF skrár inn á hleðslusvæðið. Hver skrá verður þjöppuð sérstaklega og niðurstöðunum pakkað í eina ZIP skrá.',
        tr: 'Evet, OptimaPDF aynı anda birden fazla dosyayı sıkıştırmayı destekler. Tüm PDF dosyalarını yükleme alanına sürüklemeniz yeterlidir. Her dosya ayrı ayrı sıkıştırılacak ve sonuçlar tek bir ZIP dosyasında paketlenecektir.',
        ar: 'نعم، يدعم OptimaPDF ضغط عدة ملفات في وقت واحد. ما عليك سوى سحب جميع ملفات PDF إلى منطقة التحميل. سيتم ضغط كل ملف على حدة وتعبئة النتائج في ملف ZIP واحد للتنزيل.',
        fa: 'بله، OptimaPDF از فشرده‌سازی همزمان چندین فایل پشتیبانی می‌کند. کافی است همه فایل‌های PDF را به منطقه بارگذاری بکشید. هر فایل به صورت جداگانه فشرده شده و نتایج در یک فایل ZIP بسته‌بندی می‌شود.',
        hi: 'हाँ, OptimaPDF एक साथ कई फ़ाइलों को संपीड़ित करने का समर्थन करता है। बस सभी PDF फ़ाइलों को अपलोड क्षेत्र में खींचें। प्रत्येक फ़ाइल को अलग-अलग संपीड़ित किया जाएगा और परिणाम डाउनलोड के लिए एक ZIP फ़ाइल में पैक किए जाएंगे।',
        ja: 'はい、OptimaPDFは複数のファイルを同時に圧縮することができます。すべてのPDFファイルをアップロードエリアにドラッグするだけで、各ファイルが個別に圧縮され、結果が1つのZIPファイルにまとめられます。',
        zh: '是的，OptimaPDF支持同时压缩多个文件。只需将所有PDF文件拖放到上传区域即可。每个文件将被单独压缩，结果打包成一个ZIP文件供下载。',
      },
    },
  ],
  canonicalOverride: undefined,
  publishedAt: '2025-06-01',
  updatedAt: '2025-07-02',
};

export default article;
