import type { GuideArticle } from '@/types/guide';

const article: GuideArticle = {
  slug: 'how-to-merge-pdf-online',
  category: 'merge-pdf',
  title: {
    pl: 'Jak połączyć pliki PDF w jeden dokument',
    en: 'How to Merge PDF Files into One Document',
    de: 'Wie man PDF-Dateien zu einem Dokument zusammenfügt',
    es: 'Cómo combinar archivos PDF en un solo documento',
    fr: 'Comment fusionner des fichiers PDF en un seul document',
    it: 'Come unire file PDF in un unico documento',
    pt: 'Como unir ficheiros PDF num único documento',
    sv: 'Hur man slår ihop PDF-filer till ett dokument',
    no: 'Hvordan slå sammen PDF-filer til ett dokument',
    is: 'Hvernig á að sameina PDF skrár í eitt skjal',
    tr: 'PDF dosyaları tek bir belgede nasıl birleştirilir',
    ar: 'كيفية دمج ملفات PDF في مستند واحد',
    fa: 'چگونه فایل‌های PDF را در یک سند ادغام کنیم',
    hi: 'PDF फ़ाइलों को एक दस्तावेज़ में कैसे मर्ज करें',
    ja: 'PDFファイルを1つの文書に結合する方法',
    zh: '如何将PDF文件合并为一个文档',
  },
  excerpt: {
    pl: 'Naucz się łączyć wiele plików PDF w jeden dokument. Prosta instrukcja krok po kroku z darmowym narzędziem online — bez instalacji i rejestracji.',
    en: 'Learn how to combine multiple PDF files into a single document. A simple step-by-step guide using a free online tool — no installation or registration required.',
    de: 'Erfahren Sie, wie Sie mehrere PDF-Dateien zu einem Dokument zusammenfügen. Eine einfache Schritt-für-Schritt-Anleitung — ohne Installation oder Registrierung.',
    es: 'Aprenda a combinar varios archivos PDF en un solo documento. Una guía sencilla paso a paso — sin instalación ni registro.',
    fr: 'Apprenez à fusionner plusieurs fichiers PDF en un seul document. Un guide simple étape par étape — sans installation ni inscription.',
    it: 'Impara a unire più file PDF in un unico documento. Una semplice guida passo dopo passo — senza installazione o registrazione.',
    pt: 'Aprenda a combinar vários ficheiros PDF num único documento. Um guia simples passo a passo — sem instalação ou registo.',
    sv: 'Lär dig hur du kombinerar flera PDF-filer till ett enda dokument. En enkel steg-för-steg-guide — ingen installation eller registrering krävs.',
    no: 'Lær hvordan du kombinerer flere PDF-filer til ett dokument. En enkel trinn-for-trinn-guide — ingen installasjon eller registrering.',
    is: 'Lærðu hvernig á að sameina margar PDF skrár í eitt skjal. Einföld skref-fyrir-skref leiðbeining — engin uppsetning eða skráning.',
    tr: 'Birden fazla PDF dosyasını tek bir belgede nasıl birleştireceğinizi öğrenin. Basit bir adım adım kılavuz — kurulum veya kayıt gerekmez.',
    ar: 'تعلم كيفية دمج ملفات PDF متعددة في مستند واحد. دليل بسيط خطوة بخطوة — بدون تثبيت أو تسجيل.',
    fa: 'بیاموزید چگونه چندین فایل PDF را در یک سند ترکیب کنید. یک راهنمای ساده گام به گام — بدون نصب یا ثبت‌نام.',
    hi: 'एकाधिक PDF फ़ाइलों को एक दस्तावेज़ में कैसे संयोजित करें सीखें। एक सरल चरण-दर-चरण मार्गदर्शिका — बिना इंस्टॉलेशन या रजिस्ट्रेशन के।',
    ja: '複数のPDFファイルを1つの文書に結合する方法を学びます。インストールや登録は不要です。',
    zh: '了解如何将多个PDF文件合并为一个文档。简单的分步指南 — 无需安装或注册。',
  },
  body: [
    { type: 'paragraph', text: {
      pl: 'Scalanie plików PDF to jedna z najczęściej wykonywanych operacji na dokumentach. Łączenie kilku plików w jeden jest przydatne, gdy masz osobne skany, faktury, raporty lub umowy i chcesz je połączyć w spójny dokument. OptimaPDF oferuje darmowe narzędzie do łączenia PDF, które działa w całości w przeglądarce.',
      en: 'Merging PDF files is one of the most common document operations. Combining several files into one is useful when you have separate scans, invoices, reports or contracts and want to create a cohesive document. OptimaPDF offers a free PDF merging tool that works entirely in your browser.',
      de: 'Das Zusammenführen von PDF-Dateien ist einer der häufigsten Dokumentvorgänge. Es ist nützlich, wenn Sie separate Scans, Rechnungen, Berichte oder Verträge haben und ein zusammenhängendes Dokument erstellen möchten.',
      es: 'La fusión de archivos PDF es una de las operaciones más comunes. Es útil cuando tienes escaneos, facturas, informes o contratos separados y quieres crear un documento cohesionado.',
      fr: 'La fusion de fichiers PDF est l\'une des opérations les plus courantes. Utile lorsque vous avez des scans, factures, rapports ou contrats séparés et souhaitez créer un document cohérent.',
      it: 'L\'unione di file PDF è una delle operazioni più comuni sui documenti. Utile quando hai scansioni, fatture, report o contratti separati e vuoi creare un documento coeso.',
      pt: 'A fusão de ficheiros PDF é uma das operações mais comuns. Útil quando tem digitalizações, faturas, relatórios ou contratos separados e pretende criar um documento coeso.',
      sv: 'Att slå ihop PDF-filer är en av de vanligaste dokumentoperationerna. Användbart när du har separata skanningar, fakturor, rapporter eller avtal.',
      no: 'Å slå sammen PDF-filer er en av de vanligste dokumentoperasjonene. Nyttig når du har separate skanninger, fakturaer, rapporter eller kontrakter.',
      is: 'Að sameina PDF skrár er ein algengasta skjalaaðgerðin. Gagnlegt þegar þú ert með aðskildar skannanir, reikninga, skýrslur eða samninga.',
      tr: 'PDF dosyalarını birleştirmek en yaygın belge işlemlerinden biridir. Ayrı taramalar, faturalar, raporlar veya sözleşmeleriniz olduğunda kullanışlıdır.',
      ar: 'دمج ملفات PDF هي إحدى أكثر عمليات المستندات شيوعًا. مفيدة عندما يكون لديك عمليات مسح ضوئي منفصلة أو فواتير أو تقارير أو عقود.',
      fa: 'ادغام فایل‌های PDF یکی از رایج‌ترین عملیات اسناد است. زمانی مفید است که اسکن‌ها، فاکتورها، گزارش‌ها یا قراردادهای جداگانه دارید.',
      hi: 'PDF फ़ाइलों को मर्ज करना सबसे सामान्य दस्तावेज़ संचालनों में से एक है। जब आपके पास अलग-अलग स्कैन, चालान, रिपोर्ट या अनुबंध हों तो उपयोगी है।',
      ja: 'PDFファイルの結合は最も一般的なドキュメント操作の1つです。別々のスキャン、請求書、レポート、契約書を1つにまとめるのに便利です。',
      zh: '合并PDF文件是最常见的文档操作之一。当您有单独的扫描件、发票、报告或合同时，需要将它们合并为一个 cohesive 文档。',
    }},
    { type: 'cta', tool: 'merge' },
    { type: 'heading', level: 2, text: {
      pl: 'Jak połączyć PDF krok po kroku',
      en: 'How to Merge PDF Step by Step',
      de: 'Wie man PDF Schritt für Schritt zusammenfügt',
      es: 'Cómo combinar PDF paso a paso',
      fr: 'Comment fusionner des PDF étape par étape',
      it: 'Come unire PDF passo dopo passo',
      pt: 'Como unir PDF passo a passo',
      sv: 'Hur man slår ihop PDF steg för steg',
      no: 'Hvordan slå sammen PDF trinn for trinn',
      is: 'Hvernig á að sameina PDF skref fyrir skref',
      tr: 'PDF Nasıl Adım Adım Birleştirilir',
      ar: 'كيفية دمج PDF خطوة بخطوة',
      fa: 'نحوه ادغام PDF گام به گام',
      hi: 'चरण दर चरण PDF कैसे मर्ज करें',
      ja: 'ステップバイステップでPDFを結合する方法',
      zh: '如何逐步合并PDF',
    }},
    { type: 'step', title: {
      pl: 'Dodaj pliki PDF',
      en: 'Add PDF Files',
      de: 'PDF-Dateien hinzufügen',
      es: 'Añadir archivos PDF',
      fr: 'Ajouter des fichiers PDF',
      it: 'Aggiungi file PDF',
      pt: 'Adicionar ficheiros PDF',
      sv: 'Lägg till PDF-filer',
      no: 'Legg til PDF-filer',
      is: 'Bæta við PDF skrám',
      tr: 'PDF Dosyaları Ekle',
      ar: 'إضافة ملفات PDF',
      fa: 'افزودن فایل‌های PDF',
      hi: 'PDF फ़ाइलें जोड़ें',
      ja: 'PDFファイルを追加',
      zh: '添加PDF文件',
    }, text: {
      pl: 'Przeciągnij pliki PDF w pole wyboru lub kliknij, aby wybrać je z dysku. Możesz dodać wiele plików jednocześnie — obsługujemy dowolną liczbę plików.',
      en: 'Drag and drop PDF files into the upload area or click to select them from your disk. You can add multiple files at once — we support any number of files.',
      de: 'Ziehen Sie PDF-Dateien in den Upload-Bereich oder klicken Sie, um sie von Ihrer Festplatte auszuwählen. Sie können mehrere Dateien gleichzeitig hinzufügen.',
      es: 'Arrastre archivos PDF al área de carga o haga clic para seleccionarlos. Puede añadir varios archivos a la vez.',
      fr: 'Glissez-déposez les fichiers PDF dans la zone de téléchargement ou cliquez pour les sélectionner. Vous pouvez ajouter plusieurs fichiers à la fois.',
      it: 'Trascina i file PDF nell\'area di caricamento o clicca per selezionarli dal disco. Puoi aggiungere più file contemporaneamente.',
      pt: 'Arraste ficheiros PDF para a área de carregamento ou clique para os selecionar. Pode adicionar vários ficheiros de uma vez.',
      sv: 'Dra och släpp PDF-filer till uppladdningsområdet eller klicka för att välja dem från din disk. Du kan lägga till flera filer samtidigt.',
      no: 'Dra og slipp PDF-filer til opplastingsområdet eller klikk for å velge dem fra disken. Du kan legge til flere filer samtidig.',
      is: 'Dragðu og slepptu PDF skrám á hleðslusvæðið eða smelltu til að velja þær af disknum þínum. Þú getur bætt við mörgum skrám í einu.',
      tr: 'PDF dosyalarını yükleme alanına sürükleyip bırakın veya tıklayarak diskinizden seçin. Aynı anda birden fazla dosya ekleyebilirsiniz.',
      ar: 'اسحب وأسقط ملفات PDF في منطقة التحميل أو انقر لتحديدها من القرص. يمكنك إضافة عدة ملفات في وقت واحد.',
      fa: 'فایل‌های PDF را به منطقه بارگذاری بکشید و رها کنید یا کلیک کنید تا از دیسک خود انتخاب کنید. می‌توانید چندین فایل را همزمان اضافه کنید.',
      hi: 'PDF फ़ाइलों को अपलोड क्षेत्र में खींचें और छोड़ें या अपनी डिस्क से चुनने के लिए क्लिक करें। आप एक साथ कई फ़ाइलें जोड़ सकते हैं।',
      ja: 'PDFファイルをアップロードエリアにドラッグ＆ドロップするか、クリックしてディスクから選択します。複数のファイルを同時に追加できます。',
      zh: '将PDF文件拖放到上传区域，或单击从磁盘中选择。您可以一次添加多个文件。',
    }},
    { type: 'step', title: {
      pl: 'Ustaw kolejność plików',
      en: 'Arrange File Order',
      de: 'Dateireihenfolge festlegen',
      es: 'Ordenar archivos',
      fr: 'Ordonner les fichiers',
      it: 'Ordina i file',
      pt: 'Ordenar ficheiros',
      sv: 'Ordna filordning',
      no: 'Angi filrekkefølge',
      is: 'Raða skrám',
      tr: 'Dosya Sırasını Ayarla',
      ar: 'ترتيب الملفات',
      fa: 'ترتیب فایل‌ها را تنظیم کنید',
      hi: 'फ़ाइल क्रम व्यवस्थित करें',
      ja: 'ファイルの順序を設定',
      zh: '排列文件顺序',
    }, text: {
      pl: 'Pliki można przeciągać, aby zmienić ich kolejność. Górny plik będzie pierwszy w scalonym dokumencie. Wskazówka: dodaj najpierw plik, który ma być pierwszy.',
      en: 'You can drag files to change their order. The top file will be first in the merged document. Tip: add the file that should come first first.',
      de: 'Sie können Dateien ziehen, um die Reihenfolge zu ändern. Die oberste Datei steht im zusammengefügten Dokument an erster Stelle.',
      es: 'Puede arrastrar los archivos para cambiar su orden. El archivo superior será el primero en el documento combinado.',
      fr: 'Vous pouvez faire glisser les fichiers pour changer leur ordre. Le fichier supérieur sera le premier dans le document fusionné.',
      it: 'Puoi trascinare i file per cambiarne l\'ordine. Il file in cima sarà il primo nel documento unito.',
      pt: 'Pode arrastar ficheiros para alterar a sua ordem. O ficheiro no topo será o primeiro no documento fundido.',
      sv: 'Du kan dra filer för att ändra ordningen. Den översta filen kommer först i det sammanslagna dokumentet.',
      no: 'Du kan dra filer for å endre rekkefølgen. Den øverste filen vil være først i det sammenslåtte dokumentet.',
      is: 'Þú getur dregið skrár til að breyta röð þeirra. Efsta skráin verður fyrst í sameinuðu skjalinu.',
      tr: 'Sıralamayı değiştirmek için dosyaları sürükleyebilirsiniz. Üstteki dosya birleştirilmiş belgede ilk olacaktır.',
      ar: 'يمكنك سحب الملفات لتغيير ترتيبها. سيكون الملف العلوي أول ملف في المستند المدمج.',
      fa: 'می‌توانید فایل‌ها را بکشید تا ترتیب آنها را تغییر دهید. فایل بالایی اولین فایل در سند ادغام شده خواهد بود.',
      hi: 'आप क्रम बदलने के लिए फ़ाइलों को खींच सकते हैं। शीर्ष फ़ाइल मर्ज किए गए दस्तावेज़ में पहली होगी।',
      ja: 'ファイルをドラッグして順序を変更できます。一番上のファイルが結合された文書の最初になります。',
      zh: '您可以拖动文件更改顺序。顶部文件将是合并文档中的第一个。',
    }},
    { type: 'step', title: {
      pl: 'Kliknij "Połącz PDF"',
      en: 'Click "Merge PDF"',
      de: 'Klicken Sie auf "PDF zusammenfügen"',
      es: 'Haga clic en "Combinar PDF"',
      fr: 'Cliquez sur "Fusionner les PDF"',
      it: 'Clicca su "Unisci PDF"',
      pt: 'Clique em "Unir PDF"',
      sv: 'Klicka på "Slå ihop PDF"',
      no: 'Klikk på "Slå sammen PDF"',
      is: 'Smelltu á "Sameina PDF"',
      tr: '"PDF Birleştir"e tıklayın',
      ar: 'انقر على "دمج PDF"',
      fa: 'روی "ادغام PDF" کلیک کنید',
      hi: '"PDF मर्ज करें" पर क्लिक करें',
      ja: '「PDFを結合」をクリック',
      zh: '点击"合并PDF"',
    }, text: {
      pl: 'Proces scalania trwa zwykle kilka sekund. Po zakończeniu plik zostanie automatycznie pobrany. Scalony dokument zachowuje strony, formatowanie i jakość z oryginalnych plików.',
      en: 'The merging process usually takes a few seconds. Once complete, the file will be downloaded automatically. The merged document retains the pages, formatting and quality of the original files.',
      de: 'Der Zusammenführungsprozess dauert in der Regel einige Sekunden. Die zusammengeführte Datei behält die Seiten, Formatierung und Qualität der Originaldateien.',
      es: 'El proceso de combinación suele tardar unos segundos. El documento combinado conserva las páginas, el formato y la calidad de los archivos originales.',
      fr: 'Le processus de fusion prend généralement quelques secondes. Le document fusionné conserve les pages, le formatage et la qualité des fichiers originaux.',
      it: 'Il processo di unione richiede solitamente alcuni secondi. Il documento unito conserva pagine, formattazione e qualità dei file originali.',
      pt: 'O processo de fusão normalmente leva alguns segundos. O documento fundido mantém as páginas, formatação e qualidade dos ficheiros originais.',
      sv: 'Sammanslagningsprocessen tar vanligtvis några sekunder. Det sammanslagna dokumentet behåller sidor, formatering och kvalitet.',
      no: 'Sammenslåingsprosessen tar vanligvis noen sekunder. Det sammenslåtte dokumentet beholder sider, formatering og kvalitet.',
      is: 'Sameiningarferlið tekur venjulega nokkrar sekúndur. Sameinaða skjalið heldur síðum, sniði og gæðum upprunalegu skránna.',
      tr: 'Birleştirme işlemi genellikle birkaç saniye sürer. Birleştirilen belge, orijinal dosyaların sayfalarını, biçimlendirmesini ve kalitesini korur.',
      ar: 'عملية الدمج تستغرق عادة بضع ثوانٍ. المستند المدمج يحتفظ بالصفحات والتنسيق والجودة من الملفات الأصلية.',
      fa: 'فرآیند ادغام معمولاً چند ثانیه طول می‌کشد. سند ادغام شده صفحات، قالب‌بندی و کیفیت فایل‌های اصلی را حفظ می‌کند.',
      hi: 'मर्ज प्रक्रिया में आमतौर पर कुछ सेकंड लगते हैं। मर्ज किया गया दस्तावेज़ मूल फ़ाइलों के पृष्ठों, फ़ॉर्मेटिंग और गुणवत्ता को बरकरार रखता है।',
      ja: '結合処理は通常数秒で完了します。結合された文書は、元のファイルのページ、書式、品質を保持します。',
      zh: '合并过程通常需要几秒钟。合并后的文档保留原始文件的页面、格式和质量。',
    }},
    { type: 'cta', tool: 'merge' },
    { type: 'heading', level: 3, text: {
      pl: 'Kiedy przydaje się scalanie PDF?',
      en: 'When is PDF Merging Useful?',
      de: 'Wann ist das Zusammenführen von PDFs sinnvoll?',
      es: '¿Cuándo es útil combinar PDF?',
      fr: 'Quand la fusion PDF est-elle utile ?',
      it: 'Quando è utile unire PDF?',
      pt: 'Quando é útil fundir PDF?',
      sv: 'När är det användbart att slå ihop PDF?',
      no: 'Når er det nyttig å slå sammen PDF?',
      is: 'Hvenær er gagnlegt að sameina PDF?',
      tr: 'PDF birleştirme ne zaman kullanışlıdır?',
      ar: 'متى يكون دمج PDF مفيدًا؟',
      fa: 'چه زمانی ادغام PDF مفید است؟',
      hi: 'PDF मर्ज करना कब उपयोगी है?',
      ja: 'PDF結合はどんな時に便利？',
      zh: '何时需要合并PDF？',
    }},
    { type: 'list', items: [
      { pl: 'Łączenie kilku zeskanowanych stron w jeden dokument', en: 'Combining several scanned pages into one document', de: 'Zusammenführen mehrerer gescannter Seiten zu einem Dokument', es: 'Combinar varias páginas escaneadas en un documento', fr: 'Combiner plusieurs pages scannées en un document', it: 'Unire più pagine scansionate in un documento', pt: 'Combinar várias páginas digitalizadas num documento', sv: 'Kombinera flera skannade sidor till ett dokument', no: 'Kombinere flere skannede sider til ett dokument', is: 'Sameina margar skannaðar síður í eitt skjal', tr: 'Birden fazla taranmış sayfayı tek bir belgede birleştirme', ar: 'دمج عدة صفحات ممسوحة ضوئيًا في مستند واحد', fa: 'ترکیب چندین صفحه اسکن شده در یک سند', hi: 'कई स्कैन किए गए पृष्ठों को एक दस्तावेज़ में संयोजित करना', ja: '複数のスキャンページを1つの文書に結合', zh: '将多个扫描页面合并到一个文档中' },
      { pl: 'Łączenie faktur i raportów w jeden plik dla księgowości', en: 'Merging invoices and reports into one file for accounting', de: 'Zusammenführen von Rechnungen und Berichten für die Buchhaltung', es: 'Combinar facturas e informes en un solo archivo para contabilidad', fr: 'Fusionner factures et rapports en un seul fichier pour la comptabilité', it: 'Unire fatture e report in un unico file per la contabilità', pt: 'Fundir faturas e relatórios num único ficheiro para contabilidade', sv: 'Slå ihop fakturor och rapporter till en fil för redovisning', no: 'Slå sammen fakturaer og rapporter til én fil for regnskap', is: 'Sameina reikninga og skýrslur í eina skrá fyrir bókhald', tr: 'Faturaları ve raporları muhasebe için tek bir dosyada birleştirme', ar: 'دمج الفواتير والتقارير في ملف واحد للمحاسبة', fa: 'ادغام فاکتورها و گزارش‌ها در یک فایل برای حسابداری', hi: 'लेखांकन के लिए चालान और रिपोर्ट को एक फ़ाइल में मर्ज करना', ja: '請求書とレポートを会計用に1つのファイルに結合', zh: '将发票和报告合并到一个文件中用于会计' },
      { pl: 'Tworzenie jednego pliku z wielu umów lub dokumentów prawnych', en: 'Creating a single file from multiple contracts or legal documents', de: 'Erstellen einer einzigen Datei aus mehreren Verträgen oder Rechtsdokumenten', es: 'Crear un solo archivo a partir de varios contratos o documentos legales', fr: 'Créer un fichier unique à partir de plusieurs contrats ou documents juridiques', it: 'Creare un unico file da più contratti o documenti legali', pt: 'Criar um único ficheiro a partir de vários contratos ou documentos legais', sv: 'Skapa en enda fil från flera kontrakt eller juridiska dokument', no: 'Opprette én fil fra flere kontrakter eller juridiske dokumenter', is: 'Búa til eina skrá úr mörgum samningum eða lagalegum skjölum', tr: 'Birden fazla sözleşme veya yasal belgeden tek bir dosya oluşturma', ar: 'إنشاء ملف واحد من عدة عقود أو مستندات قانونية', fa: 'ایجاد یک فایل از چندین قرارداد یا اسناد حقوقی', hi: 'कई अनुबंधों या कानूनी दस्तावेज़ों से एक फ़ाइल बनाना', ja: '複数の契約書や法的文書から1つのファイルを作成', zh: '从多个合同或法律文件创建单个文件' },
    ]},
    { type: 'cta', tool: 'merge' },
  ],
  relatedTool: 'merge',
  faq: [
    { q: {
      pl: 'Ile plików mogę połączyć jednocześnie?',
      en: 'How many files can I merge at once?',
      de: 'Wie viele Dateien kann ich gleichzeitig zusammenführen?',
      es: '¿Cuántos archivos puedo combinar a la vez?',
      fr: 'Combien de fichiers puis-je fusionner à la fois ?',
      it: 'Quanti file posso unire contemporaneamente?',
      pt: 'Quantos ficheiros posso fundir de uma vez?',
      sv: 'Hur många filer kan jag slå ihop samtidigt?',
      no: 'Hvor mange filer kan jeg slå sammen samtidig?',
      is: 'Hversu margar skrár get ég sameinað í einu?',
      tr: 'Aynı anda kaç dosya birleştirebilirim?',
      ar: 'كم عدد الملفات التي يمكنني دمجها في وقت واحد؟',
      fa: 'چند فایل می‌توانم همزمان ادغام کنم؟',
      hi: 'मैं एक बार में कितनी फ़ाइलें मर्ज कर सकता हूँ?',
      ja: '一度にいくつのファイルを結合できますか？',
      zh: '一次可以合并多少个文件？',
    }, a: {
      pl: 'Nie ma ograniczenia liczby plików — możesz dodać tyle plików PDF, ile potrzebujesz. Jedyne ograniczenie to pamięć Twojej przeglądarki. W praktyce narzędzie radzi sobie z kilkunastoma plikami bez problemu.',
      en: 'There is no limit on the number of files — you can add as many PDFs as you need. The only limitation is your browser\'s memory. In practice, the tool handles a dozen files without any issues.',
      de: 'Es gibt keine Begrenzung der Dateianzahl. Die einzige Einschränkung ist der Arbeitsspeicher Ihres Browsers. In der Praxis verarbeitet das Werkzeug ein Dutzend Dateien problemlos.',
      es: 'No hay límite de archivos. La única limitación es la memoria de su navegador. En la práctica, la herramienta maneja una docena de archivos sin problemas.',
      fr: 'Il n\'y a pas de limite sur le nombre de fichiers. La seule limitation est la mémoire de votre navigateur. En pratique, l\'outil gère une douzaine de fichiers sans problème.',
      it: 'Non c\'è limite al numero di file. L\'unica limitazione è la memoria del browser. In pratica, lo strumento gestisce una dozzina di file senza problemi.',
      pt: 'Não há limite no número de ficheiros. A única limitação é a memória do seu navegador. Na prática, a ferramenta lida com uma dúzia de ficheiros sem problemas.',
      sv: 'Det finns ingen gräns för antalet filer. Den enda begränsningen är din webbläsares minne. I praktiken hanterar verktyget ett dussin filer utan problem.',
      no: 'Det er ingen grense for antall filer. Den eneste begrensningen er nettleserens minne. Verktøyet håndterer et dusin filer uten problemer.',
      is: 'Það er engin takmörk á fjölda skráa. Eina takmörkunin er minni vafrans. Í reynd höndlar tólið tugi skráa án vandræða.',
      tr: 'Dosya sayısında bir sınır yoktur. Tek sınırlama tarayıcınızın belleğidir. Pratikte araç bir düzine dosyayı sorunsuz bir şekilde işler.',
      ar: 'لا يوجد حد لعدد الملفات. القيد الوحيد هو ذاكرة المتصفح. عمليًا، تتعامل الأداة مع عشرات الملفات دون مشاكل.',
      fa: 'هیچ محدودیتی برای تعداد فایل‌ها وجود ندارد. تنها محدودیت حافظه مرورگر شماست. در عمل، ابزار ده‌ها فایل را بدون مشکل پردازش می‌کند.',
      hi: 'फ़ाइलों की संख्या की कोई सीमा नहीं है। एकमात्र सीमा आपके ब्राउज़र की मेमोरी है। व्यवहार में, उपकरण एक दर्जन फ़ाइलों को बिना किसी समस्या के संभाल लेता है।',
      ja: 'ファイル数に制限はありません。唯一の制限はブラウザのメモリです。実際には、このツールは十数個のファイルを問題なく処理できます。',
      zh: '文件数量没有限制。唯一的限制是浏览器的内存。实际上，该工具可以轻松处理十几个文件。',
    }},
    { q: {
      pl: 'Czy scalanie PDF wpływa na jakość dokumentów?',
      en: 'Does merging PDFs affect document quality?',
      de: 'Beeinträchtigt das Zusammenführen von PDFs die Dokumentqualität?',
      es: '¿La combinación de PDF afecta la calidad de los documentos?',
      fr: 'La fusion de PDF affecte-t-elle la qualité des documents ?',
      it: 'L\'unione di PDF influisce sulla qualità dei documenti?',
      pt: 'A fusão de PDF afeta a qualidade dos documentos?',
      sv: 'Påverkar ihopslagning av PDF-dokumentkvaliteten?',
      no: 'Påvirker sammenslåing av PDF dokumentkvaliteten?',
      is: 'Hefur sameining PDF áhrif á gæði skjala?',
      tr: 'PDF birleştirme belge kalitesini etkiler mi?',
      ar: 'هل يؤثر دمج PDF على جودة المستندات؟',
      fa: 'آیا ادغام PDF بر کیفیت اسناد تأثیر می‌گذارد؟',
      hi: 'क्या PDF मर्ज करने से दस्तावेज़ की गुणवत्ता प्रभावित होती है?',
      ja: 'PDFの結合は文書の品質に影響しますか？',
      zh: '合并PDF会影响文档质量吗？',
    }, a: {
      pl: 'Nie, scalanie nie zmienia zawartości plików. Każda strona pozostaje w oryginalnej jakości, a tekst i obrazy nie są modyfikowane. Narzędzie łączy pliki w jeden dokument bez ponownego kodowania stron.',
      en: 'No, merging does not change file contents. Each page remains in original quality and text and images are not modified. The tool combines files into one document without re-encoding pages.',
      de: 'Nein, die Zusammenführung ändert den Dateiinhalt nicht. Jede Seite behält die Originalqualität, Text und Bilder werden nicht verändert.',
      es: 'No, la combinación no cambia el contenido. Cada página conserva su calidad original y el texto y las imágenes no se modifican.',
      fr: 'Non, la fusion ne modifie pas le contenu. Chaque page conserve sa qualité d\'origine et le texte et les images ne sont pas modifiés.',
      it: 'No, l\'unione non modifica il contenuto. Ogni pagina rimane in qualità originale e testo e immagini non vengono modificati.',
      pt: 'Não, a fusão não altera o conteúdo. Cada página mantém a qualidade original e o texto e imagens não são modificados.',
      sv: 'Nej, ihopslagning ändrar inte filinnehållet. Varje sida behåller originalkvaliteten och text och bilder ändras inte.',
      no: 'Nei, sammenslåing endrer ikke filinnholdet. Hver side forblir i original kvalitet og tekst og bilder endres ikke.',
      is: 'Nei, sameining breytir ekki innihaldi skráa. Hver síða helst í upprunalegum gæðum og texti og myndir eru ekki breytt.',
      tr: 'Hayır, birleştirme dosya içeriğini değiştirmez. Her sayfa orijinal kalitesinde kalır ve metin ile görüntüler değiştirilmez.',
      ar: 'لا، الدمج لا يغير محتويات الملف. كل صفحة تبقى بجودتها الأصلية والنصوص والصور لا يتم تعديلها.',
      fa: 'خیر، ادغام محتوای فایل را تغییر نمی‌دهد. هر صفحه در کیفیت اصلی باقی می‌ماند و متن و تصاویر تغییر نمی‌کنند.',
      hi: 'नहीं, मर्ज करने से फ़ाइल सामग्री नहीं बदलती है। प्रत्येक पृष्ठ मूल गुणवत्ता में रहता है और टेक्स्ट और छवियां संशोधित नहीं होती हैं।',
      ja: 'いいえ、結合はファイル内容を変更しません。各ページは元の品質を維持し、テキストや画像は変更されません。',
      zh: '不会。合并不会改变文件内容。每个页面保持原始质量，文本和图像不会被修改。',
    }},
  ],
  canonicalOverride: undefined,
  publishedAt: '2025-06-15',
  updatedAt: '2025-07-02',
};

export default article;
