'use client';
import { usePathname } from 'next/navigation';
import { useHydrationSafeLocale } from '@/lib/locale-context';
import { t, type Locale } from '@/lib/i18n';
import { keyBySlug } from '@/lib/tools';

function tr(texts: Record<string, string>, locale: string): string {
  return texts[locale] || texts.en || '';
}

const L: Record<string, Record<string, string>> = {
  // --- Upload steps ---
  uploadPdf: {
    pl: 'Przeciągnij plik PDF', en: 'Upload the PDF file',
    de: 'PDF-Datei hochladen', es: 'Suba el archivo PDF',
    fr: 'Téléchargez le fichier PDF', it: 'Carica il file PDF',
    pt: 'Carregue o arquivo PDF', is: 'Hladdu upp PDF skránni',
    tr: 'PDF dosyasını yükleyin', sv: 'Ladda upp PDF-filen',
    no: 'Last opp PDF-filen', ja: 'PDFファイルをアップロード',
    hi: 'PDF फ़ाइल अपलोड करें', ar: 'قم بتحميل ملف PDF',
    fa: 'فایل PDF را بارگذاری کنید', zh: '上传PDF文件',
  },
  uploadPdfCompress: {
    pl: 'Przeciągnij plik PDF do kompresji',
    en: 'Upload the PDF file to compress',
    de: 'Laden Sie die zu komprimierende PDF-Datei hoch',
    es: 'Suba el archivo PDF para comprimir',
    fr: 'Téléchargez le fichier PDF à compresser',
    it: 'Carica il file PDF da comprimere',
    pt: 'Carregue o arquivo PDF para comprimir',
    is: 'Hladdu upp PDF skránni til að þjappa',
    tr: 'Sıkıştırmak için PDF dosyasını yükleyin',
    sv: 'Ladda upp PDF-filen för komprimering',
    no: 'Last opp PDF-filen for komprimering',
    ja: '圧縮するPDFファイルをアップロード',
    hi: 'संपीड़ित करने के लिए PDF फ़ाइल अपलोड करें',
    ar: 'قم بتحميل ملف PDF لضغطه',
    fa: 'فایل PDF را برای فشرده‌سازی بارگذاری کنید',
    zh: '上传要压缩的PDF文件',
  },
  uploadPdfSplit: {
    pl: 'Przeciągnij plik PDF do podziału',
    en: 'Upload the PDF file you want to split',
    de: 'Laden Sie die zu teilende PDF-Datei hoch',
    es: 'Suba el archivo PDF que desea dividir',
    fr: 'Téléchargez le fichier PDF à diviser',
    it: 'Carica il file PDF da dividere',
    pt: 'Carregue o arquivo PDF para dividir',
    is: 'Hladdu upp PDF skránni til að skipta',
    tr: 'Bölünecek PDF dosyasını yükleyin',
    sv: 'Ladda upp den PDF-fil du vill dela upp',
    no: 'Last opp PDF-filen du vil dele',
    ja: '分割するPDFファイルをアップロード',
    hi: 'विभाजित करने के लिए PDF फ़ाइल अपलोड करें',
    ar: 'قم بتحميل ملف PDF الذي تريد تقسيمه',
    fa: 'فایل PDF مورد نظر برای تقسیم را بارگذاری کنید',
    zh: '上传要拆分的PDF文件',
  },
  uploadPdfConvert: {
    pl: 'Przeciągnij plik PDF do konwersji',
    en: 'Upload the PDF file to convert',
    de: 'Laden Sie die zu konvertierende PDF-Datei hoch',
    es: 'Suba el archivo PDF para convertir',
    fr: 'Téléchargez le fichier PDF à convertir',
    it: 'Carica il file PDF da convertire',
    pt: 'Carregue o arquivo PDF para converter',
    is: 'Hladdu upp PDF skránni til að breyta',
    tr: 'Dönüştürmek için PDF dosyasını yükleyin',
    sv: 'Ladda upp PDF-filen för konvertering',
    no: 'Last opp PDF-filen for konvertering',
    ja: '変換するPDFファイルをアップロード',
    hi: 'रूपांतरित करने के लिए PDF फ़ाइल अपलोड करें',
    ar: 'قم بتحميل ملف PDF للتحويل',
    fa: 'فایل PDF را برای تبدیل بارگذاری کنید',
    zh: '上传要转换的PDF文件',
  },
  uploadWord: {
    pl: 'Przeciągnij dokument Word',
    en: 'Upload the Word document',
    de: 'Laden Sie das Word-Dokument hoch',
    es: 'Suba el documento de Word',
    fr: 'Téléchargez le document Word',
    it: 'Carica il documento Word',
    pt: 'Carregue o documento do Word',
    is: 'Hladdu upp Word skjalinu',
    tr: 'Word belgesini yükleyin',
    sv: 'Ladda upp Word-dokumentet',
    no: 'Last opp Word-dokumentet',
    ja: 'Word文書をアップロード',
    hi: 'Word दस्तावेज़ अपलोड करें',
    ar: 'قم بتحميل مستند Word',
    fa: 'سند Word را بارگذاری کنید',
    zh: '上传Word文档',
  },
  uploadJpg: {
    pl: 'Przeciągnij obrazy JPG',
    en: 'Upload JPG images by dragging and dropping',
    de: 'Laden Sie JPG-Bilder per Drag & Drop hoch',
    es: 'Suba imágenes JPG arrastrando y soltando',
    fr: 'Téléchargez des images JPG par glisser-déposer',
    it: 'Carica immagini JPG trascinandole',
    pt: 'Carregue imagens JPG arrastando e soltando',
    is: 'Hladdu upp JPG myndum með því að draga og sleppa',
    tr: 'JPG görsellerini sürükleyip bırakarak yükleyin',
    sv: 'Ladda upp JPG-bilder genom att dra och släppa',
    no: 'Last opp JPG-bilder ved å dra og slippe',
    ja: 'JPG画像をドラッグ＆ドロップでアップロード',
    hi: 'JPG इमेज को खींचकर और छोड़कर अपलोड करें',
    ar: 'قم بتحميل صور JPG عن طريق السحب والإفلات',
    fa: 'تصاویر JPG را با کشیدن و رها کردن بارگذاری کنید',
    zh: '通过拖放上传JPG图片',
  },
  uploadExcel: {
    pl: 'Przeciągnij plik Excel',
    en: 'Upload the Excel file',
    de: 'Laden Sie die Excel-Datei hoch',
    es: 'Suba el archivo de Excel',
    fr: 'Téléchargez le fichier Excel',
    it: 'Carica il file Excel',
    pt: 'Carregue o arquivo Excel',
    is: 'Hladdu upp Excel skránni',
    tr: 'Excel dosyasını yükleyin',
    sv: 'Ladda upp Excel-filen',
    no: 'Last opp Excel-filen',
    ja: 'Excelファイルをアップロード',
    hi: 'Excel फ़ाइल अपलोड करें',
    ar: 'قم بتحميل ملف Excel',
    fa: 'فایل Excel را بارگذاری کنید',
    zh: '上传Excel文件',
  },
  uploadOdt: {
    pl: 'Przeciągnij dokument OpenOffice',
    en: 'Upload an OpenOffice document',
    de: 'Laden Sie ein OpenOffice-Dokument hoch',
    es: 'Suba un documento de OpenOffice',
    fr: 'Téléchargez un document OpenOffice',
    it: 'Carica un documento OpenOffice',
    pt: 'Carregue um documento do OpenOffice',
    is: 'Hladdu upp OpenOffice skjali',
    tr: 'OpenOffice belgesini yükleyin',
    sv: 'Ladda upp ett OpenOffice-dokument',
    no: 'Last opp et OpenOffice-dokument',
    ja: 'OpenOffice文書をアップロード',
    hi: 'OpenOffice दस्तावेज़ अपलोड करें',
    ar: 'قم بتحميل مستند OpenOffice',
    fa: 'سند OpenOffice را بارگذاری کنید',
    zh: '上传OpenOffice文档',
  },
  uploadHtml: {
    pl: 'Wklej kod HTML lub prześlij plik HTML',
    en: 'Paste HTML code or upload an HTML file',
    de: 'HTML-Code einfügen oder HTML-Datei hochladen',
    es: 'Pegue código HTML o suba un archivo HTML',
    fr: 'Collez du code HTML ou téléchargez un fichier HTML',
    it: 'Incolla codice HTML o carica un file HTML',
    pt: 'Cole o código HTML ou carregue um arquivo HTML',
    is: 'Límdu HTML kóða eða hladdu upp HTML skrá',
    tr: 'HTML kodu yapıştırın veya bir HTML dosyası yükleyin',
    sv: 'Klistra in HTML-kod eller ladda upp en HTML-fil',
    no: 'Lim inn HTML-kode eller last opp en HTML-fil',
    ja: 'HTMLコードを貼り付けるかHTMLファイルをアップロード',
    hi: 'HTML कोड पेस्ट करें या HTML फ़ाइल अपलोड करें',
    ar: 'ألصق كود HTML أو قم بتحميل ملف HTML',
    fa: 'کد HTML را جای‌گذاری کنید یا فایل HTML بارگذاری کنید',
    zh: '粘贴HTML代码或上传HTML文件',
  },
  enterUrl: {
    pl: 'Wprowadź adres URL strony',
    en: 'Enter the website URL',
    de: 'Geben Sie die Website-URL ein',
    es: 'Ingrese la URL del sitio web',
    fr: 'Entrez l\'URL du site web',
    it: 'Inserisci l\'URL del sito web',
    pt: 'Insira a URL do site',
    is: 'Sláðu inn vefslóðina',
    tr: 'Web sitesi URL\'sini girin',
    sv: 'Ange webbplatsens URL',
    no: 'Skriv inn nettstedets URL',
    ja: 'ウェブサイトのURLを入力',
    hi: 'वेबसाइट URL दर्ज करें',
    ar: 'أدخل عنوان URL للموقع',
    fa: 'URL وب‌سایت را وارد کنید',
    zh: '输入网站URL',
  },
  uploadTwoPdfs: {
    pl: 'Przeciągnij dwa pliki PDF do porównania',
    en: 'Upload two PDF files to compare',
    de: 'Laden Sie zwei PDF-Dateien zum Vergleich hoch',
    es: 'Suba dos archivos PDF para comparar',
    fr: 'Téléchargez deux fichiers PDF à comparer',
    it: 'Carica due file PDF da confrontare',
    pt: 'Carregue dois arquivos PDF para comparar',
    is: 'Hladdu upp tveimur PDF skrám til að bera saman',
    tr: 'Karşılaştırmak için iki PDF dosyası yükleyin',
    sv: 'Ladda upp två PDF-filer för att jämföra',
    no: 'Last opp to PDF-filer for å sammenligne',
    ja: '比較する2つのPDFファイルをアップロード',
    hi: 'तुलना करने के लिए दो PDF फ़ाइलें अपलोड करें',
    ar: 'قم بتحميل ملفي PDF للمقارنة',
    fa: 'دو فایل PDF برای مقایسه بارگذاری کنید',
    zh: '上传两个PDF文件进行比较',
  },
  uploadPdfProtect: {
    pl: 'Przeciągnij plik PDF do zabezpieczenia',
    en: 'Upload the PDF file to protect',
    de: 'Laden Sie die zu schützende PDF-Datei hoch',
    es: 'Suba el archivo PDF para proteger',
    fr: 'Téléchargez le fichier PDF à protéger',
    it: 'Carica il file PDF da proteggere',
    pt: 'Carregue o arquivo PDF para proteger',
    is: 'Hladdu upp PDF skránni til að vernda',
    tr: 'Korumak için PDF dosyasını yükleyin',
    sv: 'Ladda upp PDF-filen för att skydda',
    no: 'Last opp PDF-filen for å beskytte',
    ja: '保護するPDFファイルをアップロード',
    hi: 'सुरक्षित करने के लिए PDF फ़ाइल अपलोड करें',
    ar: 'قم بتحميل ملف PDF لحمايته',
    fa: 'فایل PDF را برای محافظت بارگذاری کنید',
    zh: '上传要保护的PDF文件',
  },
  uploadPdfSign: {
    pl: 'Przeciągnij plik PDF do podpisania',
    en: 'Upload the PDF file to sign',
    de: 'Laden Sie die zu signierende PDF-Datei hoch',
    es: 'Suba el archivo PDF para firmar',
    fr: 'Téléchargez le fichier PDF à signer',
    it: 'Carica il file PDF da firmare',
    pt: 'Carregue o arquivo PDF para assinar',
    is: 'Hladdu upp PDF skránni til að undirrita',
    tr: 'İmzalamak için PDF dosyasını yükleyin',
    sv: 'Ladda upp PDF-filen för att signera',
    no: 'Last opp PDF-filen for å signere',
    ja: '署名するPDFファイルをアップロード',
    hi: 'हस्ताक्षर करने के लिए PDF फ़ाइल अपलोड करें',
    ar: 'قم بتحميل ملف PDF للتوقيع',
    fa: 'فایل PDF را برای امضا بارگذاری کنید',
    zh: '上传要签名的PDF文件',
  },
  uploadPdfEdit: {
    pl: 'Przeciągnij plik PDF do edycji',
    en: 'Upload the PDF file to edit',
    de: 'Laden Sie die zu bearbeitende PDF-Datei hoch',
    es: 'Suba el archivo PDF para editar',
    fr: 'Téléchargez le fichier PDF à modifier',
    it: 'Carica il file PDF da modificare',
    pt: 'Carregue o arquivo PDF para editar',
    is: 'Hladdu upp PDF skránni til að breyta',
    tr: 'Düzenlemek için PDF dosyasını yükleyin',
    sv: 'Ladda upp PDF-filen för att redigera',
    no: 'Last opp PDF-filen for å redigere',
    ja: '編集するPDFファイルをアップロード',
    hi: 'संपादित करने के लिए PDF फ़ाइल अपलोड करें',
    ar: 'قم بتحميل ملف PDF للتعديل',
    fa: 'فایل PDF را برای ویرایش بارگذاری کنید',
    zh: '上传要编辑的PDF文件',
  },
  uploadScanned: {
    pl: 'Przeciągnij zeskanowany dokument PDF',
    en: 'Upload a scanned PDF document',
    de: 'Laden Sie ein gescanntes PDF-Dokument hoch',
    es: 'Suba un documento PDF escaneado',
    fr: 'Téléchargez un document PDF numérisé',
    it: 'Carica un documento PDF scansionato',
    pt: 'Carregue um documento PDF digitalizado',
    is: 'Hladdu upp skönnuðu PDF skjali',
    tr: 'Taranmış bir PDF belgesi yükleyin',
    sv: 'Ladda upp ett skannat PDF-dokument',
    no: 'Last opp et skannet PDF-dokument',
    ja: 'スキャンしたPDF文書をアップロード',
    hi: 'स्कैन किया गया PDF दस्तावेज़ अपलोड करें',
    ar: 'قم بتحميل مستند PDF ممسوح ضوئياً',
    fa: 'یک سند PDF اسکن‌شده بارگذاری کنید',
    zh: '上传扫描的PDF文档',
  },
  uploadFormPdf: {
    pl: 'Przeciągnij plik PDF z formularzem',
    en: 'Upload the PDF with a form',
    de: 'Laden Sie das PDF mit einem Formular hoch',
    es: 'Suba el PDF con un formulario',
    fr: 'Téléchargez le PDF avec un formulaire',
    it: 'Carica il PDF con un modulo',
    pt: 'Carregue o PDF com um formulário',
    is: 'Hladdu upp PDF með eyðublaði',
    tr: 'Form içeren PDF\'i yükleyin',
    sv: 'Ladda upp PDF-filen med ett formulär',
    no: 'Last opp PDF-filen med et skjema',
    ja: 'フォーム付きPDFをアップロード',
    hi: 'फ़ॉर्म वाली PDF फ़ाइल अपलोड करें',
    ar: 'قم بتحميل PDF مع نموذج',
    fa: 'PDF دارای فرم را بارگذاری کنید',
    zh: '上传包含表单的PDF',
  },
  uploadAnnotatedPdf: {
    pl: 'Przeciągnij plik PDF z adnotacjami',
    en: 'Upload the PDF file with annotations',
    de: 'Laden Sie die PDF-Datei mit Anmerkungen hoch',
    es: 'Suba el archivo PDF con anotaciones',
    fr: 'Téléchargez le fichier PDF avec annotations',
    it: 'Carica il file PDF con annotazioni',
    pt: 'Carregue o arquivo PDF com anotações',
    is: 'Hladdu upp PDF skránni með skýringum',
    tr: 'Açıklamalı PDF dosyasını yükleyin',
    sv: 'Ladda upp PDF-filen med anteckningar',
    no: 'Last opp PDF-filen med merknader',
    ja: '注釈付きPDFファイルをアップロード',
    hi: 'एनोटेशन वाली PDF फ़ाइल अपलोड करें',
    ar: 'قم بتحميل ملف PDF مع التعليقات',
    fa: 'فایل PDF با حاشیه‌نویسی را بارگذاری کنید',
    zh: '上传带注释的PDF文件',
  },
  uploadPasswordPdf: {
    pl: 'Przeciągnij plik PDF chroniony hasłem',
    en: 'Upload the password-protected PDF',
    de: 'Laden Sie die passwortgeschützte PDF-Datei hoch',
    es: 'Suba el archivo PDF protegido con contraseña',
    fr: 'Téléchargez le fichier PDF protégé par mot de passe',
    it: 'Carica il file PDF protetto da password',
    pt: 'Carregue o arquivo PDF protegido por senha',
    is: 'Hladdu upp PDF skránni með lykilorði',
    tr: 'Parola korumalı PDF dosyasını yükleyin',
    sv: 'Ladda upp den lösenordsskyddade PDF-filen',
    no: 'Last opp den passordbeskyttede PDF-filen',
    ja: 'パスワード保護されたPDFファイルをアップロード',
    hi: 'पासवर्ड-सुरक्षित PDF फ़ाइल अपलोड करें',
    ar: 'قم بتحميل ملف PDF المحمي بكلمة مرور',
    fa: 'فایل PDF محافظت‌شده با رمز عبور را بارگذاری کنید',
    zh: '上传受密码保护的PDF文件',
  },
  uploadTabularPdf: {
    pl: 'Przeciągnij plik PDF z danymi tabelarycznymi',
    en: 'Upload the PDF file with tabular data',
    de: 'Laden Sie die PDF-Datei mit Tabellendaten hoch',
    es: 'Suba el archivo PDF con datos tabulares',
    fr: 'Téléchargez le fichier PDF avec des données tabulaires',
    it: 'Carica il file PDF con dati tabellari',
    pt: 'Carregue o arquivo PDF com dados tabulares',
    is: 'Hladdu upp PDF skránni með töflugögnum',
    tr: 'Tablo verileri içeren PDF dosyasını yükleyin',
    sv: 'Ladda upp PDF-filen med tabelldata',
    no: 'Last opp PDF-filen med tabelldata',
    ja: '表データを含むPDFファイルをアップロード',
    hi: 'सारणीबद्ध डेटा वाली PDF फ़ाइल अपलोड करें',
    ar: 'قم بتحميل ملف PDF مع بيانات جدولية',
    fa: 'فایل PDF با داده‌های جدولی را بارگذاری کنید',
    zh: '上传包含表格数据的PDF文件',
  },

  // --- Arrange steps ---
  arrangeOrder: {
    pl: 'Ustaw pliki w żądanej kolejności',
    en: 'Arrange files in the desired order',
    de: 'Ordnen Sie die Dateien in der gewünschten Reihenfolge an',
    es: 'Organice los archivos en el orden deseado',
    fr: 'Organisez les fichiers dans l\'ordre souhaité',
    it: 'Disponi i file nell\'ordine desiderato',
    pt: 'Organize os arquivos na ordem desejada',
    is: 'Raðaðu skrám í æskilegri röð',
    tr: 'Dosyaları istenen sıraya göre düzenleyin',
    sv: 'Ordna filerna i önskad ordning',
    no: 'Ordne filene i ønsket rekkefølge',
    ja: 'ファイルを希望の順序に並べ替え',
    hi: 'फ़ाइलों को वांछित क्रम में व्यवस्थित करें',
    ar: 'رتب الملفات بالترتيب المطلوب',
    fa: 'فایل‌ها را به ترتیب دلخواه مرتب کنید',
    zh: '按所需顺序排列文件',
  },
  arrangeImages: {
    pl: 'Ustaw obrazy w żądanej kolejności',
    en: 'Arrange images in the desired order',
    de: 'Ordnen Sie die Bilder in der gewünschten Reihenfolge',
    es: 'Organice las imágenes en el orden deseado',
    fr: 'Organisez les images dans l\'ordre souhaité',
    it: 'Disponi le immagini nell\'ordine desiderato',
    pt: 'Organize as imagens na ordem desejada',
    is: 'Raðaðu myndum í æskilegri röð',
    tr: 'Görselleri istenen sıraya göre düzenleyin',
    sv: 'Ordna bilderna i önskad ordning',
    no: 'Ordne bildene i ønsket rekkefølge',
    ja: '画像を希望の順序に並べ替え',
    hi: 'इमेज को वांछित क्रम में व्यवस्थित करें',
    ar: 'رتب الصور بالترتيب المطلوب',
    fa: 'تصاویر را به ترتیب دلخواه مرتب کنید',
    zh: '按所需顺序排列图片',
  },

  // --- Selection / configuration steps ---
  selectSplitMode: {
    pl: 'Wybierz tryb podziału: każda strona osobno lub zakresy',
    en: 'Choose split mode: every page separately or custom ranges',
    de: 'Wählen Sie den Teilungsmodus: jede Seite einzeln oder benutzerdefinierte Bereiche',
    es: 'Elija el modo de división: cada página por separado o rangos personalizados',
    fr: 'Choisissez le mode de division : chaque page séparément ou plages personnalisées',
    it: 'Scegli la modalità di divisione: ogni pagina separatamente o intervalli personalizzati',
    pt: 'Escolha o modo de divisão: cada página separadamente ou intervalos personalizados',
    is: 'Veldu skiptimáta: hver síða fyrir sig eða sérsniðin bil',
    tr: 'Bölme modunu seçin: her sayfa ayrı ayrı veya özel aralıklar',
    sv: 'Välj delningsläge: varje sida separat eller anpassade intervall',
    no: 'Velg delingsmodus: hver side separat eller egendefinerte områder',
    ja: '分割モードを選択：ページごとまたはカスタム範囲',
    hi: 'विभाजन मोड चुनें: प्रत्येक पृष्ठ अलग या कस्टम रेंज',
    ar: 'اختر وضع التقسيم: كل صفحة على حدة أو نطاقات مخصصة',
    fa: 'حالت تقسیم را انتخاب کنید: هر صفحه به صورت جداگانه یا محدوده‌های سفارشی',
    zh: '选择拆分模式：每页单独拆分或自定义范围',
  },
  selectCompression: {
    pl: 'Wybierz poziom kompresji: niski, zalecany lub ekstremalny',
    en: 'Select compression level: low, recommended, or extreme',
    de: 'Wählen Sie die Komprimierungsstufe: niedrig, empfohlen oder extrem',
    es: 'Seleccione el nivel de compresión: bajo, recomendado o extremo',
    fr: 'Sélectionnez le niveau de compression : faible, recommandé ou extrême',
    it: 'Seleziona il livello di compressione: basso, consigliato o estremo',
    pt: 'Selecione o nível de compressão: baixo, recomendado ou extremo',
    is: 'Veldu þjöppunarstig: lágt, mælt eða öfgafullt',
    tr: 'Sıkıştırma seviyesini seçin: düşük, önerilen veya aşırı',
    sv: 'Välj komprimeringsnivå: låg, rekommenderad eller extrem',
    no: 'Velg komprimeringsnivå: lav, anbefalt eller ekstrem',
    ja: '圧縮レベルを選択：低、推奨、または極度',
    hi: 'संपीड़न स्तर चुनें: निम्न, अनुशंसित या अत्यधिक',
    ar: 'اختر مستوى الضغط: منخفض، موصى به أو شديد',
    fa: 'سطح فشرده‌سازی را انتخاب کنید: کم، توصیه‌شده یا شدید',
    zh: '选择压缩级别：低、推荐或极限',
  },
  selectRotation: {
    pl: 'Wybierz kąt obrotu: 90, 180 lub 270 stopni',
    en: 'Select rotation angle: 90, 180, or 270 degrees',
    de: 'Wählen Sie den Drehwinkel: 90, 180 oder 270 Grad',
    es: 'Seleccione el ángulo de rotación: 90, 180 o 270 grados',
    fr: 'Sélectionnez l\'angle de rotation : 90, 180 ou 270 degrés',
    it: 'Seleziona l\'angolo di rotazione: 90, 180 o 270 gradi',
    pt: 'Selecione o ângulo de rotação: 90, 180 ou 270 graus',
    is: 'Veldu snúningshorn: 90, 180 eða 270 gráður',
    tr: 'Döndürme açısını seçin: 90, 180 veya 270 derece',
    sv: 'Välj rotationsvinkel: 90, 180 eller 270 grader',
    no: 'Velg rotasjonsvinkel: 90, 180 eller 270 grader',
    ja: '回転角度を選択：90度、180度、270度',
    hi: 'घूर्णन कोण चुनें: 90, 180 या 270 डिग्री',
    ar: 'اختر زاوية التدوير: 90 أو 180 أو 270 درجة',
    fa: 'زاویه چرخش را انتخاب کنید: 90، 180 یا 270 درجه',
    zh: '选择旋转角度：90度、180度或270度',
  },
  selectImageFormat: {
    pl: 'Wybierz format obrazu (PNG, JPEG, WebP), skalę i jakość',
    en: 'Select image format (PNG, JPEG, WebP), scale and quality',
    de: 'Wählen Sie Bildformat (PNG, JPEG, WebP), Skalierung und Qualität',
    es: 'Seleccione el formato de imagen (PNG, JPEG, WebP), escala y calidad',
    fr: 'Sélectionnez le format d\'image (PNG, JPEG, WebP), l\'échelle et la qualité',
    it: 'Seleziona formato immagine (PNG, JPEG, WebP), scala e qualità',
    pt: 'Selecione o formato de imagem (PNG, JPEG, WebP), escala e qualidade',
    is: 'Veldu myndasnið (PNG, JPEG, WebP), skala og gæði',
    tr: 'Görsel formatını (PNG, JPEG, WebP), ölçeği ve kaliteyi seçin',
    sv: 'Välj bildformat (PNG, JPEG, WebP), skala och kvalitet',
    no: 'Velg bildeformat (PNG, JPEG, WebP), skala og kvalitet',
    ja: '画像形式（PNG、JPEG、WebP）、スケール、品質を選択',
    hi: 'इमेज फ़ॉर्मैट (PNG, JPEG, WebP), स्केल और गुणवत्ता चुनें',
    ar: 'اختر تنسيق الصورة (PNG، JPEG، WebP) والمقياس والجودة',
    fa: 'فرمت تصویر (PNG، JPEG، WebP)، مقیاس و کیفیت را انتخاب کنید',
    zh: '选择图片格式（PNG、JPEG、WebP）、缩放和质量',
  },
  selectLanguage: {
    pl: 'Wybierz język dokumentu',
    en: 'Select the document language',
    de: 'Wählen Sie die Dokumentsprache',
    es: 'Seleccione el idioma del documento',
    fr: 'Sélectionnez la langue du document',
    it: 'Seleziona la lingua del documento',
    pt: 'Selecione o idioma do documento',
    is: 'Veldu skjalstungumál',
    tr: 'Belge dilini seçin',
    sv: 'Välj dokumentets språk',
    no: 'Velg dokumentspråk',
    ja: '文書の言語を選択',
    hi: 'दस्तावेज़ की भाषा चुनें',
    ar: 'اختر لغة المستند',
    fa: 'زبان سند را انتخاب کنید',
    zh: '选择文档语言',
  },
  setMargins: {
    pl: 'Ustaw marginesy: góra, dół, lewo, prawo',
    en: 'Set margin values for top, bottom, left, and right',
    de: 'Legen Sie die Randwerte für oben, unten, links und rechts fest',
    es: 'Establezca los márgenes: superior, inferior, izquierdo y derecho',
    fr: 'Définissez les marges : haut, bas, gauche et droite',
    it: 'Imposta i margini: superiore, inferiore, sinistro e destro',
    pt: 'Defina as margens: superior, inferior, esquerda e direita',
    is: 'Stilltu spássíur: efst, neðst, vinstri og hægri',
    tr: 'Kenar boşluklarını ayarlayın: üst, alt, sol ve sağ',
    sv: 'Ställ in marginalvärden för topp, botten, vänster och höger',
    no: 'Angi margverdier for topp, bunn, venstre og høyre',
    ja: 'マージンを設定：上、下、左、右',
    hi: 'मार्जिन सेट करें: ऊपर, नीचे, बाएँ, दाएँ',
    ar: 'اضبط قيم الهوامش: الأعلى والأسفل واليسار واليمين',
    fa: 'مقادیر حاشیه را تنظیم کنید: بالا، پایین، چپ و راست',
    zh: '设置页边距：上、下、左、右',
  },
  adjustPageSize: {
    pl: 'Dostosuj rozmiar i orientację strony',
    en: 'Adjust page size and orientation',
    de: 'Passen Sie Seitengröße und Ausrichtung an',
    es: 'Ajuste el tamaño y la orientación de la página',
    fr: 'Ajustez la taille et l\'orientation de la page',
    it: 'Regola dimensioni e orientamento della pagina',
    pt: 'Ajuste o tamanho e a orientação da página',
    is: 'Stilltu síðustærð og stefnu',
    tr: 'Sayfa boyutunu ve yönünü ayarlayın',
    sv: 'Justera sidstorlek och orientering',
    no: 'Juster sidestørrelse og retning',
    ja: 'ページサイズと向きを調整',
    hi: 'पृष्ठ आकार और अभिविन्यास समायोजित करें',
    ar: 'ضبط حجم الصفحة واتجاهها',
    fa: 'اندازه و جهت صفحه را تنظیم کنید',
    zh: '调整页面大小和方向',
  },
  customizePdfOptions: {
    pl: 'Dostosuj opcje PDF',
    en: 'Customize PDF options if needed',
    de: 'Passen Sie PDF-Optionen bei Bedarf an',
    es: 'Personalice las opciones de PDF si es necesario',
    fr: 'Personnalisez les options PDF si nécessaire',
    it: 'Personalizza le opzioni PDF se necessario',
    pt: 'Personalize as opções de PDF se necessário',
    is: 'Sérsníddu PDF valkosti ef þörf krefur',
    tr: 'Gerekirse PDF seçeneklerini özelleştirin',
    sv: 'Anpassa PDF-alternativ om det behövs',
    no: 'Tilpass PDF-alternativer om nødvendig',
    ja: '必要に応じてPDFオプションをカスタマイズ',
    hi: 'आवश्यकता हो तो PDF विकल्पों को कस्टमाइज़ करें',
    ar: 'خصص خيارات PDF إذا لزم الأمر',
    fa: 'در صورت نیاز گزینه‌های PDF را سفارشی کنید',
    zh: '根据需要自定义PDF选项',
  },
  editMetadata: {
    pl: 'Edytuj tytuł, autora, temat i słowa kluczowe',
    en: 'Edit title, author, subject, and keywords',
    de: 'Bearbeiten Sie Titel, Autor, Betreff und Schlüsselwörter',
    es: 'Edite el título, autor, asunto y palabras clave',
    fr: 'Modifiez le titre, l\'auteur, le sujet et les mots-clés',
    it: 'Modifica titolo, autore, oggetto e parole chiave',
    pt: 'Edite título, autor, assunto e palavras-chave',
    is: 'Breyttu titli, höfundi, efni og leitarorðum',
    tr: 'Başlık, yazar, konu ve anahtar kelimeleri düzenleyin',
    sv: 'Redigera titel, författare, ämne och nyckelord',
    no: 'Rediger tittel, forfatter, emne og nøkkelord',
    ja: 'タイトル、作成者、件名、キーワードを編集',
    hi: 'शीर्षक, लेखक, विषय और कीवर्ड संपादित करें',
    ar: 'عدّل العنوان والمؤلف والموضوع والكلمات المفتاحية',
    fa: 'عنوان، نویسنده، موضوع و کلمات کلیدی را ویرایش کنید',
    zh: '编辑标题、作者、主题和关键词',
  },
  customizeWatermark: {
    pl: 'Wprowadź tekst znaku wodnego i dostosuj wygląd',
    en: 'Enter watermark text and customize appearance',
    de: 'Geben Sie den Wasserzeichen-Text ein und passen Sie das Erscheinungsbild an',
    es: 'Ingrese el texto de la marca de agua y personalice la apariencia',
    fr: 'Entrez le texte du filigrane et personnalisez l\'apparence',
    it: 'Inserisci il testo della filigrana e personalizza l\'aspetto',
    pt: 'Insira o texto da marca d\'água e personalize a aparência',
    is: 'Sláðu inn vatnsmerkjatexta og sérsníddu útlit',
    tr: 'Filigran metnini girin ve görünümü özelleştirin',
    sv: 'Ange vattenstämpeltext och anpassa utseendet',
    no: 'Skriv inn vannmerketekst og tilpass utseendet',
    ja: '透かしテキストを入力し外観をカスタマイズ',
    hi: 'वॉटरमार्क टेक्स्ट दर्ज करें और रूप-रंग कस्टमाइज़ करें',
    ar: 'أدخل نص العلامة المائية وخصص المظهر',
    fa: 'متن واترمارک را وارد کنید و ظاهر را سفارشی کنید',
    zh: '输入水印文本并自定义外观',
  },

  // --- Click action steps ---
  clickMerge: {
    pl: 'Kliknij przycisk łączenia', en: 'Click the merge button',
    de: 'Klicken Sie auf die Schaltfläche Zusammenführen',
    es: 'Haga clic en el botón Unir',
    fr: 'Cliquez sur le bouton Fusionner',
    it: 'Clicca sul pulsante Unisci',
    pt: 'Clique no botão Unir',
    is: 'Smelltu á sameina hnappinn',
    tr: 'Birleştir düğmesine tıklayın',
    sv: 'Klicka på knappen Slå ihop',
    no: 'Klikk på slå sammen-knappen',
    ja: '結合ボタンをクリック',
    hi: 'मर्ज बटन पर क्लिक करें',
    ar: 'انقر على زر الدمج',
    fa: 'روی دکمه ادغام کلیک کنید',
    zh: '点击合并按钮',
  },
  clickSplit: {
    pl: 'Kliknij przycisk podziału', en: 'Click the split button',
    de: 'Klicken Sie auf die Schaltfläche Teilen',
    es: 'Haga clic en el botón Dividir',
    fr: 'Cliquez sur le bouton Diviser',
    it: 'Clicca sul pulsante Dividi',
    pt: 'Clique no botão Dividir',
    is: 'Smelltu á skipta hnappinn',
    tr: 'Böl düğmesine tıklayın',
    sv: 'Klicka på knappen Dela upp',
    no: 'Klikk på del-knappen',
    ja: '分割ボタンをクリック',
    hi: 'विभाजित बटन पर क्लिक करें',
    ar: 'انقر على زر التقسيم',
    fa: 'روی دکمه تقسیم کلیک کنید',
    zh: '点击拆分按钮',
  },
  clickCompress: {
    pl: 'Kliknij przycisk kompresji', en: 'Click the compress button',
    de: 'Klicken Sie auf die Schaltfläche Komprimieren',
    es: 'Haga clic en el botón Comprimir',
    fr: 'Cliquez sur le bouton Compresser',
    it: 'Clicca sul pulsante Comprimi',
    pt: 'Clique no botão Comprimir',
    is: 'Smelltu á þjappa hnappinn',
    tr: 'Sıkıştır düğmesine tıklayın',
    sv: 'Klicka på knappen Komprimera',
    no: 'Klikk på komprimer-knappen',
    ja: '圧縮ボタンをクリック',
    hi: 'संपीड़ित बटन पर क्लिक करें',
    ar: 'انقر على زر الضغط',
    fa: 'روی دکمه فشرده‌سازی کلیک کنید',
    zh: '点击压缩按钮',
  },
  clickConvert: {
    pl: 'Kliknij przycisk konwersji', en: 'Click the convert button',
    de: 'Klicken Sie auf die Schaltfläche Konvertieren',
    es: 'Haga clic en el botón Convertir',
    fr: 'Cliquez sur le bouton Convertir',
    it: 'Clicca sul pulsante Converti',
    pt: 'Clique no botão Converter',
    is: 'Smelltu á breyta hnappinn',
    tr: 'Dönüştür düğmesine tıklayın',
    sv: 'Klicka på knappen Konvertera',
    no: 'Klikk på konverter-knappen',
    ja: '変換ボタンをクリック',
    hi: 'रूपांतरित बटन पर क्लिक करें',
    ar: 'انقر على زر التحويل',
    fa: 'روی دکمه تبدیل کلیک کنید',
    zh: '点击转换按钮',
  },
  clickProtect: {
    pl: 'Kliknij przycisk zabezpieczenia', en: 'Click the protect button',
    de: 'Klicken Sie auf die Schaltfläche Schützen',
    es: 'Haga clic en el botón Proteger',
    fr: 'Cliquez sur le bouton Protéger',
    it: 'Clicca sul pulsante Proteggi',
    pt: 'Clique no botão Proteger',
    is: 'Smelltu á vernda hnappinn',
    tr: 'Koru düğmesine tıklayın',
    sv: 'Klicka på knappen Skydda',
    no: 'Klikk på beskytt-knappen',
    ja: '保護ボタンをクリック',
    hi: 'सुरक्षित बटन पर क्लिक करें',
    ar: 'انقر على زر الحماية',
    fa: 'روی دکمه محافظت کلیک کنید',
    zh: '点击保护按钮',
  },
  clickUnlock: {
    pl: 'Kliknij przycisk odblokowania', en: 'Click unlock to remove the password',
    de: 'Klicken Sie auf Entsperren, um das Passwort zu entfernen',
    es: 'Haga clic en Desbloquear para quitar la contraseña',
    fr: 'Cliquez sur Déverrouiller pour supprimer le mot de passe',
    it: 'Clicca su Sblocca per rimuovere la password',
    pt: 'Clique em Desbloquear para remover a senha',
    is: 'Smelltu á aflæsa til að fjarlægja lykilorðið',
    tr: 'Şifreyi kaldırmak için Kilidi Aç\'a tıklayın',
    sv: 'Klicka på Lås upp för att ta bort lösenordet',
    no: 'Klikk på Lås opp for å fjerne passordet',
    ja: 'ロック解除をクリックしてパスワードを削除',
    hi: 'पासवर्ड हटाने के लिए अनलॉक पर क्लिक करें',
    ar: 'انقر على إلغاء القفل لإزالة كلمة المرور',
    fa: 'برای حذف رمز عبور روی باز کردن قفل کلیک کنید',
    zh: '点击解锁以移除密码',
  },
  clickRotate: {
    pl: 'Kliknij przycisk obrotu', en: 'Click the rotate button',
    de: 'Klicken Sie auf die Schaltfläche Drehen',
    es: 'Haga clic en el botón Rotar',
    fr: 'Cliquez sur le bouton Pivoter',
    it: 'Clicca sul pulsante Ruota',
    pt: 'Clique no botão Girar',
    is: 'Smelltu á snúa hnappinn',
    tr: 'Döndür düğmesine tıklayın',
    sv: 'Klicka på knappen Rotera',
    no: 'Klikk på roter-knappen',
    ja: '回転ボタンをクリック',
    hi: 'घुमाएँ बटन पर क्लिक करें',
    ar: 'انقر على زر التدوير',
    fa: 'روی دکمه چرخش کلیک کنید',
    zh: '点击旋转按钮',
  },
  clickAddNumbers: {
    pl: 'Kliknij przycisk dodawania numerów',
    en: 'Click the add numbers button',
    de: 'Klicken Sie auf die Schaltfläche Nummern hinzufügen',
    es: 'Haga clic en el botón Agregar números',
    fr: 'Cliquez sur le bouton Ajouter des numéros',
    it: 'Clicca sul pulsante Aggiungi numeri',
    pt: 'Clique no botão Adicionar números',
    is: 'Smelltu á bæta við númerum hnappinn',
    tr: 'Numara ekle düğmesine tıklayın',
    sv: 'Klicka på knappen Lägg till nummer',
    no: 'Klikk på legg til numre-knappen',
    ja: 'ページ番号追加ボタンをクリック',
    hi: 'संख्या जोड़ें बटन पर क्लिक करें',
    ar: 'انقر على زر إضافة الأرقام',
    fa: 'روی دکمه افزودن اعداد کلیک کنید',
    zh: '点击添加页码按钮',
  },
  clickAddWatermark: {
    pl: 'Kliknij przycisk dodawania znaku wodnego',
    en: 'Click the add watermark button',
    de: 'Klicken Sie auf die Schaltfläche Wasserzeichen hinzufügen',
    es: 'Haga clic en el botón Agregar marca de agua',
    fr: 'Cliquez sur le bouton Ajouter un filigrane',
    it: 'Clicca sul pulsante Aggiungi filigrana',
    pt: 'Clique no botão Adicionar marca d\'água',
    is: 'Smelltu á bæta við vatnsmerki hnappinn',
    tr: 'Filigran ekle düğmesine tıklayın',
    sv: 'Klicka på knappen Lägg till vattenstämpel',
    no: 'Klikk på legg til vannmerke-knappen',
    ja: '透かし追加ボタンをクリック',
    hi: 'वॉटरमार्क जोड़ें बटन पर क्लिक करें',
    ar: 'انقر على زر إضافة العلامة المائية',
    fa: 'روی دکمه افزودن واترمارک کلیک کنید',
    zh: '点击添加水印按钮',
  },
  clickOcr: {
    pl: 'Kliknij przycisk OCR', en: 'Click the OCR button',
    de: 'Klicken Sie auf die OCR-Schaltfläche',
    es: 'Haga clic en el botón OCR',
    fr: 'Cliquez sur le bouton OCR',
    it: 'Clicca sul pulsante OCR',
    pt: 'Clique no botão OCR',
    is: 'Smelltu á OCR hnappinn',
    tr: 'OCR düğmesine tıklayın',
    sv: 'Klicka på OCR-knappen',
    no: 'Klikk på OCR-knappen',
    ja: 'OCRボタンをクリック',
    hi: 'OCR बटन पर क्लिक करें',
    ar: 'انقر على زر OCR',
    fa: 'روی دکمه OCR کلیک کنید',
    zh: '点击OCR按钮',
  },
  clickExtract: {
    pl: 'Kliknij przycisk wyodrębniania', en: 'Click the extract button',
    de: 'Klicken Sie auf die Schaltfläche Extrahieren',
    es: 'Haga clic en el botón Extraer',
    fr: 'Cliquez sur le bouton Extraire',
    it: 'Clicca sul pulsante Estrai',
    pt: 'Clique no botão Extrair',
    is: 'Smelltu á draga út hnappinn',
    tr: 'Çıkar düğmesine tıklayın',
    sv: 'Klicka på knappen Extrahera',
    no: 'Klikk på ekstraher-knappen',
    ja: '抽出ボタンをクリック',
    hi: 'निकालें बटन पर क्लिक करें',
    ar: 'انقر على زر الاستخراج',
    fa: 'روی دکمه استخراج کلیک کنید',
    zh: '点击提取按钮',
  },
  clickDelete: {
    pl: 'Kliknij przycisk usuwania', en: 'Click the delete button',
    de: 'Klicken Sie auf die Schaltfläche Löschen',
    es: 'Haga clic en el botón Eliminar',
    fr: 'Cliquez sur le bouton Supprimer',
    it: 'Clicca sul pulsante Elimina',
    pt: 'Clique no botão Excluir',
    is: 'Smelltu á eyða hnappinn',
    tr: 'Sil düğmesine tıklayın',
    sv: 'Klicka på knappen Ta bort',
    no: 'Klikk på slett-knappen',
    ja: '削除ボタンをクリック',
    hi: 'हटाएँ बटन पर क्लिक करें',
    ar: 'انقر على زر الحذف',
    fa: 'روی دکمه حذف کلیک کنید',
    zh: '点击删除按钮',
  },
  clickReorder: {
    pl: 'Kliknij przycisk zmiany kolejności',
    en: 'Click the reorder button',
    de: 'Klicken Sie auf die Schaltfläche Neu anordnen',
    es: 'Haga clic en el botón Reordenar',
    fr: 'Cliquez sur le bouton Réorganiser',
    it: 'Clicca sul pulsante Riordina',
    pt: 'Clique no botão Reordenar',
    is: 'Smelltu á endurraða hnappinn',
    tr: 'Yeniden sırala düğmesine tıklayın',
    sv: 'Klicka på knappen Ordna om',
    no: 'Klikk på omorganiser-knappen',
    ja: '並べ替えボタンをクリック',
    hi: 'पुनर्क्रमित बटन पर क्लिक करें',
    ar: 'انقر على زر إعادة الترتيب',
    fa: 'روی دکمه مرتب‌سازی مجدد کلیک کنید',
    zh: '点击重新排序按钮',
  },
  clickCrop: {
    pl: 'Kliknij przycisk przycinania', en: 'Click the crop button',
    de: 'Klicken Sie auf die Schaltfläche Zuschneiden',
    es: 'Haga clic en el botón Recortar',
    fr: 'Cliquez sur le bouton Rogner',
    it: 'Clicca sul pulsante Ritaglia',
    pt: 'Clique no botão Cortar',
    is: 'Smelltu á klippa hnappinn',
    tr: 'Kırp düğmesine tıklayın',
    sv: 'Klicka på knappen Beskär',
    no: 'Klikk på beskjær-knappen',
    ja: '切り抜きボタンをクリック',
    hi: 'क्रॉप बटन पर क्लिक करें',
    ar: 'انقر على زر القص',
    fa: 'روی دکمه برش کلیک کنید',
    zh: '点击裁剪按钮',
  },
  clickAddPage: {
    pl: 'Kliknij przycisk dodawania strony',
    en: 'Click the add page button',
    de: 'Klicken Sie auf die Schaltfläche Seite hinzufügen',
    es: 'Haga clic en el botón Agregar página',
    fr: 'Cliquez sur le bouton Ajouter une page',
    it: 'Clicca sul pulsante Aggiungi pagina',
    pt: 'Clique no botão Adicionar página',
    is: 'Smelltu á bæta við síðu hnappinn',
    tr: 'Sayfa ekle düğmesine tıklayın',
    sv: 'Klicka på knappen Lägg till sida',
    no: 'Klikk på legg til side-knappen',
    ja: 'ページ追加ボタンをクリック',
    hi: 'पृष्ठ जोड़ें बटन पर क्लिक करें',
    ar: 'انقر على زر إضافة صفحة',
    fa: 'روی دکمه افزودن صفحه کلیک کنید',
    zh: '点击添加页面按钮',
  },
  clickSave: {
    pl: 'Kliknij przycisk zapisu', en: 'Click the save button',
    de: 'Klicken Sie auf die Schaltfläche Speichern',
    es: 'Haga clic en el botón Guardar',
    fr: 'Cliquez sur le bouton Enregistrer',
    it: 'Clicca sul pulsante Salva',
    pt: 'Clique no botão Salvar',
    is: 'Smelltu á vista hnappinn',
    tr: 'Kaydet düğmesine tıklayın',
    sv: 'Klicka på knappen Spara',
    no: 'Klikk på lagre-knappen',
    ja: '保存ボタンをクリック',
    hi: 'सहेजें बटन पर क्लिक करें',
    ar: 'انقر على زر الحفظ',
    fa: 'روی دکمه ذخیره کلیک کنید',
    zh: '点击保存按钮',
  },
  clickSaveEdit: {
    pl: 'Kliknij przycisk zapisu zmian',
    en: 'Click the save changes button',
    de: 'Klicken Sie auf die Schaltfläche Änderungen speichern',
    es: 'Haga clic en el botón Guardar cambios',
    fr: 'Cliquez sur le bouton Enregistrer les modifications',
    it: 'Clicca sul pulsante Salva modifiche',
    pt: 'Clique no botão Salvar alterações',
    is: 'Smelltu á vista breytingar hnappinn',
    tr: 'Değişiklikleri kaydet düğmesine tıklayın',
    sv: 'Klicka på knappen Spara ändringar',
    no: 'Klikk på lagre endringer-knappen',
    ja: '変更保存ボタンをクリック',
    hi: 'परिवर्तन सहेजें बटन पर क्लिक करें',
    ar: 'انقر على زر حفظ التغييرات',
    fa: 'روی دکمه ذخیره تغییرات کلیک کنید',
    zh: '点击保存更改按钮',
  },
  clickSign: {
    pl: 'Kliknij przycisk podpisu', en: 'Click the sign button',
    de: 'Klicken Sie auf die Schaltfläche Signieren',
    es: 'Haga clic en el botón Firmar',
    fr: 'Cliquez sur le bouton Signer',
    it: 'Clicca sul pulsante Firma',
    pt: 'Clique no botão Assinar',
    is: 'Smelltu á undirrita hnappinn',
    tr: 'İmzala düğmesine tıklayın',
    sv: 'Klicka på knappen Signera',
    no: 'Klikk på signer-knappen',
    ja: '署名ボタンをクリック',
    hi: 'हस्ताक्षर बटन पर क्लिक करें',
    ar: 'انقر على زر التوقيع',
    fa: 'روی دکمه امضا کلیک کنید',
    zh: '点击签名按钮',
  },
  clickFlatten: {
    pl: 'Kliknij przycisk spłaszczania', en: 'Click the flatten button',
    de: 'Klicken Sie auf die Schaltfläche Glätten',
    es: 'Haga clic en el botón Aplanar',
    fr: 'Cliquez sur le bouton Aplatir',
    it: 'Clicca sul pulsante Appiattisci',
    pt: 'Clique no botão Achatar',
    is: 'Smelltu á fletja hnappinn',
    tr: 'Düzleştir düğmesine tıklayın',
    sv: 'Klicka på knappen Platt',
    no: 'Klikk på flatlegg-knappen',
    ja: 'フラット化ボタンをクリック',
    hi: 'समतल बटन पर क्लिक करें',
    ar: 'انقر على زر التسطيح',
    fa: 'روی دکمه مسطح‌سازی کلیک کنید',
    zh: '点击压平按钮',
  },
  clickCompare: {
    pl: 'Kliknij przycisk porównania', en: 'Click the compare button',
    de: 'Klicken Sie auf die Schaltfläche Vergleichen',
    es: 'Haga clic en el botón Comparar',
    fr: 'Cliquez sur le bouton Comparer',
    it: 'Clicca sul pulsante Confronta',
    pt: 'Clique no botão Comparar',
    is: 'Smelltu á bera saman hnappinn',
    tr: 'Karşılaştır düğmesine tıklayın',
    sv: 'Klicka på knappen Jämför',
    no: 'Klikk på sammenlign-knappen',
    ja: '比較ボタンをクリック',
    hi: 'तुलना बटन पर क्लिक करें',
    ar: 'انقر على زر المقارنة',
    fa: 'روی دکمه مقایسه کلیک کنید',
    zh: '点击比较按钮',
  },
  clickSummarize: {
    pl: 'Kliknij przycisk streszczenia',
    en: 'Click the summarize button',
    de: 'Klicken Sie auf die Schaltfläche Zusammenfassen',
    es: 'Haga clic en el botón Resumir',
    fr: 'Cliquez sur le bouton Résumer',
    it: 'Clicca sul pulsante Riassumi',
    pt: 'Clique no botão Resumir',
    is: 'Smelltu á draga saman hnappinn',
    tr: 'Özetle düğmesine tıklayın',
    sv: 'Klicka på knappen Sammanfatta',
    no: 'Klikk på oppsummer-knappen',
    ja: '要約ボタンをクリック',
    hi: 'सारांश बटन पर क्लिक करें',
    ar: 'انقر على زر التلخيص',
    fa: 'روی دکمه خلاصه‌سازی کلیک کنید',
    zh: '点击摘要按钮',
  },
  clickRedact: {
    pl: 'Kliknij przycisk redakcji', en: 'Click the redact button',
    de: 'Klicken Sie auf die Schaltfläche Schwärzen',
    es: 'Haga clic en el botón Redactar',
    fr: 'Cliquez sur le bouton Caviarder',
    it: 'Clicca sul pulsante Oscura',
    pt: 'Clique no botão Redigir',
    is: 'Smelltu á raða hnappinn',
    tr: 'Redakte et düğmesine tıklayın',
    sv: 'Klicka på knappen Redigera',
    no: 'Klikk på rediger-knappen',
    ja: '墨消しボタンをクリック',
    hi: 'रिडैक्ट बटन पर क्लिक करें',
    ar: 'انقر على زر التنقيح',
    fa: 'روی دکمه ویرایش امن کلیک کنید',
    zh: '点击编辑按钮',
  },
  clickFill: {
    pl: 'Kliknij przycisk pobierania',
    en: 'Click the download button',
    de: 'Klicken Sie auf die Schaltfläche Herunterladen',
    es: 'Haga clic en el botón Descargar',
    fr: 'Cliquez sur le bouton Télécharger',
    it: 'Clicca sul pulsante Scarica',
    pt: 'Clique no botão Baixar',
    is: 'Smelltu á sækja hnappinn',
    tr: 'İndir düğmesine tıklayın',
    sv: 'Klicka på knappen Ladda ner',
    no: 'Klikk på last ned-knappen',
    ja: 'ダウンロードボタンをクリック',
    hi: 'डाउनलोड बटन पर क्लिक करें',
    ar: 'انقر على زر التنزيل',
    fa: 'روی دکمه دانلود کلیک کنید',
    zh: '点击下载按钮',
  },
  clickSaveChanges: {
    pl: 'Kliknij przycisk pobierania',
    en: 'Click the download button',
    de: 'Klicken Sie auf die Schaltfläche Herunterladen',
    es: 'Haga clic en el botón Descargar',
    fr: 'Cliquez sur le bouton Télécharger',
    it: 'Clicca sul pulsante Scarica',
    pt: 'Clique no botão Baixar',
    is: 'Smelltu á sækja hnappinn',
    tr: 'İndir düğmesine tıklayın',
    sv: 'Klicka på knappen Ladda ner',
    no: 'Klikk på last ned-knappen',
    ja: 'ダウンロードボタンをクリック',
    hi: 'डाउनलोड बटन पर क्लिक करें',
    ar: 'انقر على زر التنزيل',
    fa: 'روی دکمه دانلود کلیک کنید',
    zh: '点击下载按钮',
  },

  // --- Enter data steps ---
  enterPassword: {
    pl: 'Wprowadź silne hasło', en: 'Enter a strong password',
    de: 'Geben Sie ein starkes Passwort ein',
    es: 'Ingrese una contraseña segura',
    fr: 'Entrez un mot de passe fort',
    it: 'Inserisci una password sicura',
    pt: 'Insira uma senha forte',
    is: 'Sláðu inn sterkt lykilorð',
    tr: 'Güçlü bir şifre girin',
    sv: 'Ange ett starkt lösenord',
    no: 'Skriv inn et sterkt passord',
    ja: '強力なパスワードを入力',
    hi: 'एक मजबूत पासवर्ड दर्ज करें',
    ar: 'أدخل كلمة مرور قوية',
    fa: 'یک رمز عبور قوی وارد کنید',
    zh: '输入强密码',
  },
  enterPasswordForUnlock: {
    pl: 'Wprowadź hasło', en: 'Enter the password',
    de: 'Geben Sie das Passwort ein',
    es: 'Ingrese la contraseña',
    fr: 'Entrez le mot de passe',
    it: 'Inserisci la password',
    pt: 'Insira a senha',
    is: 'Sláðu inn lykilorðið',
    tr: 'Şifreyi girin',
    sv: 'Ange lösenordet',
    no: 'Skriv inn passordet',
    ja: 'パスワードを入力',
    hi: 'पासवर्ड दर्ज करें',
    ar: 'أدخل كلمة المرور',
    fa: 'رمز عبور را وارد کنید',
    zh: '输入密码',
  },
  enterPosition: {
    pl: 'Wybierz pozycję, numer początkowy i rozmiar czcionki',
    en: 'Choose position, starting number, and font size',
    de: 'Wählen Sie Position, Startnummer und Schriftgröße',
    es: 'Elija la posición, el número inicial y el tamaño de fuente',
    fr: 'Choisissez la position, le numéro de départ et la taille de police',
    it: 'Scegli posizione, numero iniziale e dimensione carattere',
    pt: 'Escolha a posição, o número inicial e o tamanho da fonte',
    is: 'Veldu stöðu, upphafsnúmer og leturstærð',
    tr: 'Konum, başlangıç numarası ve yazı tipi boyutunu seçin',
    sv: 'Välj position, startnummer och teckenstorlek',
    no: 'Velg posisjon, startnummer og skriftstørrelse',
    ja: '位置、開始番号、フォントサイズを選択',
    hi: 'स्थिति, प्रारंभ संख्या और फ़ॉन्ट आकार चुनें',
    ar: 'اختر الموضع والرقم البداية وحجم الخط',
    fa: 'موقعیت، شماره شروع و اندازه فونت را انتخاب کنید',
    zh: '选择位置、起始编号和字体大小',
  },
  drawSignature: {
    pl: 'Narysuj lub wpisz swój podpis',
    en: 'Draw or type your signature',
    de: 'Zeichnen oder tippen Sie Ihre Unterschrift',
    es: 'Dibuje o escriba su firma',
    fr: 'Dessinez ou tapez votre signature',
    it: 'Disegna o digita la tua firma',
    pt: 'Desenhe ou digite sua assinatura',
    is: 'Teiknaðu eða sláðu inn undirskriftina þína',
    tr: 'İmzanızı çizin veya yazın',
    sv: 'Rita eller skriv din signatur',
    no: 'Tegn eller skriv signaturen din',
    ja: '署名を描くか入力',
    hi: 'अपने हस्ताक्षर बनाएं या टाइप करें',
    ar: 'ارسم أو اكتب توقيعك',
    fa: 'امضای خود را بکشید یا تایپ کنید',
    zh: '绘制或输入您的签名',
  },
  placeSignature: {
    pl: 'Umieść podpis na dokumencie',
    en: 'Place the signature on the document',
    de: 'Platzieren Sie die Unterschrift auf dem Dokument',
    es: 'Coloque la firma en el documento',
    fr: 'Placez la signature sur le document',
    it: 'Posiziona la firma sul documento',
    pt: 'Coloque a assinatura no documento',
    is: 'Settu undirskriftina á skjalið',
    tr: 'İmzayı belgeye yerleştirin',
    sv: 'Placera signaturen på dokumentet',
    no: 'Plasser signaturen på dokumentet',
    ja: '文書に署名を配置',
    hi: 'दस्तावेज़ पर हस्ताक्षर रखें',
    ar: 'ضع التوقيع على المستند',
    fa: 'امضا را روی سند قرار دهید',
    zh: '将签名放在文档上',
  },

  // --- Selection by thumbnails ---
  selectPagesExtract: {
    pl: 'Wybierz strony klikając miniatury',
    en: 'Select pages to extract by clicking thumbnails',
    de: 'Wählen Sie Seiten zum Extrahieren durch Klicken auf Miniaturen aus',
    es: 'Seleccione las páginas para extraer haciendo clic en las miniaturas',
    fr: 'Sélectionnez les pages à extraire en cliquant sur les vignettes',
    it: 'Seleziona le pagine da estrarre cliccando sulle miniature',
    pt: 'Selecione as páginas para extrair clicando nas miniaturas',
    is: 'Veldu síður til að draga út með því að smella á smámyndir',
    tr: 'Küçük resimlere tıklayarak çıkarılacak sayfaları seçin',
    sv: 'Välj sidor att extrahera genom att klicka på miniatyrer',
    no: 'Velg sider å ekstrahere ved å klikke på miniatyrbilder',
    ja: 'サムネイルをクリックして抽出するページを選択',
    hi: 'थंबनेल पर क्लिक करके निकालने के लिए पृष्ठ चुनें',
    ar: 'اختر الصفحات لاستخراجها بالنقر على الصور المصغرة',
    fa: 'صفحات مورد نظر برای استخراج را با کلیک روی تصاویر بندانگشتی انتخاب کنید',
    zh: '点击缩略图选择要提取的页面',
  },
  selectPagesDelete: {
    pl: 'Wybierz strony do usunięcia klikając miniatury',
    en: 'Select pages to delete by clicking thumbnails',
    de: 'Wählen Sie Seiten zum Löschen durch Klicken auf Miniaturen aus',
    es: 'Seleccione las páginas para eliminar haciendo clic en las miniaturas',
    fr: 'Sélectionnez les pages à supprimer en cliquant sur les vignettes',
    it: 'Seleziona le pagine da eliminare cliccando sulle miniature',
    pt: 'Selecione as páginas para excluir clicando nas miniaturas',
    is: 'Veldu síður til að eyða með því að smella á smámyndir',
    tr: 'Küçük resimlere tıklayarak silinecek sayfaları seçin',
    sv: 'Välj sidor att ta bort genom att klicka på miniatyrer',
    no: 'Velg sider å slette ved å klikke på miniatyrbilder',
    ja: 'サムネイルをクリックして削除するページを選択',
    hi: 'थंबनेल पर क्लिक करके हटाने के लिए पृष्ठ चुनें',
    ar: 'اختر الصفحات للحذف بالنقر على الصور المصغرة',
    fa: 'صفحات مورد نظر برای حذف را با کلیک روی تصاویر بندانگشتی انتخاب کنید',
    zh: '点击缩略图选择要删除的页面',
  },
  selectPagesRedact: {
    pl: 'Wybierz strony do redakcji klikając miniatury',
    en: 'Select pages to redact by clicking thumbnails',
    de: 'Wählen Sie Seiten zum Schwärzen durch Klicken auf Miniaturen aus',
    es: 'Seleccione las páginas para redactar haciendo clic en las miniaturas',
    fr: 'Sélectionnez les pages à caviarder en cliquant sur les vignettes',
    it: 'Seleziona le pagine da oscurare cliccando sulle miniature',
    pt: 'Selecione as páginas para redigir clicando nas miniaturas',
    is: 'Veldu síður til að raða með því að smella á smámyndir',
    tr: 'Küçük resimlere tıklayarak redakte edilecek sayfaları seçin',
    sv: 'Välj sidor att redigera genom att klicka på miniatyrer',
    no: 'Velg sider å redigere ved å klikke på miniatyrbilder',
    ja: 'サムネイルをクリックして墨消しするページを選択',
    hi: 'थंबनेल पर क्लिक करके रिडैक्ट करने के लिए पृष्ठ चुनें',
    ar: 'اختر الصفحات للتنقيح بالنقر على الصور المصغرة',
    fa: 'صفحات مورد نظر برای ویرایش امن را با کلیک روی تصاویر بندانگشتی انتخاب کنید',
    zh: '点击缩略图选择要编辑的页面',
  },

  // --- Drag and drop reorder ---
  dragReorder: {
    pl: 'Przeciągnij miniatury stron aby zmienić kolejność',
    en: 'Drag and drop page thumbnails to reorder',
    de: 'Ziehen Sie Seitenminiaturen per Drag & Drop, um sie neu anzuordnen',
    es: 'Arrastre y suelte las miniaturas de página para reordenar',
    fr: 'Faites glisser et déposez les vignettes de page pour réorganiser',
    it: 'Trascina e rilascia le miniature delle pagine per riordinarle',
    pt: 'Arraste e solte as miniaturas de página para reordenar',
    is: 'Dragðu og slepptu smámyndum síðna til að endurraða',
    tr: 'Sayfa küçük resimlerini sürükleyip bırakarak yeniden sıralayın',
    sv: 'Dra och släpp sidminiatyrer för att ordna om',
    no: 'Dra og slipp sideminiatyrbilder for å omorganisere',
    ja: 'ページサムネイルをドラッグ＆ドロップして並べ替え',
    hi: 'पृष्ठ थंबनेल को खींचकर और छोड़कर पुनर्क्रमित करें',
    ar: 'اسحب وأفلت الصور المصغرة للصفحات لإعادة الترتيب',
    fa: 'تصاویر بندانگشتی صفحات را بکشید و رها کنید تا مرتب‌سازی مجدد کنید',
    zh: '拖放页面缩略图以重新排序',
  },

  // --- Add content steps ---
  addTextAnnotations: {
    pl: 'Dodaj tekst, podświetlenia lub adnotacje',
    en: 'Add text, highlights, or annotations',
    de: 'Fügen Sie Text, Hervorhebungen oder Anmerkungen hinzu',
    es: 'Agregue texto, resaltados o anotaciones',
    fr: 'Ajoutez du texte, des surlignages ou des annotations',
    it: 'Aggiungi testo, evidenziazioni o annotazioni',
    pt: 'Adicione texto, destaques ou anotações',
    is: 'Bættu við texta, hápunkti eða skýringum',
    tr: 'Metin, vurgulama veya açıklama ekleyin',
    sv: 'Lägg till text, markeringar eller anteckningar',
    no: 'Legg til tekst, uthevinger eller merknader',
    ja: 'テキスト、ハイライト、注釈を追加',
    hi: 'टेक्स्ट, हाइलाइट या एनोटेशन जोड़ें',
    ar: 'أضف نصاً أو تمييزات أو تعليقات',
    fa: 'متن، برجسته‌سازی یا حاشیه‌نویسی اضافه کنید',
    zh: '添加文本、高亮或注释',
  },
  fillFields: {
    pl: 'Wypełnij pola tekstowe, checkboxy i listy',
    en: 'Fill in text fields, checkboxes and dropdowns',
    de: 'Füllen Sie Textfelder, Kontrollkästchen und Dropdowns aus',
    es: 'Complete campos de texto, casillas de verificación y listas desplegables',
    fr: 'Remplissez les champs de texte, cases à cocher et listes déroulantes',
    it: 'Compila campi di testo, caselle di controllo e menu a tendina',
    pt: 'Preencha campos de texto, caixas de seleção e listas suspensas',
    is: 'Fylltu út textareiti, gátreiti og fellilista',
    tr: 'Metin alanlarını, onay kutularını ve açılır listeleri doldurun',
    sv: 'Fyll i textfält, kryssrutor och rullgardinslistor',
    no: 'Fyll ut tekstfelt, avkrysningsbokser og rullegardiner',
    ja: 'テキストフィールド、チェックボックス、ドロップダウンを入力',
    hi: 'टेक्स्ट फ़ील्ड, चेकबॉक्स और ड्रॉपडाउन भरें',
    ar: 'املأ حقول النص وخانات الاختيار والقوائم المنسدلة',
    fa: 'فیلدهای متن، چک‌باکس‌ها و کشویی‌ها را پر کنید',
    zh: '填写文本字段、复选框和下拉列表',
  },

  // --- Wait steps ---
  waitConversion: {
    pl: 'Poczekaj na konwersję', en: 'Wait for the conversion process',
    de: 'Warten Sie auf den Konvertierungsvorgang',
    es: 'Espere el proceso de conversión',
    fr: 'Attendez le processus de conversion',
    it: 'Attendi il processo di conversione',
    pt: 'Aguarde o processo de conversão',
    is: 'Bíddu eftir umbreytingarferlinu',
    tr: 'Dönüştürme işlemini bekleyin',
    sv: 'Vänta på konverteringsprocessen',
    no: 'Vent på konverteringsprosessen',
    ja: '変換処理をお待ちください',
    hi: 'रूपांतरण प्रक्रिया की प्रतीक्षा करें',
    ar: 'انتظر عملية التحويل',
    fa: 'منتظر فرآیند تبدیل بمانید',
    zh: '等待转换过程',
  },
  waitExtraction: {
    pl: 'Poczekaj na ekstrakcję danych',
    en: 'Wait for data extraction',
    de: 'Warten Sie auf die Datenextraktion',
    es: 'Espere la extracción de datos',
    fr: 'Attendez l\'extraction des données',
    it: 'Attendi l\'estrazione dei dati',
    pt: 'Aguarde a extração de dados',
    is: 'Bíddu eftir gagnaútdrætti',
    tr: 'Veri çıkarma işlemini bekleyin',
    sv: 'Vänta på datautdragningen',
    no: 'Vent på datauttrekking',
    ja: 'データ抽出をお待ちください',
    hi: 'डेटा निष्कर्षण की प्रतीक्षा करें',
    ar: 'انتظر استخراج البيانات',
    fa: 'منتظر استخراج داده باشید',
    zh: '等待数据提取',
  },
  waitSvgConversion: {
    pl: 'Poczekaj na konwersję do SVG',
    en: 'Wait for SVG conversion',
    de: 'Warten Sie auf die SVG-Konvertierung',
    es: 'Espere la conversión a SVG',
    fr: 'Attendez la conversion SVG',
    it: 'Attendi la conversione SVG',
    pt: 'Aguarde a conversão para SVG',
    is: 'Bíddu eftir SVG umbreytingu',
    tr: 'SVG dönüştürmesini bekleyin',
    sv: 'Vänta på SVG-konvertering',
    no: 'Vent på SVG-konvertering',
    ja: 'SVG変換をお待ちください',
    hi: 'SVG रूपांतरण की प्रतीक्षा करें',
    ar: 'انتظر تحويل SVG',
    fa: 'منتظر تبدیل SVG باشید',
    zh: '等待SVG转换',
  },
  waitEpubConversion: {
    pl: 'Poczekaj na konwersję do EPUB',
    en: 'Wait for EPUB conversion',
    de: 'Warten Sie auf die EPUB-Konvertierung',
    es: 'Espere la conversión a EPUB',
    fr: 'Attendez la conversion EPUB',
    it: 'Attendi la conversione EPUB',
    pt: 'Aguarde a conversão para EPUB',
    is: 'Bíddu eftir EPUB umbreytingu',
    tr: 'EPUB dönüştürmesini bekleyin',
    sv: 'Vänta på EPUB-konvertering',
    no: 'Vent på EPUB-konvertering',
    ja: 'EPUB変換をお待ちください',
    hi: 'EPUB रूपांतरण की प्रतीक्षा करें',
    ar: 'انتظر تحويل EPUB',
    fa: 'منتظر تبدیل EPUB باشید',
    zh: '等待EPUB转换',
  },
  waitAnalysis: {
    pl: 'Poczekaj na analizę dokumentu przez AI',
    en: 'Wait for AI to analyze the document',
    de: 'Warten Sie auf die KI-Analyse des Dokuments',
    es: 'Espere a que la IA analice el documento',
    fr: 'Attendez que l\'IA analyse le document',
    it: 'Attendi che l\'IA analizzi il documento',
    pt: 'Aguarde a IA analisar o documento',
    is: 'Bíddu eftir að AI greini skjalið',
    tr: 'Yapay zekanın belgeyi analiz etmesini bekleyin',
    sv: 'Vänta på att AI analyserar dokumentet',
    no: 'Vent på at AI analyserer dokumentet',
    ja: 'AIが文書を分析するのを待つ',
    hi: 'AI द्वारा दस्तावेज़ का विश्लेषण करने की प्रतीक्षा करें',
    ar: 'انتظر حتى يقوم الذكاء الاصطناعي بتحليل المستند',
    fa: 'منتظر تحلیل سند توسط هوش مصنوعی باشید',
    zh: '等待AI分析文档',
  },

  // --- Download steps ---
  downloadPdf: {
    pl: 'Pobierz plik PDF', en: 'Download the PDF file',
    de: 'Laden Sie die PDF-Datei herunter',
    es: 'Descargue el archivo PDF',
    fr: 'Téléchargez le fichier PDF',
    it: 'Scarica il file PDF',
    pt: 'Baixe o arquivo PDF',
    is: 'Sæktu PDF skránna',
    tr: 'PDF dosyasını indirin',
    sv: 'Ladda ner PDF-filen',
    no: 'Last ned PDF-filen',
    ja: 'PDFファイルをダウンロード',
    hi: 'PDF फ़ाइल डाउनलोड करें',
    ar: 'قم بتنزيل ملف PDF',
    fa: 'فایل PDF را دانلود کنید',
    zh: '下载PDF文件',
  },
  downloadCompressedPdf: {
    pl: 'Pobierz skompresowany plik PDF',
    en: 'Download the compressed PDF file',
    de: 'Laden Sie die komprimierte PDF-Datei herunter',
    es: 'Descargue el archivo PDF comprimido',
    fr: 'Téléchargez le fichier PDF compressé',
    it: 'Scarica il file PDF compresso',
    pt: 'Baixe o arquivo PDF comprimido',
    is: 'Sæktu þjappaða PDF skrána',
    tr: 'Sıkıştırılmış PDF dosyasını indirin',
    sv: 'Ladda ner den komprimerade PDF-filen',
    no: 'Last ned den komprimerte PDF-filen',
    ja: '圧縮されたPDFファイルをダウンロード',
    hi: 'संपीड़ित PDF फ़ाइल डाउनलोड करें',
    ar: 'قم بتنزيل ملف PDF المضغوط',
    fa: 'فایل PDF فشرده‌شده را دانلود کنید',
    zh: '下载压缩后的PDF文件',
  },
  downloadIndividualPdfs: {
    pl: 'Pobierz rozdzielone pliki PDF',
    en: 'Download the individual PDF files',
    de: 'Laden Sie die einzelnen PDF-Dateien herunter',
    es: 'Descargue los archivos PDF individuales',
    fr: 'Téléchargez les fichiers PDF individuels',
    it: 'Scarica i singoli file PDF',
    pt: 'Baixe os arquivos PDF individuais',
    is: 'Sæktu einstöku PDF skrárnar',
    tr: 'Ayrı ayrı PDF dosyalarını indirin',
    sv: 'Ladda ner de enskilda PDF-filerna',
    no: 'Last ned de enkelte PDF-filene',
    ja: '個別のPDFファイルをダウンロード',
    hi: 'अलग-अलग PDF फ़ाइलें डाउनलोड करें',
    ar: 'قم بتنزيل ملفات PDF الفردية',
    fa: 'فایل‌های PDF جداگانه را دانلود کنید',
    zh: '下载各个PDF文件',
  },
  downloadWord: {
    pl: 'Pobierz dokument Word',
    en: 'Download the Word document',
    de: 'Laden Sie das Word-Dokument herunter',
    es: 'Descargue el documento de Word',
    fr: 'Téléchargez le document Word',
    it: 'Scarica il documento Word',
    pt: 'Baixe o documento do Word',
    is: 'Sæktu Word skjalið',
    tr: 'Word belgesini indirin',
    sv: 'Ladda ner Word-dokumentet',
    no: 'Last ned Word-dokumentet',
    ja: 'Word文書をダウンロード',
    hi: 'Word दस्तावेज़ डाउनलोड करें',
    ar: 'قم بتنزيل مستند Word',
    fa: 'سند Word را دانلود کنید',
    zh: '下载Word文档',
  },
  downloadZip: {
    pl: 'Pobierz obrazy jako plik ZIP',
    en: 'Download the images as a ZIP file',
    de: 'Laden Sie die Bilder als ZIP-Datei herunter',
    es: 'Descargue las imágenes como archivo ZIP',
    fr: 'Téléchargez les images sous forme de fichier ZIP',
    it: 'Scarica le immagini come file ZIP',
    pt: 'Baixe as imagens como um arquivo ZIP',
    is: 'Sæktu myndirnar sem ZIP skrá',
    tr: 'Görselleri ZIP dosyası olarak indirin',
    sv: 'Ladda ner bilderna som en ZIP-fil',
    no: 'Last ned bildene som en ZIP-fil',
    ja: '画像をZIPファイルとしてダウンロード',
    hi: 'इमेज को ZIP फ़ाइल के रूप में डाउनलोड करें',
    ar: 'قم بتنزيل الصور كملف ZIP',
    fa: 'تصاویر را به عنوان فایل ZIP دانلود کنید',
    zh: '将图片下载为ZIP文件',
  },
  downloadProtectedPdf: {
    pl: 'Pobierz zabezpieczony plik PDF',
    en: 'Download the password-protected PDF',
    de: 'Laden Sie die passwortgeschützte PDF herunter',
    es: 'Descargue el PDF protegido con contraseña',
    fr: 'Téléchargez le PDF protégé par mot de passe',
    it: 'Scarica il PDF protetto da password',
    pt: 'Baixe o PDF protegido por senha',
    is: 'Sæktu PDF skrána með lykilorði',
    tr: 'Parola korumalı PDF\'i indirin',
    sv: 'Ladda ner den lösenordsskyddade PDF-filen',
    no: 'Last ned den passordbeskyttede PDF-filen',
    ja: 'パスワード保護されたPDFをダウンロード',
    hi: 'पासवर्ड-सुरक्षित PDF डाउनलोड करें',
    ar: 'قم بتنزيل PDF المحمي بكلمة مرور',
    fa: 'PDF محافظت‌شده با رمز عبور را دانلود کنید',
    zh: '下载受密码保护的PDF',
  },
  downloadMergedPdf: {
    pl: 'Pobierz połączony plik PDF',
    en: 'Download the merged PDF file',
    de: 'Laden Sie die zusammengeführte PDF-Datei herunter',
    es: 'Descargue el archivo PDF combinado',
    fr: 'Téléchargez le fichier PDF fusionné',
    it: 'Scarica il file PDF unito',
    pt: 'Baixe o arquivo PDF mesclado',
    is: 'Sæktu sameinuðu PDF skrána',
    tr: 'Birleştirilmiş PDF dosyasını indirin',
    sv: 'Ladda ner den sammanslagna PDF-filen',
    no: 'Last ned den sammenslåtte PDF-filen',
    ja: '結合されたPDFファイルをダウンロード',
    hi: 'मर्ज की गई PDF फ़ाइल डाउनलोड करें',
    ar: 'قم بتنزيل ملف PDF المدمج',
    fa: 'فایل PDF ادغام‌شده را دانلود کنید',
    zh: '下载合并后的PDF文件',
  },
  downloadUnlockedPdf: {
    pl: 'Pobierz odblokowany plik PDF',
    en: 'Download the unlocked PDF',
    de: 'Laden Sie die entsperrte PDF herunter',
    es: 'Descargue el PDF desbloqueado',
    fr: 'Téléchargez le PDF déverrouillé',
    it: 'Scarica il PDF sbloccato',
    pt: 'Baixe o PDF desbloqueado',
    is: 'Sæktu aflæstu PDF skrána',
    tr: 'Kilidi açılmış PDF\'i indirin',
    sv: 'Ladda ner den upplåsta PDF-filen',
    no: 'Last ned den opplåste PDF-filen',
    ja: 'ロック解除されたPDFをダウンロード',
    hi: 'अनलॉक की गई PDF डाउनलोड करें',
    ar: 'قم بتنزيل PDF غير المقفل',
    fa: 'PDF قفل‌گشایی‌شده را دانلود کنید',
    zh: '下载解锁后的PDF',
  },
  downloadRotatedPdf: {
    pl: 'Pobierz obrócony plik PDF',
    en: 'Download the rotated PDF',
    de: 'Laden Sie die gedrehte PDF herunter',
    es: 'Descargue el PDF rotado',
    fr: 'Téléchargez le PDF pivoté',
    it: 'Scarica il PDF ruotato',
    pt: 'Baixe o PDF girado',
    is: 'Sæktu snúnu PDF skrána',
    tr: 'Döndürülmüş PDF\'i indirin',
    sv: 'Ladda ner den roterade PDF-filen',
    no: 'Last ned den roterte PDF-filen',
    ja: '回転されたPDFをダウンロード',
    hi: 'घुमाई गई PDF डाउनलोड करें',
    ar: 'قم بتنزيل PDF المدور',
    fa: 'PDF چرخیده را دانلود کنید',
    zh: '下载旋转后的PDF',
  },
  downloadNumberedPdf: {
    pl: 'Pobierz plik PDF z numerami stron',
    en: 'Download the PDF with page numbers',
    de: 'Laden Sie die PDF mit Seitenzahlen herunter',
    es: 'Descargue el PDF con números de página',
    fr: 'Téléchargez le PDF avec numéros de page',
    it: 'Scarica il PDF con i numeri di pagina',
    pt: 'Baixe o PDF com números de página',
    is: 'Sæktu PDF með síðunúmerum',
    tr: 'Sayfa numaralarıyla PDF\'i indirin',
    sv: 'Ladda ner PDF-filen med sidnummer',
    no: 'Last ned PDF-filen med sidetall',
    ja: 'ページ番号付きPDFをダウンロード',
    hi: 'पृष्ठ संख्या वाली PDF डाउनलोड करें',
    ar: 'قم بتنزيل PDF مع أرقام الصفحات',
    fa: 'PDF با شماره صفحه را دانلود کنید',
    zh: '下载带页码的PDF',
  },
  downloadWatermarkedPdf: {
    pl: 'Pobierz plik PDF ze znakiem wodnym',
    en: 'Download the PDF with watermark',
    de: 'Laden Sie die PDF mit Wasserzeichen herunter',
    es: 'Descargue el PDF con marca de agua',
    fr: 'Téléchargez le PDF avec filigrane',
    it: 'Scarica il PDF con filigrana',
    pt: 'Baixe o PDF com marca d\'água',
    is: 'Sæktu PDF með vatnsmerki',
    tr: 'Filigranlı PDF\'i indirin',
    sv: 'Ladda ner PDF-filen med vattenstämpel',
    no: 'Last ned PDF-filen med vannmerke',
    ja: '透かし入りPDFをダウンロード',
    hi: 'वॉटरमार्क वाली PDF डाउनलोड करें',
    ar: 'قم بتنزيل PDF مع العلامة المائية',
    fa: 'PDF با واترمارک را دانلود کنید',
    zh: '下载带水印的PDF',
  },
  downloadOcrPdf: {
    pl: 'Pobierz PDF z rozpoznanym tekstem',
    en: 'Download the PDF with recognized text',
    de: 'Laden Sie die PDF mit erkanntem Text herunter',
    es: 'Descargue el PDF con texto reconocido',
    fr: 'Téléchargez le PDF avec texte reconnu',
    it: 'Scarica il PDF con testo riconosciuto',
    pt: 'Baixe o PDF com texto reconhecido',
    is: 'Sæktu PDF með viðurkenndum texta',
    tr: 'Tanınan metinle PDF\'i indirin',
    sv: 'Ladda ner PDF-filen med igenkänd text',
    no: 'Last ned PDF-filen med gjenkjent tekst',
    ja: '認識されたテキスト付きPDFをダウンロード',
    hi: 'पहचाने गए टेक्स्ट वाली PDF डाउनलोड करें',
    ar: 'قم بتنزيل PDF مع النص الذي تم التعرف عليه',
    fa: 'PDF با متن شناسایی‌شده را دانلود کنید',
    zh: '下载带识别文本的PDF',
  },
  downloadExtractedPdf: {
    pl: 'Pobierz wyodrębnione strony jako nowy PDF',
    en: 'Download the extracted pages as a new PDF',
    de: 'Laden Sie die extrahierten Seiten als neue PDF herunter',
    es: 'Descargue las páginas extraídas como un nuevo PDF',
    fr: 'Téléchargez les pages extraites sous forme de nouveau PDF',
    it: 'Scarica le pagine estratte come nuovo PDF',
    pt: 'Baixe as páginas extraídas como um novo PDF',
    is: 'Sæktu dregnar síður sem nýja PDF skrá',
    tr: 'Çıkarılan sayfaları yeni bir PDF olarak indirin',
    sv: 'Ladda ner de extraherade sidorna som en ny PDF',
    no: 'Last ned de ekstraherte sidene som en ny PDF',
    ja: '抽出されたページを新しいPDFとしてダウンロード',
    hi: 'निकाले गए पृष्ठों को नई PDF के रूप में डाउनलोड करें',
    ar: 'قم بتنزيل الصفحات المستخرجة كملف PDF جديد',
    fa: 'صفحات استخراج‌شده را به عنوان PDF جدید دانلود کنید',
    zh: '将提取的页面下载为新PDF',
  },
  downloadWithoutPages: {
    pl: 'Pobierz plik PDF bez wybranych stron',
    en: 'Download the PDF without selected pages',
    de: 'Laden Sie die PDF ohne ausgewählte Seiten herunter',
    es: 'Descargue el PDF sin las páginas seleccionadas',
    fr: 'Téléchargez le PDF sans les pages sélectionnées',
    it: 'Scarica il PDF senza le pagine selezionate',
    pt: 'Baixe o PDF sem as páginas selecionadas',
    is: 'Sæktu PDF án valinna síðna',
    tr: 'Seçilen sayfalar olmadan PDF\'i indirin',
    sv: 'Ladda ner PDF-filen utan valda sidor',
    no: 'Last ned PDF-filen uten valgte sider',
    ja: '選択されたページなしでPDFをダウンロード',
    hi: 'चयनित पृष्ठों के बिना PDF डाउनलोड करें',
    ar: 'قم بتنزيل PDF بدون الصفحات المحددة',
    fa: 'PDF را بدون صفحات انتخاب‌شده دانلود کنید',
    zh: '下载不带选定页面的PDF',
  },
  downloadReorderedPdf: {
    pl: 'Pobierz PDF z nową kolejnością',
    en: 'Download the reordered PDF',
    de: 'Laden Sie die neu angeordnete PDF herunter',
    es: 'Descargue el PDF reordenado',
    fr: 'Téléchargez le PDF réorganisé',
    it: 'Scarica il PDF riordinato',
    pt: 'Baixe o PDF reordenado',
    is: 'Sæktu endurröðuðu PDF skrána',
    tr: 'Yeniden sıralanmış PDF\'i indirin',
    sv: 'Ladda ner den omordnade PDF-filen',
    no: 'Last ned den omorganiserte PDF-filen',
    ja: '並べ替えられたPDFをダウンロード',
    hi: 'पुनर्क्रमित PDF डाउनलोड करें',
    ar: 'قم بتنزيل PDF المعاد ترتيبه',
    fa: 'PDF مرتب‌شده مجدد را دانلود کنید',
    zh: '下载重新排序的PDF',
  },
  downloadCroppedPdf: {
    pl: 'Pobierz przycięty plik PDF',
    en: 'Download the cropped PDF',
    de: 'Laden Sie die zugeschnittene PDF herunter',
    es: 'Descargue el PDF recortado',
    fr: 'Téléchargez le PDF rogné',
    it: 'Scarica il PDF ritagliato',
    pt: 'Baixe o PDF cortado',
    is: 'Sæktu klipptu PDF skrána',
    tr: 'Kırpılmış PDF\'i indirin',
    sv: 'Ladda ner den beskurna PDF-filen',
    no: 'Last ned den beskjærte PDF-filen',
    ja: '切り抜かれたPDFをダウンロード',
    hi: 'क्रॉप की गई PDF डाउनलोड करें',
    ar: 'قم بتنزيل PDF المقصوص',
    fa: 'PDF برش‌خورده را دانلود کنید',
    zh: '下载裁剪后的PDF',
  },
  downloadWithBlankPage: {
    pl: 'Pobierz plik PDF z nową stroną',
    en: 'Download the PDF with the new blank page',
    de: 'Laden Sie die PDF mit der neuen leeren Seite herunter',
    es: 'Descargue el PDF con la nueva página en blanco',
    fr: 'Téléchargez le PDF avec la nouvelle page vierge',
    it: 'Scarica il PDF con la nuova pagina vuota',
    pt: 'Baixe o PDF com a nova página em branco',
    is: 'Sæktu PDF með nýrri tómri síðu',
    tr: 'Yeni boş sayfayla PDF\'i indirin',
    sv: 'Ladda ner PDF-filen med den nya tomma sidan',
    no: 'Last ned PDF-filen med den nye tomme siden',
    ja: '新しい空白ページ付きPDFをダウンロード',
    hi: 'नए खाली पृष्ठ वाली PDF डाउनलोड करें',
    ar: 'قم بتنزيل PDF مع الصفحة الفارغة الجديدة',
    fa: 'PDF با صفحه خالی جدید را دانلود کنید',
    zh: '下载带新空白页的PDF',
  },
  downloadEditedPdf: {
    pl: 'Pobierz edytowany plik PDF',
    en: 'Download the edited PDF',
    de: 'Laden Sie die bearbeitete PDF herunter',
    es: 'Descargue el PDF editado',
    fr: 'Téléchargez le PDF modifié',
    it: 'Scarica il PDF modificato',
    pt: 'Baixe o PDF editado',
    is: 'Sæktu breyttu PDF skrána',
    tr: 'Düzenlenmiş PDF\'i indirin',
    sv: 'Ladda ner den redigerade PDF-filen',
    no: 'Last ned den redigerte PDF-filen',
    ja: '編集されたPDFをダウンロード',
    hi: 'संपादित PDF डाउनलोड करें',
    ar: 'قم بتنزيل PDF المعدل',
    fa: 'PDF ویرایش‌شده را دانلود کنید',
    zh: '下载编辑后的PDF',
  },
  downloadSignedPdf: {
    pl: 'Pobierz podpisany plik PDF',
    en: 'Download the signed PDF',
    de: 'Laden Sie die signierte PDF herunter',
    es: 'Descargue el PDF firmado',
    fr: 'Téléchargez le PDF signé',
    it: 'Scarica il PDF firmato',
    pt: 'Baixe o PDF assinado',
    is: 'Sæktu undirrituðu PDF skrána',
    tr: 'İmzalanmış PDF\'i indirin',
    sv: 'Ladda ner den signerade PDF-filen',
    no: 'Last ned den signerte PDF-filen',
    ja: '署名されたPDFをダウンロード',
    hi: 'हस्ताक्षरित PDF डाउनलोड करें',
    ar: 'قم بتنزيل PDF الموقع',
    fa: 'PDF امضا شده را دانلود کنید',
    zh: '下载已签名的PDF',
  },
  downloadMetaPdf: {
    pl: 'Pobierz plik PDF z nowymi metadanymi',
    en: 'Download the PDF with updated metadata',
    de: 'Laden Sie die PDF mit aktualisierten Metadaten herunter',
    es: 'Descargue el PDF con metadatos actualizados',
    fr: 'Téléchargez le PDF avec les métadonnées mises à jour',
    it: 'Scarica il PDF con metadati aggiornati',
    pt: 'Baixe o PDF com metadados atualizados',
    is: 'Sæktu PDF með uppfærðum lýsigögnum',
    tr: 'Güncellenmiş meta verilerle PDF\'i indirin',
    sv: 'Ladda ner PDF-filen med uppdaterad metadata',
    no: 'Last ned PDF-filen med oppdatert metadata',
    ja: '更新されたメタデータ付きPDFをダウンロード',
    hi: 'अद्यतन मेटाडेटा वाली PDF डाउनलोड करें',
    ar: 'قم بتنزيل PDF مع البيانات الوصفية المحدثة',
    fa: 'PDF با فراداده به‌روزرسانی‌شده را دانلود کنید',
    zh: '下载更新了元数据的PDF',
  },
  downloadExcel: {
    pl: 'Pobierz arkusz Excel',
    en: 'Download the Excel spreadsheet',
    de: 'Laden Sie die Excel-Tabelle herunter',
    es: 'Descargue la hoja de cálculo de Excel',
    fr: 'Téléchargez le tableur Excel',
    it: 'Scarica il foglio di calcolo Excel',
    pt: 'Baixe a planilha do Excel',
    is: 'Sæktu Excel töflureikninn',
    tr: 'Excel elektronik tablosunu indirin',
    sv: 'Ladda ner Excel-kalkylbladet',
    no: 'Last ned Excel-regnearket',
    ja: 'Excelスプレッドシートをダウンロード',
    hi: 'Excel स्प्रेडशीट डाउनलोड करें',
    ar: 'قم بتنزيل جدول بيانات Excel',
    fa: 'صفحه‌گسترده Excel را دانلود کنید',
    zh: '下载Excel电子表格',
  },
  downloadPdfDoc: {
    pl: 'Pobierz dokument PDF',
    en: 'Download the PDF document',
    de: 'Laden Sie das PDF-Dokument herunter',
    es: 'Descargue el documento PDF',
    fr: 'Téléchargez le document PDF',
    it: 'Scarica il documento PDF',
    pt: 'Baixe o documento PDF',
    is: 'Sæktu PDF skjalið',
    tr: 'PDF belgesini indirin',
    sv: 'Ladda ner PDF-dokumentet',
    no: 'Last ned PDF-dokumentet',
    ja: 'PDF文書をダウンロード',
    hi: 'PDF दस्तावेज़ डाउनलोड करें',
    ar: 'قم بتنزيل مستند PDF',
    fa: 'سند PDF را دانلود کنید',
    zh: '下载PDF文档',
  },
  downloadTxt: {
    pl: 'Pobierz plik tekstowy',
    en: 'Download the text file',
    de: 'Laden Sie die Textdatei herunter',
    es: 'Descargue el archivo de texto',
    fr: 'Téléchargez le fichier texte',
    it: 'Scarica il file di testo',
    pt: 'Baixe o arquivo de texto',
    is: 'Sæktu textaskrána',
    tr: 'Metin dosyasını indirin',
    sv: 'Ladda ner textfilen',
    no: 'Last ned tekstfilen',
    ja: 'テキストファイルをダウンロード',
    hi: 'टेक्स्ट फ़ाइल डाउनलोड करें',
    ar: 'قم بتنزيل الملف النصي',
    fa: 'فایل متنی را دانلود کنید',
    zh: '下载文本文件',
  },
  downloadHtml: {
    pl: 'Pobierz plik HTML',
    en: 'Download the HTML file',
    de: 'Laden Sie die HTML-Datei herunter',
    es: 'Descargue el archivo HTML',
    fr: 'Téléchargez le fichier HTML',
    it: 'Scarica il file HTML',
    pt: 'Baixe o arquivo HTML',
    is: 'Sæktu HTML skrána',
    tr: 'HTML dosyasını indirin',
    sv: 'Ladda ner HTML-filen',
    no: 'Last ned HTML-filen',
    ja: 'HTMLファイルをダウンロード',
    hi: 'HTML फ़ाइल डाउनलोड करें',
    ar: 'قم بتنزيل ملف HTML',
    fa: 'فایل HTML را دانلود کنید',
    zh: '下载HTML文件',
  },
  downloadSvg: {
    pl: 'Pobierz pliki SVG',
    en: 'Download the SVG files',
    de: 'Laden Sie die SVG-Dateien herunter',
    es: 'Descargue los archivos SVG',
    fr: 'Téléchargez les fichiers SVG',
    it: 'Scarica i file SVG',
    pt: 'Baixe os arquivos SVG',
    is: 'Sæktu SVG skrárnar',
    tr: 'SVG dosyalarını indirin',
    sv: 'Ladda ner SVG-filerna',
    no: 'Last ned SVG-filene',
    ja: 'SVGファイルをダウンロード',
    hi: 'SVG फ़ाइलें डाउनलोड करें',
    ar: 'قم بتنزيل ملفات SVG',
    fa: 'فایل‌های SVG را دانلود کنید',
    zh: '下载SVG文件',
  },
  downloadEpub: {
    pl: 'Pobierz e-book EPUB',
    en: 'Download the EPUB ebook',
    de: 'Laden Sie das EPUB-E-Book herunter',
    es: 'Descargue el libro electrónico EPUB',
    fr: 'Téléchargez l\'ebook EPUB',
    it: 'Scarica l\'ebook EPUB',
    pt: 'Baixe o e-book EPUB',
    is: 'Sæktu EPUB rafbókina',
    tr: 'EPUB e-kitabını indirin',
    sv: 'Ladda ner EPUB e-boken',
    no: 'Last ned EPUB e-boken',
    ja: 'EPUB電子書籍をダウンロード',
    hi: 'EPUB ई-बुक डाउनलोड करें',
    ar: 'قم بتنزيل الكتاب الإلكتروني EPUB',
    fa: 'کتاب الکترونیکی EPUB را دانلود کنید',
    zh: '下载EPUB电子书',
  },
  downloadPptx: {
    pl: 'Pobierz prezentację PowerPoint',
    en: 'Download the PowerPoint presentation',
    de: 'Laden Sie die PowerPoint-Präsentation herunter',
    es: 'Descargue la presentación de PowerPoint',
    fr: 'Téléchargez la présentation PowerPoint',
    it: 'Scarica la presentazione PowerPoint',
    pt: 'Baixe a apresentação do PowerPoint',
    is: 'Sæktu PowerPoint kynninguna',
    tr: 'PowerPoint sunumunu indirin',
    sv: 'Ladda ner PowerPoint-presentationen',
    no: 'Last ned PowerPoint-presentasjonen',
    ja: 'PowerPointプレゼンテーションをダウンロード',
    hi: 'PowerPoint प्रस्तुति डाउनलोड करें',
    ar: 'قم بتنزيل عرض PowerPoint التقديمي',
    fa: 'ارائه PowerPoint را دانلود کنید',
    zh: '下载PowerPoint演示文稿',
  },
  downloadOdt: {
    pl: 'Pobierz dokument OpenOffice',
    en: 'Download the OpenOffice document',
    de: 'Laden Sie das OpenOffice-Dokument herunter',
    es: 'Descargue el documento de OpenOffice',
    fr: 'Téléchargez le document OpenOffice',
    it: 'Scarica il documento OpenOffice',
    pt: 'Baixe o documento do OpenOffice',
    is: 'Sæktu OpenOffice skjalið',
    tr: 'OpenOffice belgesini indirin',
    sv: 'Ladda ner OpenOffice-dokumentet',
    no: 'Last ned OpenOffice-dokumentet',
    ja: 'OpenOffice文書をダウンロード',
    hi: 'OpenOffice दस्तावेज़ डाउनलोड करें',
    ar: 'قم بتنزيل مستند OpenOffice',
    fa: 'سند OpenOffice را دانلود کنید',
    zh: '下载OpenOffice文档',
  },
  downloadFlattenedPdf: {
    pl: 'Pobierz spłaszczony plik PDF',
    en: 'Download the flattened PDF',
    de: 'Laden Sie die geglättete PDF herunter',
    es: 'Descargue el PDF aplanado',
    fr: 'Téléchargez le PDF aplati',
    it: 'Scarica il PDF appiattito',
    pt: 'Baixe o PDF achatado',
    is: 'Sæktu fletju PDF skrána',
    tr: 'Düzleştirilmiş PDF\'i indirin',
    sv: 'Ladda ner den platta PDF-filen',
    no: 'Last ned den flatlagte PDF-filen',
    ja: 'フラット化されたPDFをダウンロード',
    hi: 'समतल की गई PDF डाउनलोड करें',
    ar: 'قم بتنزيل PDF المسطح',
    fa: 'PDF مسطح‌شده را دانلود کنید',
    zh: '下载压平后的PDF',
  },
  downloadReport: {
    pl: 'Pobierz raport porównania',
    en: 'Download the comparison report',
    de: 'Laden Sie den Vergleichsbericht herunter',
    es: 'Descargue el informe de comparación',
    fr: 'Téléchargez le rapport de comparaison',
    it: 'Scarica il rapporto di confronto',
    pt: 'Baixe o relatório de comparação',
    is: 'Sæktu samanburðarskýrsluna',
    tr: 'Karşılaştırma raporunu indirin',
    sv: 'Ladda ner jämförelserapporten',
    no: 'Last ned sammenligningsrapporten',
    ja: '比較レポートをダウンロード',
    hi: 'तुलना रिपोर्ट डाउनलोड करें',
    ar: 'قم بتنزيل تقرير المقارنة',
    fa: 'گزارش مقایسه را دانلود کنید',
    zh: '下载比较报告',
  },
  downloadFilledPdf: {
    pl: 'Pobierz wypełniony plik PDF',
    en: 'Download the filled PDF',
    de: 'Laden Sie das ausgefüllte PDF herunter',
    es: 'Descargue el PDF completado',
    fr: 'Téléchargez le PDF rempli',
    it: 'Scarica il PDF compilato',
    pt: 'Baixe o PDF preenchido',
    is: 'Sæktu útfylltu PDF skrána',
    tr: 'Doldurulmuş PDF\'i indirin',
    sv: 'Ladda ner den ifyllda PDF-filen',
    no: 'Last ned den utfylte PDF-filen',
    ja: '入力済みPDFをダウンロード',
    hi: 'भरी गई PDF डाउनलोड करें',
    ar: 'قم بتنزيل PDF المملوء',
    fa: 'PDF پر شده را دانلود کنید',
    zh: '下载已填写的PDF',
  },
  downloadPdfa: {
    pl: 'Pobierz dokument PDF/A',
    en: 'Download the PDF/A document',
    de: 'Laden Sie das PDF/A-Dokument herunter',
    es: 'Descargue el documento PDF/A',
    fr: 'Téléchargez le document PDF/A',
    it: 'Scarica il documento PDF/A',
    pt: 'Baixe o documento PDF/A',
    is: 'Sæktu PDF/A skjalið',
    tr: 'PDF/A belgesini indirin',
    sv: 'Ladda ner PDF/A-dokumentet',
    no: 'Last ned PDF/A-dokumentet',
    ja: 'PDF/A文書をダウンロード',
    hi: 'PDF/A दस्तावेज़ डाउनलोड करें',
    ar: 'قم بتنزيل مستند PDF/A',
    fa: 'سند PDF/A را دانلود کنید',
    zh: '下载PDF/A文档',
  },
  downloadRedactedPdf: {
    pl: 'Pobierz zeredagowany plik PDF',
    en: 'Download the redacted PDF',
    de: 'Laden Sie die geschwärzte PDF herunter',
    es: 'Descargue el PDF redactado',
    fr: 'Téléchargez le PDF caviardé',
    it: 'Scarica il PDF oscurato',
    pt: 'Baixe o PDF redigido',
    is: 'Sæktu raðaðri PDF skrána',
    tr: 'Redakte edilmiş PDF\'i indirin',
    sv: 'Ladda ner den redigerade PDF-filen',
    no: 'Last ned den redigerte PDF-filen',
    ja: '墨消しされたPDFをダウンロード',
    hi: 'रिडैक्ट की गई PDF डाउनलोड करें',
    ar: 'قم بتنزيل PDF المنقح',
    fa: 'PDF ویرایش‌امن‌شده را دانلود کنید',
    zh: '下载已编辑的PDF',
  },
  downloadSignedPdfFinal: {
    pl: 'Pobierz podpisany plik PDF',
    en: 'Download the signed PDF',
    de: 'Laden Sie die signierte PDF herunter',
    es: 'Descargue el PDF firmado',
    fr: 'Téléchargez le PDF signé',
    it: 'Scarica il PDF firmato',
    pt: 'Baixe o PDF assinado',
    is: 'Sæktu undirrituðu PDF skrána',
    tr: 'İmzalanmış PDF\'i indirin',
    sv: 'Ladda ner den signerade PDF-filen',
    no: 'Last ned den signerte PDF-filen',
    ja: '署名されたPDFをダウンロード',
    hi: 'हस्ताक्षरित PDF डाउनलोड करें',
    ar: 'قم بتنزيل PDF الموقع',
    fa: 'PDF امضا شده را دانلود کنید',
    zh: '下载已签名的PDF',
  },
  downloadWebPdf: {
    pl: 'Pobierz PDF strony internetowej',
    en: 'Download the PDF of the web page',
    de: 'Laden Sie das PDF der Webseite herunter',
    es: 'Descargue el PDF de la página web',
    fr: 'Téléchargez le PDF de la page web',
    it: 'Scarica il PDF della pagina web',
    pt: 'Baixe o PDF da página da web',
    is: 'Sæktu PDF vefsíðunnar',
    tr: 'Web sayfasının PDF\'ini indirin',
    sv: 'Ladda ner PDF-filen av webbsidan',
    no: 'Last ned PDF-en av nettsiden',
    ja: 'WebページのPDFをダウンロード',
    hi: 'वेब पेज का PDF डाउनलोड करें',
    ar: 'قم بتنزيل PDF لصفحة الويب',
    fa: 'PDF صفحه وب را دانلود کنید',
    zh: '下载网页的PDF',
  },

  // --- View / Read steps ---
  viewDifferences: {
    pl: 'Zobacz różnice między plikami',
    en: 'View the differences between files',
    de: 'Zeigen Sie die Unterschiede zwischen Dateien an',
    es: 'Vea las diferencias entre archivos',
    fr: 'Visualisez les différences entre les fichiers',
    it: 'Visualizza le differenze tra i file',
    pt: 'Veja as diferenças entre os arquivos',
    is: 'Skoðaðu muninn á skrám',
    tr: 'Dosyalar arasındaki farkları görüntüleyin',
    sv: 'Visa skillnaderna mellan filer',
    no: 'Se forskjellene mellom filene',
    ja: 'ファイル間の差分を表示',
    hi: 'फ़ाइलों के बीच अंतर देखें',
    ar: 'عرض الاختلافات بين الملفات',
    fa: 'تفاوت‌های بین فایل‌ها را مشاهده کنید',
    zh: '查看文件之间的差异',
  },
  askQuestions: {
    pl: 'Zadawaj pytania dotyczące treści dokumentu',
    en: 'Ask questions about the document content',
    de: 'Stellen Sie Fragen zum Dokumentinhalt',
    es: 'Haga preguntas sobre el contenido del documento',
    fr: 'Posez des questions sur le contenu du document',
    it: 'Fai domande sul contenuto del documento',
    pt: 'Faça perguntas sobre o conteúdo do documento',
    is: 'Spyrðu spurninga um efni skjalsins',
    tr: 'Belge içeriği hakkında sorular sorun',
    sv: 'Ställ frågor om dokumentinnehållet',
    no: 'Still spørsmål om dokumentinnholdet',
    ja: '文書の内容について質問する',
    hi: 'दस्तावेज़ की सामग्री के बारे में प्रश्न पूछें',
    ar: 'اطرح أسئلة حول محتوى المستند',
    fa: 'در مورد محتوای سند سؤال بپرسید',
    zh: '就文档内容提问',
  },
  readSummary: {
    pl: 'Przeczytaj streszczenie wygenerowane przez AI',
    en: 'Read the AI-generated summary',
    de: 'Lesen Sie die KI-generierte Zusammenfassung',
    es: 'Lea el resumen generado por IA',
    fr: 'Lisez le résumé généré par l\'IA',
    it: 'Leggi il riassunto generato dall\'IA',
    pt: 'Leia o resumo gerado por IA',
    is: 'Lestu AI-framleitt samantekt',
    tr: 'Yapay zeka tarafından oluşturulan özeti okuyun',
    sv: 'Läs den AI-genererade sammanfattningen',
    no: 'Les AI-generert oppsummering',
    ja: 'AI生成の要約を読む',
    hi: 'AI-जनित सारांश पढ़ें',
    ar: 'اقرأ الملخص الذي تم إنشاؤه بواسطة الذكاء الاصطناعي',
    fa: 'خلاصه تولیدشده توسط هوش مصنوعی را بخوانید',
    zh: '阅读AI生成的摘要',
  },
  receiveAnswers: {
    pl: 'Otrzymuj odpowiedzi wygenerowane przez AI',
    en: 'Receive AI-generated answers',
    de: 'Erhalten Sie KI-generierte Antworten',
    es: 'Reciba respuestas generadas por IA',
    fr: 'Recevez des réponses générées par l\'IA',
    it: 'Ricevi risposte generate dall\'IA',
    pt: 'Receba respostas geradas por IA',
    is: 'Fáðu AI-framleidd svör',
    tr: 'Yapay zeka tarafından oluşturulan yanıtları alın',
    sv: 'Få AI-genererade svar',
    no: 'Få AI-genererte svar',
    ja: 'AI生成の回答を受け取る',
    hi: 'AI-जनित उत्तर प्राप्त करें',
    ar: 'تلقي إجابات تم إنشاؤها بواسطة الذكاء الاصطناعي',
    fa: 'پاسخ‌های تولیدشده توسط هوش مصنوعی را دریافت کنید',
    zh: '接收AI生成的答案',
  },
  getAiAnswers: {
    pl: 'Otrzymuj odpowiedzi wygenerowane przez AI',
    en: 'Receive AI-generated answers',
    de: 'Erhalten Sie KI-generierte Antworten',
    es: 'Reciba respuestas generadas por IA',
    fr: 'Recevez des réponses générées par l\'IA',
    it: 'Ricevi risposte generate dall\'IA',
    pt: 'Receba respostas geradas por IA',
    is: 'Fáðu AI-framleidd svör',
    tr: 'Yapay zeka tarafından oluşturulan yanıtları alın',
    sv: 'Få AI-genererade svar',
    no: 'Få AI-genererte svar',
    ja: 'AI生成の回答を受け取る',
    hi: 'AI-जनित उत्तर प्राप्त करें',
    ar: 'تلقي إجابات تم إنشاؤها بواسطة الذكاء الاصطناعي',
    fa: 'پاسخ‌های تولیدشده توسط هوش مصنوعی را دریافت کنید',
    zh: '接收AI生成的答案',
  },
  clickUnlockBtn: {
    pl: 'Kliknij przycisk odblokowania',
    en: 'Click the unlock button',
    de: 'Klicken Sie auf die Schaltfläche Entsperren',
    es: 'Haga clic en el botón Desbloquear',
    fr: 'Cliquez sur le bouton Déverrouiller',
    it: 'Clicca sul pulsante Sblocca',
    pt: 'Clique no botão Desbloquear',
    is: 'Smelltu á aflæsa hnappinn',
    tr: 'Kilidi Aç düğmesine tıklayın',
    sv: 'Klicka på knappen Lås upp',
    no: 'Klikk på lås opp-knappen',
    ja: 'ロック解除ボタンをクリック',
    hi: 'अनलॉक बटन पर क्लिक करें',
    ar: 'انقر على زر إلغاء القفل',
    fa: 'روی دکمه باز کردن قفل کلیک کنید',
    zh: '点击解锁按钮',
  },
};

type StepRef = string;

const toolSteps: Record<string, StepRef[][]> = {
  merge: [
    ['uploadPdf'], ['arrangeOrder'], ['clickMerge'], ['downloadMergedPdf'],
  ],
  split: [
    ['uploadPdfSplit'], ['selectSplitMode'], ['clickSplit'], ['downloadIndividualPdfs'],
  ],
  compress: [
    ['uploadPdfCompress'], ['selectCompression'], ['clickCompress'], ['downloadCompressedPdf'],
  ],
  'pdf-to-word': [
    ['uploadPdfConvert'], ['waitConversion'], ['downloadWord'],
  ],
  'word-to-pdf': [
    ['uploadWord'], ['waitConversion'], ['downloadPdfDoc'],
  ],
  'pdf-to-images': [
    ['uploadPdfConvert'], ['selectImageFormat'], ['clickConvert'], ['downloadZip'],
  ],
  'jpg-to-pdf': [
    ['uploadJpg'], ['arrangeImages'], ['adjustPageSize'], ['clickConvert'],
  ],
  'protect-pdf': [
    ['uploadPdfProtect'], ['enterPassword'], ['clickProtect'], ['downloadProtectedPdf'],
  ],
  'unlock-pdf': [
    ['uploadPasswordPdf'], ['enterPasswordForUnlock'], ['clickUnlock'], ['downloadUnlockedPdf'],
  ],
  'rotate-pdf': [
    ['uploadPdf'], ['selectRotation'], ['clickRotate'], ['downloadRotatedPdf'],
  ],
  'page-numbers': [
    ['uploadPdf'], ['enterPosition'], ['clickAddNumbers'], ['downloadNumberedPdf'],
  ],
  'watermark-pdf': [
    ['uploadPdf'], ['customizeWatermark'], ['clickAddWatermark'], ['downloadWatermarkedPdf'],
  ],
  'ocr-pdf': [
    ['uploadScanned'], ['selectLanguage'], ['clickOcr'], ['downloadOcrPdf'],
  ],
  'extract-pages': [
    ['uploadPdf'], ['selectPagesExtract'], ['clickExtract'], ['downloadExtractedPdf'],
  ],
  'delete-pages': [
    ['uploadPdf'], ['selectPagesDelete'], ['clickDelete'], ['downloadWithoutPages'],
  ],
  'reorder-pages': [
    ['uploadPdf'], ['dragReorder'], ['clickReorder'], ['downloadReorderedPdf'],
  ],
  'crop-pdf': [
    ['uploadPdf'], ['setMargins'], ['clickCrop'], ['downloadCroppedPdf'],
  ],
  'add-page': [
    ['uploadPdf'], ['clickAddPage'], ['downloadWithBlankPage'],
  ],
  metadata: [
    ['uploadPdf'], ['editMetadata'], ['clickSave'], ['downloadMetaPdf'],
  ],
  'edit-pdf': [
    ['uploadPdfEdit'], ['addTextAnnotations'], ['clickSaveEdit'], ['downloadEditedPdf'],
  ],
  'sign-pdf': [
    ['uploadPdfSign'], ['drawSignature'], ['placeSignature'], ['downloadSignedPdf'],
  ],
  'pdf-to-excel': [
    ['uploadTabularPdf'], ['waitExtraction'], ['downloadExcel'],
  ],
  'excel-to-pdf': [
    ['uploadExcel'], ['waitConversion'], ['downloadPdfDoc'],
  ],
  'pdf-to-txt': [
    ['uploadPdfConvert'], ['waitExtraction'], ['downloadTxt'],
  ],
  'html-to-pdf': [
    ['uploadHtml'], ['customizePdfOptions'], ['clickConvert'], ['downloadPdfDoc'],
  ],
  'url-to-pdf': [
    ['enterUrl'], ['clickConvert'], ['downloadWebPdf'],
  ],
  'pdf-to-html': [
    ['uploadPdfConvert'], ['waitConversion'], ['downloadHtml'],
  ],
  'flatten-pdf': [
    ['uploadAnnotatedPdf'], ['clickFlatten'], ['downloadFlattenedPdf'],
  ],
  'pdf-to-powerpoint': [
    ['uploadPdfConvert'], ['waitConversion'], ['downloadPptx'],
  ],
  'pdf-to-svg': [
    ['uploadPdfConvert'], ['waitSvgConversion'], ['downloadSvg'],
  ],
  'redact-pdf': [
    ['uploadPdf'], ['selectPagesRedact'], ['clickRedact'], ['downloadRedactedPdf'],
  ],
  'pdf-to-epub': [
    ['uploadPdfConvert'], ['waitEpubConversion'], ['downloadEpub'],
  ],
  'to-pdfa': [
    ['uploadPdf'], ['clickConvert'], ['downloadPdfa'],
  ],
  'fill-form': [
    ['uploadFormPdf'], ['fillFields'], ['clickFill'], ['downloadFilledPdf'],
  ],
  'openoffice-to-pdf': [
    ['uploadOdt'], ['waitConversion'], ['downloadPdfDoc'],
  ],
  'pdf-to-openoffice': [
    ['uploadPdfConvert'], ['waitConversion'], ['downloadOdt'],
  ],
  'compare-pdf': [
    ['uploadTwoPdfs'], ['clickCompare'], ['viewDifferences'], ['downloadReport'],
  ],
  'ai-chat': [
    ['uploadPdfConvert'], ['waitAnalysis'], ['askQuestions'], ['getAiAnswers'],
  ],
  'ai-summary': [
    ['uploadPdfConvert'], ['clickSummarize'], ['readSummary'],
  ],
};

export default function SchemaHowTo({ locale: forcedLocale }: { locale?: Locale }) {
  const pathname = usePathname();
  const locale = forcedLocale ?? useHydrationSafeLocale();
  const segment = pathname.split('/').filter(Boolean)[0];
  const key = keyBySlug[segment];
  if (!key || !toolSteps[segment]) return null;

  const name = t(`tool.${key}`, locale);
  const description = t(`desc.${key}`, locale);
  const url = `https://optimapdf.com/${segment}`;
  const steps = toolSteps[segment];

  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'HowTo',
    name,
    description,
    url,
    image: 'https://optimapdf.com/icon-512.svg',
    estimatedCost: { '@type': 'MonetaryAmount', currency: 'PLN', value: '0' },
    supply: { '@type': 'HowToSupply', name: tr({ pl: 'Plik PDF', en: 'PDF file' }, locale) },
    tool: { '@type': 'HowToTool', name: 'OptimaPDF' },
    step: steps.map((refs, i) => {
      const text = refs.map(ref => tr(L[ref], locale)).join(' ');
      return {
        '@type': 'HowToStep',
        position: i + 1,
        name: text,
        text,
        url: `${url}#step-${i + 1}`,
      };
    }),
    inLanguage: locale,
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
    />
  );
}