import type { GuideArticle } from '@/types/guide';

const article: GuideArticle = {
  slug: 'how-to-convert-pdf-to-word',
  category: 'pdf-to-word',
  title: {
    pl: 'Jak przekonwertować PDF do Worda',
    en: 'How to Convert PDF to Word',
    de: 'Wie man PDF in Word konvertiert',
    es: 'Cómo convertir PDF a Word',
    fr: 'Comment convertir un PDF en Word',
    it: 'Come convertire PDF in Word',
    pt: 'Como converter PDF para Word',
    sv: 'Hur man konverterar PDF till Word',
    no: 'Hvordan konvertere PDF til Word',
    is: 'Hvernig á að umbreyta PDF í Word',
    tr: 'PDF Word\'e nasıl dönüştürülür',
    ar: 'كيفية تحويل PDF إلى Word',
    fa: 'چگونه PDF را به Word تبدیل کنیم',
    hi: 'PDF को Word में कैसे बदलें',
    ja: 'PDFをWordに変換する方法',
    zh: '如何将PDF转换为Word',
  },
  excerpt: {
    pl: 'Dowiedz się, jak zamienić plik PDF na edytowalny dokument Word (DOCX). Darmowe narzędzie online — konwersja w przeglądarce, bez wysyłania plików.',
    en: 'Learn how to convert a PDF file to an editable Word document (DOCX). Free online tool — conversion in your browser, no file upload.',
    de: 'Erfahren Sie, wie Sie eine PDF-Datei in ein bearbeitbares Word-Dokument konvertieren. Kostenloses Online-Tool — Konvertierung im Browser.',
    es: 'Aprenda a convertir un archivo PDF a un documento de Word editable. Herramienta gratuita online — conversión en el navegador.',
    fr: 'Apprenez à convertir un fichier PDF en document Word modifiable. Outil en ligne gratuit — conversion dans le navigateur.',
    it: 'Impara a convertire un file PDF in un documento Word modificabile. Strumento online gratuito — conversione nel browser.',
    pt: 'Aprenda a converter um ficheiro PDF para um documento Word editável. Ferramenta online gratuita — conversão no navegador.',
    sv: 'Lär dig konvertera en PDF-fil till ett redigerbart Word-dokument. Gratis onlineverktyg — konvertering i webbläsaren.',
    no: 'Lær hvordan du konverterer en PDF-fil til et redigerbart Word-dokument. Gratis onlineverktøy — konvertering i nettleseren.',
    is: 'Lærðu hvernig á að umbreyta PDF skrá í breytanlegt Word skjal. Ókeypis nettól — umbreyting í vafranum.',
    tr: 'Bir PDF dosyasını düzenlenebilir bir Word belgesine nasıl dönüştüreceğinizi öğrenin. Ücretsiz çevrimiçi araç — tarayıcıda dönüştürme.',
    ar: 'تعلم كيفية تحويل ملف PDF إلى مستند Word قابل للتحرير. أداة مجانية عبر الإنترنت — تحويل في المتصفح.',
    fa: 'بیاموزید چگونه یک فایل PDF را به سند Word قابل ویرایش تبدیل کنید. ابزار رایگان آنلاین — تبدیل در مرورگر.',
    hi: 'PDF फ़ाइल को संपादन योग्य Word दस्तावेज़ में बदलना सीखें। मुफ़्त ऑनलाइन उपकरण — ब्राउज़र में रूपांतरण।',
    ja: 'PDFファイルを編集可能なWord文書に変換する方法を学びます。無料のオンラインツール — ブラウザ内で変換。',
    zh: '了解如何将PDF文件转换为可编辑的Word文档。免费在线工具 — 在浏览器中完成转换。',
  },
  body: [
    { type: 'paragraph', text: {
      pl: 'Konwersja PDF do Worda to jedno z najpopularniejszych narzędzi. Przydaje się, gdy otrzymałeś plik PDF i potrzebujesz edytować jego treść — zmienić tekst, poprawić formatowanie lub dodać akapity. OptimaPDF konwertuje PDF do DOCX w całości w przeglądarce.',
      en: 'PDF to Word conversion is one of the most popular tools. It\'s useful when you receive a PDF file and need to edit its content — change text, fix formatting or add paragraphs. OptimaPDF converts PDF to DOCX entirely in your browser.',
      de: 'PDF-zu-Word-Konvertierung ist eines der beliebtesten Werkzeuge. Nützlich, wenn Sie ein PDF erhalten und dessen Inhalt bearbeiten müssen.',
      es: 'La conversión de PDF a Word es una de las herramientas más populares. Útil cuando recibes un PDF y necesitas editar su contenido.',
      fr: 'La conversion PDF en Word est l\'un des outils les plus populaires. Utile lorsque vous recevez un PDF et devez modifier son contenu.',
      it: 'La conversione da PDF a Word è uno degli strumenti più popolari. Utile quando ricevi un PDF e devi modificarne il contenuto.',
      pt: 'A conversão de PDF para Word é uma das ferramentas mais populares. Útil quando recebe um PDF e precisa de editar o seu conteúdo.',
      sv: 'PDF till Word-konvertering är ett av de mest populära verktygen. Användbart när du får en PDF och behöver redigera innehållet.',
      no: 'PDF til Word-konvertering er et av de mest populære verktøyene. Nyttig når du mottar en PDF og trenger å redigere innholdet.',
      is: 'PDF í Word umbreyting er eitt vinsælasta tólið. Gagnlegt þegar þú færð PDF og þarft að breyta innihaldinu.',
      tr: 'PDF\'den Word\'e dönüştürme en popüler araçlardan biridir. Bir PDF aldığınızda ve içeriğini düzenlemeniz gerektiğinde kullanışlıdır.',
      ar: 'تحويل PDF إلى Word هو أحد أكثر الأدوات شيوعًا. مفيد عندما تتلقى ملف PDF وتحتاج إلى تعديل محتواه.',
      fa: 'تبدیل PDF به Word یکی از محبوب‌ترین ابزارها است. زمانی مفید است که یک PDF دریافت می‌کنید و نیاز به ویرایش محتوای آن دارید.',
      hi: 'PDF से Word रूपांतरण सबसे लोकप्रिय उपकरणों में से एक है। यह तब उपयोगी होता है जब आपको PDF फ़ाइल मिलती है और आपको इसकी सामग्री संपादित करने की आवश्यकता होती है।',
      ja: 'PDFからWordへの変換は、最も人気のあるツールの1つです。PDFファイルを受け取り、その内容を編集する必要がある場合に便利です。',
      zh: 'PDF转Word是最受欢迎的工具之一。当您收到PDF文件并需要编辑其内容时非常有用。',
    }},
    { type: 'cta', tool: 'word' },
    { type: 'heading', level: 2, text: {
      pl: 'Jak przekonwertować PDF do Worda krok po kroku',
      en: 'How to Convert PDF to Word Step by Step',
      de: 'Schritt-für-Schritt-Anleitung zur PDF-zu-Word-Konvertierung',
      es: 'Cómo convertir PDF a Word paso a paso',
      fr: 'Comment convertir un PDF en Word étape par étape',
      it: 'Come convertire PDF in Word passo dopo passo',
      pt: 'Como converter PDF para Word passo a passo',
      sv: 'Hur man konverterar PDF till Word steg för steg',
      no: 'Hvordan konvertere PDF til Word trinn for trinn',
      is: 'Hvernig á að umbreyta PDF í Word skref fyrir skref',
      tr: 'PDF Adım Adım Word\'e Nasıl Dönüştürülür',
      ar: 'كيفية تحويل PDF إلى Word خطوة بخطوة',
      fa: 'نحوه تبدیل PDF به Word گام به گام',
      hi: 'चरण दर चरण PDF को Word में कैसे बदलें',
      ja: 'ステップバイステップでPDFをWordに変換する方法',
      zh: '如何逐步将PDF转换为Word',
    }},
    { type: 'step', title: {
      pl: 'Przeciągnij plik PDF',
      en: 'Drop the PDF File',
      de: 'PDF-Datei ablegen',
      es: 'Arrastre el archivo PDF',
      fr: 'Déposez le fichier PDF',
      it: 'Trascina il file PDF',
      pt: 'Arraste o ficheiro PDF',
      sv: 'Släpp PDF-filen',
      no: 'Slipp PDF-filen',
      is: 'Slepptu PDF skránni',
      tr: 'PDF dosyasını bırakın',
      ar: 'أسقط ملف PDF',
      fa: 'فایل PDF را رها کنید',
      hi: 'PDF फ़ाइल छोड़ें',
      ja: 'PDFファイルをドロップ',
      zh: '放入PDF文件',
    }, text: {
      pl: 'Przeciągnij plik PDF w pole wyboru lub kliknij, aby wybrać go z dysku. Konwersja rozpoczyna się automatycznie po dodaniu pliku.',
      en: 'Drag the PDF file into the upload area or click to select it from your disk. The conversion starts automatically after adding the file.',
      de: 'Ziehen Sie die PDF-Datei in den Upload-Bereich oder klicken Sie zur Auswahl. Die Konvertierung beginnt automatisch.',
      es: 'Arrastre el PDF al área de carga o haga clic para seleccionarlo. La conversión comienza automáticamente.',
      fr: 'Glissez le PDF dans la zone de téléchargement ou cliquez pour le sélectionner. La conversion démarre automatiquement.',
      it: 'Trascina il PDF nell\'area di caricamento o clicca per selezionarlo. La conversione inizia automaticamente.',
      pt: 'Arraste o PDF para a área de carregamento ou clique para o selecionar. A conversão começa automaticamente.',
      sv: 'Dra PDF-filen till uppladdningsområdet eller klicka för att välja den. Konverteringen startar automatiskt.',
      no: 'Dra PDF-filen til opplastingsområdet eller klikk for å velge den. Konverteringen starter automatisk.',
      is: 'Dragðu PDF skránni á hleðslusvæðið eða smelltu til að velja hana. Umbreytingin hefst sjálfkrafa.',
      tr: 'PDF dosyasını yükleme alanına sürükleyin veya tıklayarak seçin. Dönüştürme dosya eklendikten sonra otomatik olarak başlar.',
      ar: 'اسحب ملف PDF إلى منطقة التحميل أو انقر لتحديده. يبدأ التحويل تلقائيًا.',
      fa: 'فایل PDF را به منطقه بارگذاری بکشید یا کلیک کنید تا آن را انتخاب کنید. تبدیل پس از افزودن فایل به طور خودکار شروع می‌شود.',
      hi: 'PDF फ़ाइल को अपलोड क्षेत्र में खींचें या अपनी डिस्क से चुनने के लिए क्लिक करें। फ़ाइल जोड़ने के बाद रूपांतरण स्वचालित रूप से शुरू हो जाता है।',
      ja: 'PDFファイルをアップロードエリアにドラッグするか、クリックして選択します。ファイルを追加すると変換が自動的に開始されます。',
      zh: '将PDF文件拖放到上传区域，或单击从磁盘中选择。添加文件后转换将自动开始。',
    }},
    { type: 'step', title: {
      pl: 'Poczekaj na konwersję',
      en: 'Wait for the Conversion',
      de: 'Warten Sie auf die Konvertierung',
      es: 'Espere a que se complete la conversión',
      fr: 'Attendez la fin de la conversion',
      it: 'Attendi la conversione',
      pt: 'Aguarde pela conversão',
      sv: 'Vänta på konverteringen',
      no: 'Vent på konverteringen',
      is: 'Bíddu eftir umbreytingunni',
      tr: 'Dönüşümü bekleyin',
      ar: 'انتظر حتى اكتمال التحويل',
      fa: 'منتظر تبدیل بمانید',
      hi: 'रूपांतरण की प्रतीक्षा करें',
      ja: '変換が完了するまで待機',
      zh: '等待转换完成',
    }, text: {
      pl: 'Konwersja trwa zwykle kilka sekund. Plik DOCX zostanie pobrany automatycznie. Otwórz go w Wordzie, LibreOffice lub Google Docs, aby edytować treść.',
      en: 'The conversion usually takes a few seconds. The DOCX file will be downloaded automatically. Open it in Word, LibreOffice or Google Docs to edit the content.',
      de: 'Die Konvertierung dauert in der Regel einige Sekunden. Die DOCX-Datei wird automatisch heruntergeladen. Öffnen Sie sie in Word, LibreOffice oder Google Docs.',
      es: 'La conversión suele tardar unos segundos. El archivo DOCX se descargará automáticamente. Ábralo en Word, LibreOffice o Google Docs.',
      fr: 'La conversion prend généralement quelques secondes. Le fichier DOCX sera téléchargé automatiquement. Ouvrez-le dans Word, LibreOffice ou Google Docs.',
      it: 'La conversione richiede solitamente alcuni secondi. Il file DOCX verrà scaricato automaticamente. Aprilo in Word, LibreOffice o Google Docs.',
      pt: 'A conversão normalmente leva alguns segundos. O ficheiro DOCX será descarregado automaticamente. Abra-o no Word, LibreOffice ou Google Docs.',
      sv: 'Konverteringen tar vanligtvis några sekunder. DOCX-filen laddas ner automatiskt. Öppna den i Word, LibreOffice eller Google Docs.',
      no: 'Konverteringen tar vanligvis noen sekunder. DOCX-filen lastes ned automatisk. Åpne den i Word, LibreOffice eller Google Docs.',
      is: 'Umbreytingin tekur venjulega nokkrar sekúndur. DOCX skráin verður sótt sjálfkrafa. Opnaðu hana í Word, LibreOffice eða Google Docs.',
      tr: 'Dönüştürme genellikle birkaç saniye sürer. DOCX dosyası otomatik olarak indirilecektir. İçeriği düzenlemek için Word, LibreOffice veya Google Docs\'ta açın.',
      ar: 'التحويل يستغرق عادة بضع ثوانٍ. سيتم تنزيل ملف DOCX تلقائيًا. افتحه في Word أو LibreOffice أو Google Docs لتحرير المحتوى.',
      fa: 'تبدیل معمولاً چند ثانیه طول می‌کشد. فایل DOCX به طور خودکار دانلود می‌شود. برای ویرایش محتوا آن را در Word، LibreOffice یا Google Docs باز کنید.',
      hi: 'रूपांतरण में आमतौर पर कुछ सेकंड लगते हैं। DOCX फ़ाइल स्वचालित रूप से डाउनलोड हो जाएगी। सामग्री संपादित करने के लिए इसे Word, LibreOffice या Google Docs में खोलें।',
      ja: '変換は通常数秒で完了します。DOCXファイルが自動的にダウンロードされます。Word、LibreOffice、Google Docsで開いて編集してください。',
      zh: '转换通常需要几秒钟。DOCX文件将自动下载。在Word、LibreOffice或Google Docs中打开以编辑内容。',
    }},
    { type: 'cta', tool: 'word' },
    { type: 'heading', level: 3, text: {
      pl: 'Wskazówki dotyczące konwersji',
      en: 'Conversion Tips',
      de: 'Konvertierungstipps',
      es: 'Consejos de conversión',
      fr: 'Conseils de conversion',
      it: 'Suggerimenti per la conversione',
      pt: 'Dicas de conversão',
      sv: 'Konverteringstips',
      no: 'Konverteringstips',
      is: 'Umbreytingarábendingar',
      tr: 'Dönüştürme İpuçları',
      ar: 'نصائح للتحويل',
      fa: 'نکات تبدیل',
      hi: 'रूपांतरण युक्तियाँ',
      ja: '変換のヒント',
      zh: '转换提示',
    }},
    { type: 'list', items: [
      { pl: 'Proste dokumenty tekstowe konwertują się najlepiej — zachowują formatowanie, listy i akapity', en: 'Simple text documents convert best — they retain formatting, lists and paragraphs', de: 'Einfache Textdokumente konvertieren am besten — sie behalten Formatierung, Listen und Absätze bei', es: 'Los documentos de texto simples se convierten mejor — conservan el formato, listas y párrafos', fr: 'Les documents texte simples se convertissent le mieux — ils conservent le formatage, les listes et les paragraphes', it: 'I documenti di testo semplici si convertono meglio — conservano formattazione, elenchi e paragrafi', pt: 'Documentos de texto simples convertem-se melhor — retêm formatação, listas e parágrafos', sv: 'Enkla textdokument konverteras bäst — de behåller formatering, listor och stycken', no: 'Enkle tekstdokument konverteres best — de beholder formatering, lister og avsnitt', is: 'Einföld textaskjöl umbreytast best — þau halda sniði, listum og efnisgreinum', tr: 'Basit metin belgeleri en iyi şekilde dönüşür — biçimlendirmeyi, listeleri ve paragrafları korurlar', ar: 'المستندات النصية البسيطة تتحول بشكل أفضل — تحتفظ بالتنسيق والقوائم والفقرات', fa: 'اسناد متنی ساده بهترین تبدیل را دارند — قالب‌بندی، لیست‌ها و پاراگراف‌ها را حفظ می‌کنند', hi: 'सरल टेक्स्ट दस्तावेज़ सबसे अच्छा रूपांतरित होते हैं — वे फ़ॉर्मेटिंग, सूचियां और पैराग्राफ बनाए रखते हैं', ja: 'シンプルなテキスト文書は最も変換品質が高く、書式、リスト、段落を保持します', zh: '简单的文本文档转换效果最好 — 它们保留格式、列表和段落' },
      { pl: 'Tabele i zaawansowane układy mogą wymagać ręcznej korekty w Wordzie po konwersji', en: 'Tables and complex layouts may need manual adjustment in Word after conversion', de: 'Tabellen und komplexe Layouts können nach der Konvertierung manuelle Anpassungen erfordern', es: 'Las tablas y diseños complejos pueden necesitar ajustes manuales en Word', fr: 'Les tableaux et mises en page complexes peuvent nécessiter un ajustement manuel dans Word', it: 'Tabelle e layout complessi potrebbero richiedere regolazioni manuali in Word', pt: 'Tabelas e layouts complexos podem necessitar de ajuste manual no Word', sv: 'Tabeller och komplexa layouter kan behöva manuell justering i Word', no: 'Tabeller og komplekse oppsett kan trenge manuell justering i Word', is: 'Töflur og flókin skipulag geta þurft handvirka aðlögun í Word', tr: 'Tablolar ve karmaşık düzenler, dönüştürmeden sonra Word\'de manuel ayar gerektirebilir', ar: 'الجداول والتخطيطات المعقدة قد تحتاج إلى تعديل يدوي في Word بعد التحويل', fa: 'جدول‌ها و طرح‌های پیچیده ممکن است پس از تبدیل نیاز به تنظیم دستی در Word داشته باشند', hi: 'तालिकाओं और जटिल लेआउट को रूपांतरण के बाद Word में मैन्युअल समायोजन की आवश्यकता हो सकती है', ja: '表や複雑なレイアウトは変換後にWordで手動調整が必要な場合があります', zh: '表格和复杂的布局在转换后可能需要在Word中进行手动调整' },
    ]},
    { type: 'cta', tool: 'word' },
  ],
  relatedTool: 'word',
  faq: [
    { q: {
      pl: 'Czy konwersja zachowuje formatowanie?',
      en: 'Does the conversion preserve formatting?',
      de: 'Bleibt die Formatierung bei der Konvertierung erhalten?',
      es: '¿La conversión conserva el formato?',
      fr: 'La conversion préserve-t-elle le formatage ?',
      it: 'La conversione preserva la formattazione?',
      pt: 'A conversão preserva a formatação?',
      sv: 'Bevarar konverteringen formateringen?',
      no: 'Bevarer konverteringen formateringen?',
      is: 'Varðveitir umbreytingin sniðið?',
      tr: 'Dönüştürme biçimlendirmeyi korur mu?',
      ar: 'هل يحافظ التحويل على التنسيق؟',
      fa: 'آیا تبدیل قالب‌بندی را حفظ می‌کند؟',
      hi: 'क्या रूपांतरण फ़ॉर्मेटिंग को संरक्षित करता है?',
      ja: '変換は書式を保持しますか？',
      zh: '转换是否保留格式？',
    }, a: {
      pl: 'Tak, podstawowe formatowanie (krój czcionki, rozmiar, pogrubienie, kursywa, listy, akapity) jest zachowane. Tabele i zaawansowane układy graficzne mogą wymagać ręcznej korekty.',
      en: 'Yes, basic formatting (font, size, bold, italic, lists, paragraphs) is preserved. Tables and advanced graphic layouts may need manual adjustment.',
      de: 'Ja, die Grundformatierung bleibt erhalten. Tabellen und komplexe Layouts können manuelle Anpassungen erfordern.',
      es: 'Sí, el formato básico se conserva. Las tablas y diseños avanzados pueden necesitar ajustes.',
      fr: 'Oui, le formatage de base est conservé. Les tableaux et mises en page avancées peuvent nécessiter des ajustements.',
      it: 'Sì, la formattazione di base viene preservata. Tabelle e layout grafici avanzati potrebbero richiedere regolazioni.',
      pt: 'Sim, a formatação básica é preservada. Tabelas e layouts gráficos avançados podem necessitar de ajuste manual.',
      sv: 'Ja, grundläggande formatering bevaras. Tabeller och avancerade grafiska layouter kan behöva manuell justering.',
      no: 'Ja, grunnleggende formatering bevares. Tabeller og avanserte grafiske oppsett kan trenge manuell justering.',
      is: 'Já, grunnsnið er varðveitt. Töflur og háþróuð grafísk skipulag geta þurft handvirka aðlögun.',
      tr: 'Evet, temel biçimlendirme korunur. Tablolar ve gelişmiş grafik düzenler manuel ayar gerektirebilir.',
      ar: 'نعم، يتم الحفاظ على التنسيق الأساسي. الجداول والتخطيطات الرسومية المتقدمة قد تحتاج إلى تعديل يدوي.',
      fa: 'بله، قالب‌بندی پایه حفظ می‌شود. جدول‌ها و طرح‌های گرافیکی پیشرفته ممکن است نیاز به تنظیم دستی داشته باشند.',
      hi: 'हाँ, बुनियादी फ़ॉर्मेटिंग संरक्षित रहती है। तालिकाओं और उन्नत ग्राफ़िक लेआउट को मैन्युअल समायोजन की आवश्यकता हो सकती है।',
      ja: 'はい、基本的な書式（フォント、サイズ、太字、斜体、リスト、段落）は保持されます。表や高度なグラフィックレイアウトは手動調整が必要な場合があります。',
      zh: '是的，基本格式（字体、大小、加粗、斜体、列表、段落）会保留。表格和高级图形布局可能需要手动调整。',
    }},
  ],
  canonicalOverride: undefined,
  publishedAt: '2025-06-25',
  updatedAt: '2025-07-02',
};

export default article;
