import type { GuideArticle } from '@/types/guide';

const article: GuideArticle = {
  slug: 'how-to-protect-pdf-online',
  category: 'protect-pdf',
  title: {
    pl: 'Jak zabezpieczyć PDF hasłem',
    en: 'How to Protect a PDF with a Password',
    de: 'Wie man eine PDF mit einem Passwort schützt',
    es: 'Cómo proteger un PDF con contraseña',
    fr: 'Comment protéger un PDF par mot de passe',
    it: 'Come proteggere un PDF con password',
    pt: 'Como proteger um PDF com palavra-passe',
    sv: 'Hur man skyddar en PDF med lösenord',
    no: 'Hvordan beskytte en PDF med passord',
    is: 'Hvernig á að vernda PDF með lykilorði',
    tr: 'Bir PDF nasıl şifre ile korunur',
    ar: 'كيفية حماية PDF بكلمة مرور',
    fa: 'چگونه یک PDF را با رمز عبور محافظت کنیم',
    hi: 'PDF को पासवर्ड से कैसे सुरक्षित करें',
    ja: 'PDFをパスワードで保護する方法',
    zh: '如何用密码保护PDF',
  },
  excerpt: {
    pl: 'Dodaj hasło do pliku PDF, aby chronić poufne dokumenty. Instrukcja krok po kroku — bez instalacji, w pełni lokalnie w przeglądarce.',
    en: 'Add a password to your PDF file to protect sensitive documents. Step-by-step guide — no installation, fully local in your browser.',
    de: 'Fügen Sie Ihrer PDF-Datei ein Passwort hinzu. Schritt-für-Schritt-Anleitung — ohne Installation, komplett lokal.',
    es: 'Añada una contraseña a su archivo PDF. Guía paso a paso — sin instalación, completamente local.',
    fr: 'Ajoutez un mot de passe à votre fichier PDF. Guide étape par étape — sans installation, entièrement local.',
    it: 'Aggiungi una password al tuo file PDF. Guida passo dopo passo — senza installazione, completamente locale.',
    pt: 'Adicione uma palavra-passe ao seu ficheiro PDF. Guia passo a passo — sem instalação, totalmente local.',
    sv: 'Lägg till ett lösenord till din PDF-fil. Steg-för-steg-guide — ingen installation, helt lokalt.',
    no: 'Legg til et passord på PDF-filen din. Trinn-for-trinn-guide — ingen installasjon, helt lokalt.',
    is: 'Bættu lykilorði við PDF skrána þína. Skref-fyrir-skref leiðbeining — engin uppsetning, alfarið staðbundið.',
    tr: 'Hassas belgeleri korumak için PDF dosyanıza şifre ekleyin. Adım adım kılavuz — kurulum gerekmez, tamamen yerel.',
    ar: 'أضف كلمة مرور إلى ملف PDF الخاص بك. دليل خطوة بخطوة — بدون تثبيت، محلي بالكامل.',
    fa: 'برای محافظت از اسناد حساس به فایل PDF خود رمز عبور اضافه کنید. راهنمای گام به گام — بدون نصب، کاملاً محلی.',
    hi: 'संवेदनशील दस्तावेज़ों की सुरक्षा के लिए अपनी PDF फ़ाइल में पासवर्ड जोड़ें। चरण-दर-चरण मार्गदर्शिका — बिना इंस्टॉलेशन, पूरी तरह से स्थानीय।',
    ja: '機密文書を保護するためにPDFファイルにパスワードを追加します。インストール不要、完全にブラウザ内で完結。',
    zh: '为PDF文件添加密码以保护敏感文档。分步指南 — 无需安装，完全在浏览器中本地完成。',
  },
  body: [
    { type: 'paragraph', text: {
      pl: 'Zabezpieczenie PDF hasłem to skuteczny sposób na ochronę poufnych dokumentów przed nieautoryzowanym dostępem. OptimaPDF używa szyfrowania AES-256, które jest obecnie standardem bezpieczeństwa. Wszystko dzieje się lokalnie w Twojej przeglądarce.',
      en: 'Password-protecting a PDF is an effective way to protect sensitive documents from unauthorized access. OptimaPDF uses AES-256 encryption, the current security standard. Everything happens locally in your browser.',
      de: 'Passwortschutz für PDFs ist eine effektive Methode, um vertrauliche Dokumente zu schützen. OptimaPDF verwendet AES-256-Verschlüsselung. Alles geschieht lokal in Ihrem Browser.',
      es: 'Proteger un PDF con contraseña es eficaz para proteger documentos confidenciales. OptimaPDF utiliza cifrado AES-256. Todo ocurre localmente en su navegador.',
      fr: 'Protéger un PDF par mot de passe est un moyen efficace de protéger les documents confidentiels. OptimaPDF utilise le chiffrement AES-256. Tout se passe localement dans votre navigateur.',
      it: 'Proteggere un PDF con password è un modo efficace per proteggere documenti riservati. OptimaPDF utilizza la crittografia AES-256. Tutto avviene localmente nel browser.',
      pt: 'Proteger um PDF com palavra-passe é uma forma eficaz de proteger documentos confidenciais. OptimaPDF usa encriptação AES-256. Tudo acontece localmente no seu navegador.',
      sv: 'Lösenordsskydd av en PDF är ett effektivt sätt att skydda känsliga dokument. OptimaPDF använder AES-256-kryptering. Allt sker lokalt i din webbläsare.',
      no: 'Passordbeskyttelse av en PDF er en effektiv måte å beskytte sensitive dokumenter på. OptimaPDF bruker AES-256-kryptering. Alt skjer lokalt i nettleseren din.',
      is: 'Lykilorðsverndun á PDF er áhrifarík leið til að vernda viðkvæm skjöl. OptimaPDF notar AES-256 dulkóðun. Allt gerist staðbundið í vafranum þínum.',
      tr: 'Bir PDF\'yi şifreyle korumak, hassas belgeleri yetkisiz erişime karşı korumanın etkili bir yoludur. OptimaPDF, AES-256 şifreleme kullanır. Her şey tarayıcınızda yerel olarak gerçekleşir.',
      ar: 'حماية PDF بكلمة مرور هي طريقة فعالة لحماية المستندات الحساسة. يستخدم OptimaPDF تشفير AES-256. كل شيء يحدث محليًا في متصفحك.',
      fa: 'محافظت از PDF با رمز عبور راهی مؤثر برای محافظت از اسناد حساس در برابر دسترسی غیرمجاز است. OptimaPDF از رمزنگاری AES-256 استفاده می‌کند.',
      hi: 'पासवर्ड से PDF की सुरक्षा करना संवेदनशील दस्तावेज़ों को अनधिकृत पहुंच से बचाने का एक प्रभावी तरीका है। OptimaPDF AES-256 एन्क्रिप्शन का उपयोग करता है।',
      ja: 'パスワードによるPDF保護は、機密文書を不正アクセスから守る効果的な方法です。OptimaPDFはAES-256暗号化を使用します。',
      zh: '用密码保护PDF是防止未经授权访问敏感文档的有效方法。OptimaPDF使用AES-256加密。一切都在浏览器中本地完成。',
    }},
    { type: 'cta', tool: 'protect' },
    { type: 'heading', level: 2, text: {
      pl: 'Jak zabezpieczyć PDF krok po kroku',
      en: 'How to Protect a PDF Step by Step',
      de: 'Schritt-für-Schritt-Anleitung zum Passwortschutz',
      es: 'Cómo proteger un PDF paso a paso',
      fr: 'Comment protéger un PDF étape par étape',
      it: 'Come proteggere un PDF passo dopo passo',
      pt: 'Como proteger um PDF passo a passo',
      sv: 'Hur man skyddar en PDF steg för steg',
      no: 'Hvordan beskytte en PDF trinn for trinn',
      is: 'Hvernig á að vernda PDF skref fyrir skref',
      tr: 'PDF Adım Adım Nasıl Korunur',
      ar: 'كيفية حماية PDF خطوة بخطوة',
      fa: 'نحوه محافظت از PDF گام به گام',
      hi: 'चरण दर चरण PDF कैसे सुरक्षित करें',
      ja: 'ステップバイステップでPDFを保護する方法',
      zh: '如何逐步保护PDF',
    }},
    { type: 'step', title: {
      pl: 'Wprowadź hasło',
      en: 'Enter a Password',
      de: 'Geben Sie ein Passwort ein',
      es: 'Introduzca una contraseña',
      fr: 'Entrez un mot de passe',
      it: 'Inserisci una password',
      pt: 'Introduza uma palavra-passe',
      sv: 'Ange ett lösenord',
      no: 'Skriv inn et passord',
      is: 'Sláðu inn lykilorð',
      tr: 'Bir şifre girin',
      ar: 'أدخل كلمة مرور',
      fa: 'یک رمز عبور وارد کنید',
      hi: 'एक पासवर्ड दर्ज करें',
      ja: 'パスワードを入力',
      zh: '输入密码',
    }, text: {
      pl: 'Wprowadź hasło, którym chcesz zabezpieczyć dokument. Minimalna długość to 6 znaków. Im dłuższe i bardziej złożone hasło, tym trudniej je złamać. Wskaźnik siły hasła pomoże Ci ocenić jego bezpieczeństwo.',
      en: 'Enter the password you want to use to secure the document. Minimum length is 6 characters. The longer and more complex the password, the harder it is to crack. The password strength meter helps you assess security.',
      de: 'Geben Sie das Passwort ein. Mindestlänge 6 Zeichen. Je länger und komplexer das Passwort, desto schwieriger ist es zu knacken.',
      es: 'Introduzca la contraseña. Longitud mínima 6 caracteres. Cuanto más larga y compleja, más difícil de descifrar.',
      fr: 'Entrez le mot de passe. Longueur minimale 6 caractères. Plus le mot de passe est long et complexe, plus il est difficile à craquer.',
      it: 'Inserisci la password. Lunghezza minima 6 caratteri. Più lunga e complessa è la password, più difficile è decifrarla.',
      pt: 'Introduza a palavra-passe. Comprimento mínimo 6 caracteres. Quanto mais longa e complexa, mais difícil de decifrar.',
      sv: 'Ange lösenordet. Minsta längd 6 tecken. Ju längre och mer komplext lösenord, desto svårare att knäcka.',
      no: 'Skriv inn passordet. Minimum 6 tegn. Jo lengre og mer komplekst passord, jo vanskeligere å knekke.',
      is: 'Sláðu inn lykilorðið. Lágmarkslengd 6 stafir. Því lengra og flóknara lykilorð, því erfiðara að brjóta það.',
      tr: 'Belgeyi korumak için kullanmak istediğiniz şifreyi girin. Minimum 6 karakter. Şifre ne kadar uzun ve karmaşık olursa, kırılması o kadar zor olur.',
      ar: 'أدخل كلمة المرور التي تريد استخدامها. الحد الأدنى للطول 6 أحرف. كلما كانت كلمة المرور أطول وأكثر تعقيدًا، زادت صعوبة اختراقها.',
      fa: 'رمز عبوری را که می‌خواهید برای محافظت از سند استفاده کنید وارد کنید. حداقل طول 6 کاراکتر. هر چه رمز عبور طولانی‌تر و پیچیده‌تر باشد، شکستن آن دشوارتر است.',
      hi: 'वह पासवर्ड दर्ज करें जिसका उपयोग आप दस्तावेज़ को सुरक्षित करने के लिए करना चाहते हैं। न्यूनतम लंबाई 6 अक्षर है। पासवर्ड जितना लंबा और जटिल होगा, इसे तोड़ना उतना ही कठिन होगा।',
      ja: '文書を保護するためのパスワードを入力します。最低6文字以上。パスワードが長く複雑であればあるほど、解読は困難になります。',
      zh: '输入要用于保护文档的密码。最小长度为6个字符。密码越长越复杂，越难破解。',
    }},
    { type: 'step', title: {
      pl: 'Potwierdź hasło',
      en: 'Confirm the Password',
      de: 'Passwort bestätigen',
      es: 'Confirme la contraseña',
      fr: 'Confirmez le mot de passe',
      it: 'Conferma la password',
      pt: 'Confirme a palavra-passe',
      sv: 'Bekräfta lösenordet',
      no: 'Bekreft passordet',
      is: 'Staðfestu lykilorðið',
      tr: 'Şifreyi onaylayın',
      ar: 'تأكيد كلمة المرور',
      fa: 'رمز عبور را تأیید کنید',
      hi: 'पासवर्ड की पुष्टि करें',
      ja: 'パスワードを確認',
      zh: '确认密码',
    }, text: {
      pl: 'Wpisz hasło ponownie w polu potwierdzenia. Aplikacja sprawdzi, czy oba hasła są identyczne. Jeśli hasła różnią się, pojawi się ostrzeżenie.',
      en: 'Re-enter the password in the confirmation field. The app checks if both passwords match. If they differ, a warning will appear.',
      de: 'Geben Sie das Passwort im Bestätigungsfeld erneut ein. Die App prüft, ob beide Passwörter übereinstimmen.',
      es: 'Vuelva a introducir la contraseña. La aplicación comprueba si ambas contraseñas coinciden.',
      fr: 'Saisissez à nouveau le mot de passe. L\'application vérifie que les deux mots de passe correspondent.',
      it: 'Reinserisci la password nel campo di conferma. L\'app verifica che entrambe le password corrispondano.',
      pt: 'Reintroduza a palavra-passe. A aplicação verifica se ambas as palavras-passe coincidem.',
      sv: 'Ange lösenordet igen i bekräftelsefältet. Appen kontrollerar om båda lösenorden matchar.',
      no: 'Skriv inn passordet på nytt i bekreftelsesfeltet. Appen sjekker om begge passordene er like.',
      is: 'Sláðu lykilorðið aftur inn í staðfestingarreitinn. Forritið athugar hvort bæði lykilorðin séu eins.',
      tr: 'Onay alanına şifreyi yeniden girin. Uygulama her iki şifrenin de eşleşip eşleşmediğini kontrol eder.',
      ar: 'أعد إدخال كلمة المرور في حقل التأكيد. يتحقق التطبيق من تطابق كلمتي المرور.',
      fa: 'رمز عبور را دوباره در قسمت تأیید وارد کنید. برنامه بررسی می‌کند که آیا هر دو رمز عبور یکسان هستند.',
      hi: 'पुष्टिकरण फ़ील्ड में पासवर्ड पुनः दर्ज करें। ऐप जाँचता है कि दोनों पासवर्ड मेल खाते हैं या नहीं।',
      ja: '確認フィールドにパスワードを再入力します。アプリが両方のパスワードが一致するか確認します。',
      zh: '在确认字段中重新输入密码。应用程序会检查两个密码是否匹配。',
    }},
    { type: 'step', title: {
      pl: 'Pobierz zabezpieczony plik',
      en: 'Download the Protected File',
      de: 'Laden Sie die geschützte Datei herunter',
      es: 'Descargue el archivo protegido',
      fr: 'Téléchargez le fichier protégé',
      it: 'Scarica il file protetto',
      pt: 'Descarregue o ficheiro protegido',
      sv: 'Ladda ner den skyddade filen',
      no: 'Last ned den beskyttede filen',
      is: 'Sæktu vernduðu skrána',
      tr: 'Korumalı dosyayı indirin',
      ar: 'قم بتنزيل الملف المحمي',
      fa: 'فایل محافظت شده را دانلود کنید',
      hi: 'सुरक्षित फ़ाइल डाउनलोड करें',
      ja: '保護されたファイルをダウンロード',
      zh: '下载受保护的文件',
    }, text: {
      pl: 'Kliknij "Zabezpiecz PDF". Po chwili plik zostanie pobrany. Od tej pory do otwarcia dokumentu potrzebne będzie hasło. Uwaga: OptimaPDF nie przechowuje haseł — jeśli zapomnisz hasła, nie ma możliwości odzyskania dostępu.',
      en: 'Click "Protect PDF". The file will be downloaded shortly. From now on, the password will be required to open the document. Note: OptimaPDF does not store passwords — if you forget it, there is no way to recover access.',
      de: 'Klicken Sie auf "PDF schützen". Die Datei wird heruntergeladen. Ab jetzt ist das Passwort zum Öffnen erforderlich. OptimaPDF speichert keine Passwörter.',
      es: 'Haga clic en "Proteger PDF". El archivo se descargará. A partir de ahora se requerirá la contraseña. OptimaPDF no almacena contraseñas.',
      fr: 'Cliquez sur "Protéger le PDF". Le fichier sera téléchargé. Le mot de passe sera désormais requis. OptimaPDF ne stocke pas les mots de passe.',
      it: 'Clicca su "Proteggi PDF". Il file verrà scaricato. D\'ora in poi sarà necessaria la password. OptimaPDF non memorizza le password.',
      pt: 'Clique em "Proteger PDF". O ficheiro será descarregado. A partir de agora a palavra-passe será necessária. OptimaPDF não armazena palavras-passe.',
      sv: 'Klicka på "Skydda PDF". Filen kommer att laddas ner. Från och med nu krävs lösenordet. OptimaPDF lagrar inte lösenord.',
      no: 'Klikk på "Beskytt PDF". Filen vil bli lastet ned. Heretter kreves passordet. OptimaPDF lagrer ikke passord.',
      is: 'Smelltu á "Vernda PDF". Skráin verður sótt. Héðan í frá þarf lykilorðið. OptimaPDF geymir ekki lykilorð.',
      tr: '"PDF\'yi Koru"ya tıklayın. Dosya indirilecektir. Artık belgeyi açmak için şifre gerekecektir. OptimaPDF şifreleri saklamaz.',
      ar: 'انقر على "حماية PDF". سيتم تنزيل الملف. من الآن فصاعدًا، ستكون كلمة المرور مطلوبة. OptimaPDF لا يخزن كلمات المرور.',
      fa: 'روی "محافظت از PDF" کلیک کنید. فایل دانلود خواهد شد. از این به بعد برای باز کردن سند به رمز عبور نیاز است. OptimaPDF رمزهای عبور را ذخیره نمی‌کند.',
      hi: '"PDF सुरक्षित करें" पर क्लिक करें। फ़ाइल डाउनलोड हो जाएगी। अब से दस्तावेज़ खोलने के लिए पासवर्ड की आवश्यकता होगी। OptimaPDF पासवर्ड संग्रहीत नहीं करता है।',
      ja: '「PDFを保護」をクリックします。ファイルがダウンロードされます。今後、文書を開くにはパスワードが必要になります。OptimaPDFはパスワードを保存しません。',
      zh: '点击"保护PDF"。文件将下载。从现在开始，打开文档需要密码。注意：OptimaPDF不存储密码 — 如果您忘记密码，无法恢复访问。',
    }},
    { type: 'cta', tool: 'protect' },
  ],
  relatedTool: 'protect',
  faq: [
    { q: {
      pl: 'Jakie szyfrowanie jest używane?',
      en: 'What encryption is used?',
      de: 'Welche Verschlüsselung wird verwendet?',
      es: '¿Qué cifrado se utiliza?',
      fr: 'Quel chiffrement est utilisé ?',
      it: 'Quale crittografia viene utilizzata?',
      pt: 'Que encriptação é utilizada?',
      sv: 'Vilken kryptering används?',
      no: 'Hvilken kryptering brukes?',
      is: 'Hvaða dulkóðun er notuð?',
      tr: 'Hangi şifreleme kullanılıyor?',
      ar: 'ما التشفير المستخدم؟',
      fa: 'از چه رمزنگاری استفاده می‌شود؟',
      hi: 'कौन सा एन्क्रिप्शन उपयोग किया जाता है?',
      ja: 'どの暗号化方式が使用されていますか？',
      zh: '使用什么加密？',
    }, a: {
      pl: 'OptimaPDF używa szyfrowania AES-256, które jest obecnie standardem w zabezpieczaniu dokumentów PDF. Jest to ten sam standard, którego używają instytucje rządowe i banki.',
      en: 'OptimaPDF uses AES-256 encryption, the current standard for securing PDF documents. It is the same standard used by government institutions and banks.',
      de: 'OptimaPDF verwendet AES-256-Verschlüsselung, den aktuellen Standard für PDF-Sicherheit. Derselbe Standard wird von Behörden und Banken verwendet.',
      es: 'OptimaPDF utiliza cifrado AES-256. Es el mismo estándar utilizado por instituciones gubernamentales y bancos.',
      fr: 'OptimaPDF utilise le chiffrement AES-256, la norme actuelle pour la sécurisation des PDF. Même standard utilisé par les institutions gouvernementales et les banques.',
      it: 'OptimaPDF utilizza la crittografia AES-256, lo standard attuale per la sicurezza dei PDF. È lo stesso standard utilizzato da istituzioni governative e banche.',
      pt: 'OptimaPDF usa encriptação AES-256, o padrão atual para segurança de PDF. É o mesmo padrão usado por instituições governamentais e bancos.',
      sv: 'OptimaPDF använder AES-256-kryptering, nuvarande standard för PDF-säkerhet. Samma standard som används av myndigheter och banker.',
      no: 'OptimaPDF bruker AES-256-kryptering, gjeldende standard for PDF-sikkerhet. Samme standard som brukes av offentlige institusjoner og banker.',
      is: 'OptimaPDF notar AES-256 dulkóðun, núverandi staðal fyrir PDF öryggi. Sama staðall og notaður er af ríkisstofnunum og bönkum.',
      tr: 'OptimaPDF, PDF güvenliği için mevcut standart olan AES-256 şifrelemesini kullanır. Devlet kurumları ve bankalar tarafından kullanılan aynı standarttır.',
      ar: 'يستخدم OptimaPDF تشفير AES-256، المعيار الحالي لتأمين PDF. هو نفس المعيار المستخدم من قبل المؤسسات الحكومية والبنوك.',
      fa: 'OptimaPDF از رمزنگاری AES-256 استفاده می‌کند، استاندارد فعلی برای امنیت PDF. همان استانداردی که توسط مؤسسات دولتی و بانک‌ها استفاده می‌شود.',
      hi: 'OptimaPDF AES-256 एन्क्रिप्शन का उपयोग करता है, जो PDF सुरक्षा के लिए वर्तमान मानक है। यह वही मानक है जो सरकारी संस्थानों और बैंकों द्वारा उपयोग किया जाता है।',
      ja: 'OptimaPDFは、PDFセキュリティの現在の標準であるAES-256暗号化を使用しています。これは政府機関や銀行が使用するのと同じ標準です。',
      zh: 'OptimaPDF使用AES-256加密，这是当前保护PDF的标准。与政府机构和银行使用的标准相同。',
    }},
  ],
  canonicalOverride: undefined,
  publishedAt: '2025-06-20',
  updatedAt: '2025-07-02',
};

export default article;
