import type { GuideArticle } from '@/types/guide';

const article: GuideArticle = {
  slug: 'how-to-unlock-pdf-online',
  category: 'unlock-pdf',
  title: {
    pl: 'Jak odblokować PDF i usunąć hasło',
    en: 'How to Unlock a PDF and Remove Password',
    de: 'Wie man eine PDF entsperrt und das Passwort entfernt',
    es: 'Cómo desbloquear un PDF y eliminar la contraseña',
    fr: 'Comment déverrouiller un PDF et supprimer le mot de passe',
    it: 'Come sbloccare un PDF e rimuovere la password',
    pt: 'Como desbloquear um PDF e remover a palavra-passe',
    sv: 'Hur man låser upp en PDF och tar bort lösenord',
    no: 'Hvordan låse opp en PDF og fjerne passord',
    is: 'Hvernig á að opna PDF og fjarlægja lykilorð',
    tr: 'Bir PDF\'nin kilidi nasıl açılır ve şifre nasıl kaldırılır',
    ar: 'كيفية فتح قفل PDF وإزالة كلمة المرور',
    fa: 'چگونه قفل PDF را باز کنیم و رمز عبور را حذف کنیم',
    hi: 'PDF को अनलॉक कैसे करें और पासवर्ड कैसे हटाएं',
    ja: 'PDFのロックを解除してパスワードを削除する方法',
    zh: '如何解锁PDF并移除密码',
  },
  excerpt: {
    pl: 'Dowiedz się, jak usunąć zabezpieczenie hasłem z pliku PDF. Wystarczy znać hasło — narzędzie działa lokalnie w przeglądarce, bez wysyłania plików na serwer.',
    en: 'Learn how to remove password protection from a PDF file. You just need to know the password — the tool works locally in your browser, no files are sent to any server.',
    de: 'Entfernen Sie den Passwortschutz von einer PDF-Datei. Sie müssen nur das Passwort kennen — alles lokal im Browser.',
    es: 'Aprenda a eliminar la protección por contraseña de un PDF. Solo necesita saber la contraseña — todo local en el navegador.',
    fr: 'Apprenez à supprimer la protection par mot de passe d\'un PDF. Vous avez juste besoin du mot de passe — tout local dans le navigateur.',
    it: 'Impara a rimuovere la protezione tramite password da un PDF. Ti serve solo la password — tutto locale nel browser.',
    pt: 'Aprenda a remover a proteção por palavra-passe de um PDF. Só precisa da palavra-passe — tudo local no navegador.',
    sv: 'Lär dig hur du tar bort lösenordsskyddet från en PDF-fil. Du behöver bara lösenordet — allt lokalt i webbläsaren.',
    no: 'Lær hvordan du fjerner passordbeskyttelse fra en PDF-fil. Du trenger bare passordet — alt lokalt i nettleseren.',
    is: 'Lærðu hvernig á að fjarlægja lykilorðsvernd af PDF skrá. Þú þarft bara lykilorðið — allt staðbundið í vafranum.',
    tr: 'Bir PDF dosyasından şifre korumasını nasıl kaldıracağınızı öğrenin. Sadece şifreyi bilmeniz yeterli — her şey tarayıcınızda yerel.',
    ar: 'تعلم كيفية إزالة حماية كلمة المرور من ملف PDF. كل ما تحتاجه هو معرفة كلمة المرور — كل شيء محلي في المتصفح.',
    fa: 'بیاموزید چگونه حفاظت رمز عبور را از یک فایل PDF حذف کنید. فقط باید رمز عبور را بدانید — همه چیز محلی در مرورگر.',
    hi: 'PDF फ़ाइल से पासवर्ड सुरक्षा हटाना सीखें। आपको बस पासवर्ड जानना होगा — सब कुछ ब्राउज़र में स्थानीय रूप से होता है।',
    ja: 'PDFファイルからパスワード保護を解除する方法を学びます。パスワードを知っているだけで、すべてブラウザ内でローカルに処理されます。',
    zh: '了解如何从PDF文件中移除密码保护。您只需知道密码 — 一切都在浏览器中本地完成，文件不会发送到任何服务器。',
  },
  body: [
    { type: 'paragraph', text: {
      pl: 'Odblokowanie PDF przydaje się, gdy masz dokument chroniony hasłem i potrzebujesz go edytować, wydrukować lub przekonwertować. OptimaPDF pozwala usunąć zabezpieczenie, jeśli znasz hasło. Proces odbywa się w całości w przeglądarce.',
      en: 'Unlocking a PDF is useful when you have a password-protected document and need to edit, print or convert it. OptimaPDF lets you remove the protection if you know the password. The process happens entirely in your browser.',
      de: 'Das Entsperren einer PDF ist nützlich, wenn Sie ein passwortgeschütztes Dokument bearbeiten, drucken oder konvertieren müssen.',
      es: 'Desbloquear un PDF es útil cuando tienes un documento protegido y necesitas editarlo, imprimirlo o convertirlo.',
      fr: 'Déverrouiller un PDF est utile lorsque vous avez un document protégé et devez le modifier, l\'imprimer ou le convertir.',
      it: 'Sbloccare un PDF è utile quando hai un documento protetto e devi modificarlo, stamparlo o convertirlo.',
      pt: 'Desbloquear um PDF é útil quando tem um documento protegido e precisa de o editar, imprimir ou converter.',
      sv: 'Att låsa upp en PDF är användbart när du har ett lösenordsskyddat dokument och behöver redigera, skriva ut eller konvertera det.',
      no: 'Å låse opp en PDF er nyttig når du har et passordbeskyttet dokument og trenger å redigere, skrive ut eller konvertere det.',
      is: 'Að opna PDF er gagnlegt þegar þú ert með lykilorðsverndað skjal og þarft að breyta, prenta eða umbreyta því.',
      tr: 'Şifre korumalı bir belgeniz olduğunda ve onu düzenlemeniz, yazdırmanız veya dönüştürmeniz gerektiğinde PDF kilidini açmak kullanışlıdır.',
      ar: 'فتح قفل PDF مفيد عندما يكون لديك مستند محمي بكلمة مرور وتحتاج إلى تحريره أو طباعته أو تحويله.',
      fa: 'باز کردن قفل PDF زمانی مفید است که سندی محافظت شده با رمز عبور دارید و نیاز به ویرایش، چاپ یا تبدیل آن دارید.',
      hi: 'PDF अनलॉक करना तब उपयोगी होता है जब आपके पास पासवर्ड-संरक्षित दस्तावेज़ हो और आपको इसे संपादित, प्रिंट या कनवर्ट करने की आवश्यकता हो।',
      ja: 'パスワードで保護された文書を編集、印刷、変換する必要がある場合、PDFのロック解除が便利です。',
      zh: '当您有受密码保护的文档需要编辑、打印或转换时，解锁PDF非常有用。',
    }},
    { type: 'cta', tool: 'unlock' },
    { type: 'heading', level: 2, text: {
      pl: 'Jak odblokować PDF krok po kroku',
      en: 'How to Unlock a PDF Step by Step',
      de: 'Schritt-für-Schritt-Anleitung zum Entsperren',
      es: 'Cómo desbloquear un PDF paso a paso',
      fr: 'Comment déverrouiller un PDF étape par étape',
      it: 'Come sbloccare un PDF passo dopo passo',
      pt: 'Como desbloquear um PDF passo a passo',
      sv: 'Hur man låser upp en PDF steg för steg',
      no: 'Hvordan låse opp en PDF trinn for trinn',
      is: 'Hvernig á að opna PDF skref fyrir skref',
      tr: 'PDF Adım Adım Nasıl Açılır',
      ar: 'كيفية فتح قفل PDF خطوة بخطوة',
      fa: 'نحوه باز کردن قفل PDF گام به گام',
      hi: 'चरण दर चरण PDF कैसे अनलॉक करें',
      ja: 'ステップバイステップでPDFのロックを解除する方法',
      zh: '如何逐步解锁PDF',
    }},
    { type: 'step', title: {
      pl: 'Wybierz plik PDF',
      en: 'Select the PDF File',
      de: 'PDF-Datei auswählen',
      es: 'Seleccione el archivo PDF',
      fr: 'Sélectionnez le fichier PDF',
      it: 'Seleziona il file PDF',
      pt: 'Selecione o ficheiro PDF',
      sv: 'Välj PDF-filen',
      no: 'Velg PDF-filen',
      is: 'Veldu PDF skrána',
      tr: 'PDF dosyasını seçin',
      ar: 'حدد ملف PDF',
      fa: 'فایل PDF را انتخاب کنید',
      hi: 'PDF फ़ाइल चुनें',
      ja: 'PDFファイルを選択',
      zh: '选择PDF文件',
    }, text: {
      pl: 'Przeciągnij plik PDF chroniony hasłem w pole wyboru lub kliknij, aby wybrać go z dysku. Narzędzie obsługuje wszystkie standardowe zabezpieczenia PDF.',
      en: 'Drag the password-protected PDF into the upload area or click to select it from your disk. The tool supports all standard PDF protections.',
      de: 'Ziehen Sie die passwortgeschützte PDF in den Upload-Bereich oder klicken Sie zur Auswahl. Das Tool unterstützt alle Standard-PDF-Schutzmaßnahmen.',
      es: 'Arrastre el PDF protegido al área de carga o haga clic para seleccionarlo. La herramienta admite todas las protecciones PDF estándar.',
      fr: 'Glissez le PDF protégé dans la zone de téléchargement ou cliquez pour le sélectionner. L\'outil prend en charge toutes les protections PDF standard.',
      it: 'Trascina il PDF protetto nell\'area di caricamento o clicca per selezionarlo. Lo strumento supporta tutte le protezioni PDF standard.',
      pt: 'Arraste o PDF protegido para a área de carregamento ou clique para o selecionar. A ferramenta suporta todas as proteções PDF padrão.',
      sv: 'Dra den lösenordsskyddade PDF-filen till uppladdningsområdet eller klicka för att välja den. Verktyget stöder alla standard PDF-skydd.',
      no: 'Dra den passordbeskyttede PDF-filen til opplastingsområdet eller klikk for å velge den. Verktøyet støtter alle standard PDF-beskyttelser.',
      is: 'Dragðu lykilorðsvernduðu PDF skrána á hleðslusvæðið eða smelltu til að velja hana. Tólið styður alla staðlaða PDF verndun.',
      tr: 'Şifre korumalı PDF\'yi yükleme alanına sürükleyin veya tıklayarak diskinizden seçin. Araç, tüm standart PDF korumalarını destekler.',
      ar: 'اسحب PDF المحمي بكلمة مرور إلى منطقة التحميل أو انقر لتحديده. الأداة تدعم جميع حماية PDF القياسية.',
      fa: 'PDF محافظت شده با رمز عبور را به منطقه بارگذاری بکشید یا کلیک کنید تا آن را از دیسک خود انتخاب کنید. ابزار از تمام محافظت‌های استاندارد PDF پشتیبانی می‌کند.',
      hi: 'पासवर्ड-संरक्षित PDF को अपलोड क्षेत्र में खींचें या अपनी डिस्क से चुनने के लिए क्लिक करें। उपकरण सभी मानक PDF सुरक्षाओं का समर्थन करता है।',
      ja: 'パスワードで保護されたPDFをアップロードエリアにドラッグするか、クリックしてディスクから選択します。このツールはすべての標準的なPDF保護に対応しています。',
      zh: '将受密码保护的PDF拖放到上传区域，或单击从磁盘中选择。该工具支持所有标准PDF保护。',
    }},
    { type: 'step', title: {
      pl: 'Wprowadź hasło',
      en: 'Enter the Password',
      de: 'Passwort eingeben',
      es: 'Introduzca la contraseña',
      fr: 'Entrez le mot de passe',
      it: 'Inserisci la password',
      pt: 'Introduza a palavra-passe',
      sv: 'Ange lösenordet',
      no: 'Skriv inn passordet',
      is: 'Sláðu inn lykilorðið',
      tr: 'Şifreyi girin',
      ar: 'أدخل كلمة المرور',
      fa: 'رمز عبور را وارد کنید',
      hi: 'पासवर्ड दर्ज करें',
      ja: 'パスワードを入力',
      zh: '输入密码',
    }, text: {
      pl: 'Wpisz hasło dokumentu w polu tekstowym. Jeśli hasło jest poprawne, narzędzie usunie zabezpieczenie. Uwaga: jeśli nie znasz hasła, nie ma możliwości odblokowania pliku.',
      en: 'Enter the document password in the text field. If the password is correct, the tool will remove the protection. Note: if you don\'t know the password, there is no way to unlock the file.',
      de: 'Geben Sie das Dokumentpasswort ein. Bei korrektem Passwort wird der Schutz entfernt. Ohne Passwort ist keine Entsperrung möglich.',
      es: 'Introduzca la contraseña del documento. Si es correcta, la herramienta eliminará la protección. Sin la contraseña no es posible desbloquear.',
      fr: 'Entrez le mot de passe du document. S\'il est correct, l\'outil supprime la protection. Sans le mot de passe, impossible de déverrouiller.',
      it: 'Inserisci la password del documento. Se corretta, lo strumento rimuove la protezione. Senza password non è possibile sbloccare.',
      pt: 'Introduza a palavra-passe do documento. Se estiver correta, a ferramenta remove a proteção. Sem a palavra-passe não é possível desbloquear.',
      sv: 'Ange dokumentlösenordet. Om det är korrekt tar verktyget bort skyddet. Utan lösenordet går det inte att låsa upp.',
      no: 'Skriv inn dokumentpassordet. Hvis det er riktig, fjerner verktøyet beskyttelsen. Uten passordet er det ikke mulig å låse opp.',
      is: 'Sláðu inn lykilorð skjalsins. Ef það er rétt fjarlægir tólið verndun. Án lykilorðsins er ekki hægt að opna skrána.',
      tr: 'Belge şifresini metin alanına girin. Şifre doğruysa, araç korumayı kaldıracaktır. Şifreyi bilmiyorsanız, dosyanın kilidini açmanın bir yolu yoktur.',
      ar: 'أدخل كلمة مرور المستند في حقل النص. إذا كانت كلمة المرور صحيحة، ستقوم الأداة بإزالة الحماية. بدون كلمة المرور، لا يمكن فتح القفل.',
      fa: 'رمز عبور سند را در قسمت متن وارد کنید. اگر رمز عبور صحیح باشد، ابزار حفاظت را حذف می‌کند. بدون رمز عبور، امکان باز کردن قفل وجود ندارد.',
      hi: 'टेक्स्ट फ़ील्ड में दस्तावेज़ पासवर्ड दर्ज करें। यदि पासवर्ड सही है, तो उपकरण सुरक्षा हटा देगा। यदि आप पासवर्ड नहीं जानते हैं, तो फ़ाइल को अनलॉक करने का कोई तरीका नहीं है।',
      ja: 'テキストフィールドにドキュメントのパスワードを入力します。パスワードが正しければ、ツールが保護を解除します。パスワードがわからない場合は、ロックを解除する方法はありません。',
      zh: '在文本字段中输入文档密码。如果密码正确，工具将移除保护。如果您不知道密码，则无法解锁文件。',
    }},
    { type: 'step', title: {
      pl: 'Pobierz odblokowany plik',
      en: 'Download the Unlocked File',
      de: 'Laden Sie die entsperrte Datei herunter',
      es: 'Descargue el archivo desbloqueado',
      fr: 'Téléchargez le fichier déverrouillé',
      it: 'Scarica il file sbloccato',
      pt: 'Descarregue o ficheiro desbloqueado',
      sv: 'Ladda ner den upplåsta filen',
      no: 'Last ned den låste opp filen',
      is: 'Sæktu opnuðu skrána',
      tr: 'Kilidi açılmış dosyayı indirin',
      ar: 'قم بتنزيل الملف مفتوح القفل',
      fa: 'فایل باز شده را دانلود کنید',
      hi: 'अनलॉक की गई फ़ाइल डाउनलोड करें',
      ja: 'ロック解除されたファイルをダウンロード',
      zh: '下载已解锁的文件',
    }, text: {
      pl: 'Kliknij "Odblokuj PDF". Po chwili plik bez zabezpieczenia zostanie pobrany. Możesz teraz swobodnie edytować, drukować i konwertować dokument.',
      en: 'Click "Unlock PDF". The unprotected file will be downloaded shortly. You can now freely edit, print and convert the document.',
      de: 'Klicken Sie auf "PDF entsperren". Die ungeschützte Datei wird heruntergeladen. Sie können das Dokument nun frei bearbeiten, drucken und konvertieren.',
      es: 'Haga clic en "Desbloquear PDF". El archivo desprotegido se descargará. Ahora puede editar, imprimir y convertir el documento.',
      fr: 'Cliquez sur "Déverrouiller le PDF". Le fichier non protégé sera téléchargé. Vous pouvez maintenant modifier, imprimer et convertir le document.',
      it: 'Clicca su "Sblocca PDF". Il file non protetto verrà scaricato. Ora puoi modificare, stampare e convertire liberamente il documento.',
      pt: 'Clique em "Desbloquear PDF". O ficheiro desprotegido será descarregado. Agora pode editar, imprimir e converter o documento livremente.',
      sv: 'Klicka på "Lås upp PDF". Den oskyddade filen laddas ner. Du kan nu fritt redigera, skriva ut och konvertera dokumentet.',
      no: 'Klikk på "Lås opp PDF". Den ubeskyttede filen vil bli lastet ned. Du kan nå fritt redigere, skrive ut og konvertere dokumentet.',
      is: 'Smelltu á "Opna PDF". Óvarin skráin verður sótt. Þú getur nú breytt, prentað og umbreytt skjalinu frjálslega.',
      tr: '"PDF\'nin Kilidini Aç"a tıklayın. Korumasız dosya indirilecektir. Artık belgeyi özgürce düzenleyebilir, yazdırabilir ve dönüştürebilirsiniz.',
      ar: 'انقر على "فتح قفل PDF". سيتم تنزيل الملف غير المحمي. يمكنك الآن تحرير المستند وطباعته وتحويله بحرية.',
      fa: 'روی "باز کردن قفل PDF" کلیک کنید. فایل بدون حفاظت دانلود خواهد شد. اکنون می‌توانید آزادانه سند را ویرایش، چاپ و تبدیل کنید.',
      hi: '"PDF अनलॉक करें" पर क्लिक करें। असुरक्षित फ़ाइल डाउनलोड हो जाएगी। अब आप दस्तावेज़ को स्वतंत्र रूप से संपादित, प्रिंट और कनवर्ट कर सकते हैं।',
      ja: '「PDFのロックを解除」をクリックします。保護されていないファイルがダウンロードされます。これで自由に編集、印刷、変換ができます。',
      zh: '点击"解锁PDF"。未受保护的文件将被下载。您现在可以自由编辑、打印和转换文档。',
    }},
    { type: 'cta', tool: 'unlock' },
  ],
  relatedTool: 'unlock',
  faq: [
    { q: {
      pl: 'Czy mogę odblokować PDF bez znajomości hasła?',
      en: 'Can I unlock a PDF without knowing the password?',
      de: 'Kann ich eine PDF ohne Passwort entsperren?',
      es: '¿Puedo desbloquear un PDF sin conocer la contraseña?',
      fr: 'Puis-je déverrouiller un PDF sans connaître le mot de passe ?',
      it: 'Posso sbloccare un PDF senza conoscere la password?',
      pt: 'Posso desbloquear um PDF sem saber a palavra-passe?',
      sv: 'Kan jag låsa upp en PDF utan att känna till lösenordet?',
      no: 'Kan jeg låse opp en PDF uten å kjenne passordet?',
      is: 'Get ég opnað PDF án þess að vita lykilorðið?',
      tr: 'Şifreyi bilmeden bir PDF\'nin kilidini açabilir miyim?',
      ar: 'هل يمكنني فتح قفل PDF بدون معرفة كلمة المرور؟',
      fa: 'آیا می‌توانم بدون دانستن رمز عبور قفل PDF را باز کنم؟',
      hi: 'क्या मैं पासवर्ड जाने बिना PDF अनलॉक कर सकता हूँ?',
      ja: 'パスワードを知らなくてもPDFのロックを解除できますか？',
      zh: '不知道密码可以解锁PDF吗？',
    }, a: {
      pl: 'Nie. Narzędzie działa w przeglądarce i nie omija zabezpieczeń. Aby odblokować plik, musisz znać hasło. Jest to celowe — gwarantuje, że nie można otworzyć cudzych dokumentów.',
      en: 'No. The tool works in your browser and does not bypass security. To unlock a file, you must know the password. This is intentional — it guarantees that nobody can open someone else\'s documents.',
      de: 'Nein. Das Tool umgeht keine Sicherheitsvorkehrungen. Sie müssen das Passwort kennen. Das ist beabsichtigt — so kann niemand fremde Dokumente öffnen.',
      es: 'No. La herramienta no omite la seguridad. Debe conocer la contraseña. Es intencionado: garantiza que nadie pueda abrir documentos ajenos.',
      fr: 'Non. L\'outil ne contourne pas la sécurité. Vous devez connaître le mot de passe. C\'est intentionnel — personne ne peut ouvrir les documents d\'autrui.',
      it: 'No. Lo strumento non aggira la sicurezza. Devi conoscere la password. È intenzionale — garantisce che nessuno possa aprire documenti altrui.',
      pt: 'Não. A ferramenta não contorna a segurança. Tem de saber a palavra-passe. É intencional — garante que ninguém pode abrir documentos alheios.',
      sv: 'Nej. Verktyget kringgår inte säkerheten. Du måste känna till lösenordet. Det är avsiktligt — ingen kan öppna någon annans dokument.',
      no: 'Nei. Verktøyet omgår ikke sikkerheten. Du må kjenne passordet. Dette er tilsiktet — ingen kan åpne andres dokumenter.',
      is: 'Nei. Tólið framhjá ekki öryggi. Þú verður að vita lykilorðið. Þetta er viljandi — það tryggir að enginn getur opnað skjöl annarra.',
      tr: 'Hayır. Araç güvenliği atlamaz. Dosyanın kilidini açmak için şifreyi bilmelisiniz. Bu kasıtlıdır — kimsenin başkasının belgelerini açamamasını garanti eder.',
      ar: 'لا. الأداة لا تتجاوز الأمان. يجب أن تعرف كلمة المرور. هذا مقصود — يضمن عدم تمكن أي شخص من فتح مستندات الآخرين.',
      fa: 'خیر. ابزار امنیت را دور نمی‌زند. برای باز کردن قفل فایل باید رمز عبور را بدانید. این عمدی است — تضمین می‌کند که هیچ‌کس نمی‌تواند اسناد دیگران را باز کند.',
      hi: 'नहीं। उपकरण सुरक्षा को बायपास नहीं करता है। फ़ाइल अनलॉक करने के लिए, आपको पासवर्ड पता होना चाहिए। यह जानबूझकर है — यह गारंटी देता है कि कोई भी दूसरे के दस्तावेज़ नहीं खोल सकता।',
      ja: 'いいえ。このツールはセキュリティを回避しません。ロックを解除するにはパスワードを知っている必要があります。これは意図的なものであり、他人の文書を開くことができないことを保証します。',
      zh: '不能。该工具不会绕过安全机制。要解锁文件，您必须知道密码。这是有意为之 — 它保证任何人都无法打开他人的文档。',
    }},
  ],
  canonicalOverride: undefined,
  publishedAt: '2025-06-22',
  updatedAt: '2025-07-02',
};

export default article;
