import type { GuideArticle } from '@/types/guide';

const article: GuideArticle = {
  slug: 'how-to-convert-jpg-to-pdf',
  category: 'jpg-to-pdf',
  title: {
    pl: 'Jak przekonwertować JPG do PDF',
    en: 'How to Convert JPG to PDF',
    de: 'Wie man JPG in PDF konvertiert',
    es: 'Cómo convertir JPG a PDF',
    fr: 'Comment convertir JPG en PDF',
    it: 'Come convertire JPG in PDF',
    pt: 'Como converter JPG para PDF',
    sv: 'Hur man konverterar JPG till PDF',
    no: 'Hvordan konvertere JPG til PDF',
    is: 'Hvernig á að umbreyta JPG í PDF',
    tr: 'JPG PDF\'ye nasıl dönüştürülür',
    ar: 'كيفية تحويل JPG إلى PDF',
    fa: 'چگونه JPG را به PDF تبدیل کنیم',
    hi: 'JPG को PDF में कैसे बदलें',
    ja: 'JPGをPDFに変換する方法',
    zh: '如何将JPG转换为PDF',
  },
  excerpt: {
    pl: 'Zamień zdjęcia i obrazy JPG, PNG, WebP na plik PDF. Połącz wiele obrazów w jeden dokument — idealne do skanów i dokumentacji.',
    en: 'Convert photos and images (JPG, PNG, WebP) into a PDF file. Combine multiple images into one document — perfect for scans and documentation.',
    de: 'Konvertieren Sie Fotos und Bilder in eine PDF-Datei. Kombinieren Sie mehrere Bilder in einem Dokument.',
    es: 'Convierta fotos e imágenes en un archivo PDF. Combine varias imágenes en un documento.',
    fr: 'Convertissez des photos et images en un fichier PDF. Combinez plusieurs images en un seul document.',
    it: 'Converti foto e immagini in un file PDF. Combina più immagini in un unico documento.',
    pt: 'Converta fotos e imagens num ficheiro PDF. Combine várias imagens num único documento.',
    sv: 'Konvertera foton och bilder till en PDF-fil. Kombinera flera bilder till ett dokument.',
    no: 'Konverter bilder og foto til en PDF-fil. Kombiner flere bilder til ett dokument.',
    is: 'Umbreyttu ljósmyndum og myndum í PDF skrá. Sameina margar myndir í eitt skjal.',
    tr: 'Fotoğrafları ve görüntüleri PDF dosyasına dönüştürün. Birden fazla görüntüyü tek bir belgede birleştirin.',
    ar: 'حوّل الصور والصور الفوتوغرافية إلى ملف PDF. ادمج عدة صور في مستند واحد.',
    fa: 'عکس‌ها و تصاویر را به فایل PDF تبدیل کنید. چندین تصویر را در یک سند ترکیب کنید.',
    hi: 'फ़ोटो और छवियों को PDF फ़ाइल में बदलें। कई छवियों को एक दस्तावेज़ में संयोजित करें।',
    ja: '写真や画像をPDFファイルに変換します。複数の画像を1つの文書に結合します。',
    zh: '将照片和图像转换为PDF文件。将多个图像合并到一个文档中。',
  },
  body: [
    { type: 'paragraph', text: {
      pl: 'Konwersja obrazów do PDF przydaje się, gdy chcesz wysłać zdjęcia jako jeden plik, utworzyć dokument z zeskanowanych stron lub zrobić portfolio. OptimaPDF obsługuje JPG, PNG i WebP — możesz mieszać formaty w jednym dokumencie.',
      en: 'Converting images to PDF is useful when you want to send photos as one file, create a document from scanned pages or make a portfolio. OptimaPDF supports JPG, PNG and WebP — you can mix formats in one document.',
      de: 'Die Konvertierung von Bildern in PDF ist nützlich, um Fotos als eine Datei zu versenden oder aus gescannten Seiten ein Dokument zu erstellen.',
      es: 'Convertir imágenes a PDF es útil para enviar fotos como un solo archivo o crear un documento a partir de páginas escaneadas.',
      fr: 'La conversion d\'images en PDF est utile pour envoyer des photos en un seul fichier ou créer un document à partir de pages scannées.',
      it: 'Convertire immagini in PDF è utile per inviare foto come unico file o creare un documento da pagine scansionate.',
      pt: 'Converter imagens para PDF é útil para enviar fotos como um único ficheiro ou criar um documento a partir de páginas digitalizadas.',
      sv: 'Att konvertera bilder till PDF är användbart för att skicka foton som en fil eller skapa ett dokument från skannade sidor.',
      no: 'Å konvertere bilder til PDF er nyttig for å sende bilder som én fil eller lage et dokument fra skannede sider.',
      is: 'Að umbreyta myndum í PDF er gagnlegt til að senda myndir sem eina skrá eða búa til skjal úr skönnuðum síðum.',
      tr: 'Görüntüleri PDF\'ye dönüştürmek, fotoğrafları tek bir dosya olarak göndermek veya taranmış sayfalardan belge oluşturmak için kullanışlıdır.',
      ar: 'تحويل الصور إلى PDF مفيد عندما تريد إرسال الصور كملف واحد أو إنشاء مستند من الصفحات الممسوحة ضوئيًا.',
      fa: 'تبدیل تصاویر به PDF برای ارسال عکس‌ها به عنوان یک فایل یا ایجاد سند از صفحات اسکن شده مفید است.',
      hi: 'फ़ोटो को एक फ़ाइल के रूप में भेजने या स्कैन किए गए पृष्ठों से दस्तावेज़ बनाने के लिए छवियों को PDF में बदलना उपयोगी है।',
      ja: '画像からPDFへの変換は、写真を1つのファイルとして送信したり、スキャンページから文書を作成したりするのに便利です。',
      zh: '将图像转换为PDF在需要将照片作为单个文件发送或从扫描页面创建文档时非常有用。',
    }},
    { type: 'cta', tool: 'jpgTopdf' },
    { type: 'heading', level: 2, text: {
      pl: 'Jak przekonwertować JPG do PDF krok po kroku',
      en: 'How to Convert JPG to PDF Step by Step',
      de: 'Schritt-für-Schritt-Anleitung zur JPG-zu-PDF-Konvertierung',
      es: 'Cómo convertir JPG a PDF paso a paso',
      fr: 'Comment convertir JPG en PDF étape par étape',
      it: 'Come convertire JPG in PDF passo dopo passo',
      pt: 'Como converter JPG para PDF passo a passo',
      sv: 'Hur man konverterar JPG till PDF steg för steg',
      no: 'Hvordan konvertere JPG til PDF trinn for trinn',
      is: 'Hvernig á að umbreyta JPG í PDF skref fyrir skref',
      tr: 'JPG Adım Adım PDF\'ye Nasıl Dönüştürülür',
      ar: 'كيفية تحويل JPG إلى PDF خطوة بخطوة',
      fa: 'نحوه تبدیل JPG به PDF گام به گام',
      hi: 'चरण दर चरण JPG को PDF में कैसे बदलें',
      ja: 'ステップバイステップでJPGをPDFに変換する方法',
      zh: '如何逐步将JPG转换为PDF',
    }},
    { type: 'step', title: {
      pl: 'Dodaj obrazy',
      en: 'Add Images',
      de: 'Bilder hinzufügen',
      es: 'Añadir imágenes',
      fr: 'Ajouter des images',
      it: 'Aggiungi immagini',
      pt: 'Adicionar imagens',
      sv: 'Lägg till bilder',
      no: 'Legg til bilder',
      is: 'Bæta við myndum',
      tr: 'Görüntü ekleyin',
      ar: 'أضف صورًا',
      fa: 'تصاویر را اضافه کنید',
      hi: 'चित्र जोड़ें',
      ja: '画像を追加',
      zh: '添加图像',
    }, text: {
      pl: 'Przeciągnij obrazy (JPG, PNG, WebP) w pole wyboru lub kliknij, aby wybrać je z dysku. Możesz dodać wiele obrazów jednocześnie, a także mieszać różne formaty w jednym dokumencie.',
      en: 'Drag images (JPG, PNG, WebP) into the upload area or click to select them from your disk. You can add multiple images at once and mix different formats in one document.',
      de: 'Ziehen Sie Bilder in den Upload-Bereich oder klicken Sie zur Auswahl. Sie können mehrere Bilder gleichzeitig hinzufügen und Formate mischen.',
      es: 'Arrastre imágenes al área de carga o haga clic para seleccionarlas. Puede añadir varias imágenes a la vez y mezclar formatos.',
      fr: 'Glissez les images dans la zone de téléchargement ou cliquez pour les sélectionner. Vous pouvez ajouter plusieurs images à la fois et mélanger les formats.',
      it: 'Trascina le immagini nell\'area di caricamento o clicca per selezionarle. Puoi aggiungere più immagini contemporaneamente e mescolare formati diversi.',
      pt: 'Arraste imagens para a área de carregamento ou clique para as selecionar. Pode adicionar várias imagens de uma vez e misturar formatos.',
      sv: 'Dra bilder till uppladdningsområdet eller klicka för att välja dem. Du kan lägga till flera bilder samtidigt och blanda format.',
      no: 'Dra bilder til opplastingsområdet eller klikk for å velge dem. Du kan legge til flere bilder samtidig og blande formater.',
      is: 'Dragðu myndir á hleðslusvæðið eða smelltu til að velja þær. Þú getur bætt við mörgum myndum í einu og blandað sniðum.',
      tr: 'Görüntüleri yükleme alanına sürükleyin veya tıklayarak diskinizden seçin. Aynı anda birden fazla görüntü ekleyebilir ve farklı formatları karıştırabilirsiniz.',
      ar: 'اسحب الصور إلى منطقة التحميل أو انقر لتحديدها. يمكنك إضافة عدة صور في وقت واحد وخلط التنسيقات.',
      fa: 'تصاویر را به منطقه بارگذاری بکشید یا کلیک کنید تا آنها را از دیسک خود انتخاب کنید. می‌توانید چندین تصویر را همزمان اضافه کرده و فرمت‌های مختلف را ترکیب کنید.',
      hi: 'चित्रों को अपलोड क्षेत्र में खींचें या अपनी डिस्क से चुनने के लिए क्लिक करें। आप एक साथ कई चित्र जोड़ सकते हैं और विभिन्न प्रारूपों को मिश्रित कर सकते हैं।',
      ja: '画像をアップロードエリアにドラッグするか、クリックしてディスクから選択します。複数の画像を同時に追加でき、異なる形式を混在させることもできます。',
      zh: '将图像拖放到上传区域，或单击从磁盘中选择。您可以一次添加多个图像，并在一个文档中混合不同的格式。',
    }},
    { type: 'step', title: {
      pl: 'Ustaw kolejność i opcje',
      en: 'Set Order and Options',
      de: 'Reihenfolge und Optionen festlegen',
      es: 'Establecer orden y opciones',
      fr: 'Définir l\'ordre et les options',
      it: 'Imposta ordine e opzioni',
      pt: 'Definir ordem e opções',
      sv: 'Ställ in ordning och alternativ',
      no: 'Angi rekkefølge og alternativer',
      is: 'Still inn röð og valkosti',
      tr: 'Sıra ve seçenekleri ayarlayın',
      ar: 'تعيين الترتيب والخيارات',
      fa: 'ترتیب و گزینه‌ها را تنظیم کنید',
      hi: 'क्रम और विकल्प सेट करें',
      ja: '順序とオプションを設定',
      zh: '设置顺序和选项',
    }, text: {
      pl: 'Przeciągnij obrazy, aby zmienić ich kolejność. Wybierz rozmiar strony (A4, Letter, lub dopasowany do obrazu) oraz margines. Możesz też wybrać orientację: pionową lub poziomą.',
      en: 'Drag images to change their order. Choose the page size (A4, Letter, or fit to image) and margin. You can also select orientation: portrait or landscape.',
      de: 'Ziehen Sie Bilder, um die Reihenfolge zu ändern. Wählen Sie Seitengröße und Rand. Sie können auch das Format auswählen: Hoch- oder Querformat.',
      es: 'Arrastre imágenes para cambiar el orden. Elija el tamaño de página y el margen. También puede seleccionar la orientación.',
      fr: 'Glissez les images pour changer l\'ordre. Choisissez la taille de page et la marge. Vous pouvez aussi sélectionner l\'orientation.',
      it: 'Trascina le immagini per cambiarne l\'ordine. Scegli le dimensioni della pagina e il margine. Puoi anche selezionare l\'orientamento.',
      pt: 'Arraste imagens para alterar a ordem. Escolha o tamanho da página e a margem. Pode também selecionar a orientação.',
      sv: 'Dra bilder för att ändra ordningen. Välj sidstorlek och marginal. Du kan också välja orientering.',
      no: 'Dra bilder for å endre rekkefølgen. Velg sidestørrelse og marg. Du kan også velge orientering.',
      is: 'Dragðu myndir til að breyta röð. Veldu síðustærð og spássíu. Þú getur líka valið stefnu.',
      tr: 'Sıralamayı değiştirmek için görüntüleri sürükleyin. Sayfa boyutunu ve kenar boşluğunu seçin. Ayrıca yönlendirmeyi de seçebilirsiniz.',
      ar: 'اسحب الصور لتغيير ترتيبها. اختر حجم الصفحة والهامش. يمكنك أيضًا اختيار الاتجاه.',
      fa: 'تصاویر را بکشید تا ترتیب آنها را تغییر دهید. اندازه صفحه و حاشیه را انتخاب کنید. همچنین می‌توانید جهت را انتخاب کنید.',
      hi: 'क्रम बदलने के लिए चित्रों को खींचें। पृष्ठ का आकार और मार्जिन चुनें। आप ओरिएंटेशन भी चुन सकते हैं।',
      ja: '画像をドラッグして順序を変更します。用紙サイズと余白を選択します。向き（縦/横）も選択できます。',
      zh: '拖动图像更改顺序。选择页面大小和边距。您还可以选择方向。',
    }},
    { type: 'step', title: {
      pl: 'Pobierz plik PDF',
      en: 'Download the PDF File',
      de: 'PDF-Datei herunterladen',
      es: 'Descargue el archivo PDF',
      fr: 'Téléchargez le fichier PDF',
      it: 'Scarica il file PDF',
      pt: 'Descarregue o ficheiro PDF',
      sv: 'Ladda ner PDF-filen',
      no: 'Last ned PDF-filen',
      is: 'Sæktu PDF skrána',
      tr: 'PDF dosyasını indirin',
      ar: 'قم بتنزيل ملف PDF',
      fa: 'فایل PDF را دانلود کنید',
      hi: 'PDF फ़ाइल डाउनलोड करें',
      ja: 'PDFファイルをダウンロード',
      zh: '下载PDF文件',
    }, text: {
      pl: 'Kliknij "Utwórz PDF". Po chwili plik zostanie pobrany. Każdy obraz stanie się osobną stroną w dokumencie PDF. Jakość obrazów pozostaje oryginalna.',
      en: 'Click "Create PDF". The file will be downloaded shortly. Each image becomes a separate page in the PDF document. Image quality remains original.',
      de: 'Klicken Sie auf "PDF erstellen". Jedes Bild wird zu einer eigenen Seite im PDF. Die Bildqualität bleibt original.',
      es: 'Haga clic en "Crear PDF". Cada imagen se convierte en una página separada. La calidad de imagen sigue siendo original.',
      fr: 'Cliquez sur "Créer le PDF". Chaque image devient une page séparée. La qualité d\'image reste originale.',
      it: 'Clicca su "Crea PDF". Ogni immagine diventa una pagina separata. La qualità dell\'immagine rimane originale.',
      pt: 'Clique em "Criar PDF". Cada imagem torna-se uma página separada. A qualidade da imagem permanece original.',
      sv: 'Klicka på "Skapa PDF". Varje bild blir en separat sida. Bildkvaliteten förblir original.',
      no: 'Klikk på "Opprett PDF". Hvert bilde blir en separat side. Bildekvaliteten forblir original.',
      is: 'Smelltu á "Búa til PDF". Hver mynd verður aðskilin síða. Myndgæðin haldast upprunaleg.',
      tr: '"PDF Oluştur"a tıklayın. Her görüntü PDF belgesinde ayrı bir sayfa haline gelir. Görüntü kalitesi orijinal kalır.',
      ar: 'انقر على "إنشاء PDF". تصبح كل صورة صفحة منفصلة في مستند PDF. تبقى جودة الصورة أصلية.',
      fa: 'روی "ایجاد PDF" کلیک کنید. هر تصویر به یک صفحه جداگانه در سند PDF تبدیل می‌شود. کیفیت تصویر اصلی باقی می‌ماند.',
      hi: '"PDF बनाएं" पर क्लिक करें। प्रत्येक चित्र PDF दस्तावेज़ में एक अलग पृष्ठ बन जाता है। छवि गुणवत्ता मूल बनी रहती है।',
      ja: '「PDFを作成」をクリックします。各画像がPDF文書の個別のページになります。画質は元のままです。',
      zh: '点击"创建PDF"。每个图像成为PDF文档中的一个单独页面。图像质量保持原始水平。',
    }},
    { type: 'cta', tool: 'jpgTopdf' },
  ],
  relatedTool: 'jpgTopdf',
  faq: [
    { q: {
      pl: 'Jakie formaty obrazów są obsługiwane?',
      en: 'What image formats are supported?',
      de: 'Welche Bildformate werden unterstützt?',
      es: '¿Qué formatos de imagen son compatibles?',
      fr: 'Quels formats d\'image sont pris en charge ?',
      it: 'Quali formati di immagine sono supportati?',
      pt: 'Que formatos de imagem são suportados?',
      sv: 'Vilka bildformat stöds?',
      no: 'Hvilke bildeformater støttes?',
      is: 'Hvaða myndsnið eru studd?',
      tr: 'Hangi görüntü formatları destekleniyor?',
      ar: 'ما تنسيقات الصور المدعومة؟',
      fa: 'چه فرمت‌های تصویری پشتیبانی می‌شوند؟',
      hi: 'कौन से चित्र प्रारूप समर्थित हैं?',
      ja: '対応している画像形式は？',
      zh: '支持哪些图像格式？',
    }, a: {
      pl: 'Obsługiwane są formaty JPG, PNG i WebP. Możesz mieszać różne formaty w jednym dokumencie — na przykład dodać 3 zdjęcia JPG i 2 zrzuty ekranu PNG w jednym pliku PDF.',
      en: 'JPG, PNG and WebP formats are supported. You can mix different formats in one document — for example, add 3 JPG photos and 2 PNG screenshots in a single PDF file.',
      de: 'JPG, PNG und WebP werden unterstützt. Sie können verschiedene Formate in einem Dokument mischen.',
      es: 'Se admiten los formatos JPG, PNG y WebP. Puede mezclar diferentes formatos en un documento.',
      fr: 'Les formats JPG, PNG et WebP sont pris en charge. Vous pouvez mélanger différents formats dans un document.',
      it: 'I formati JPG, PNG e WebP sono supportati. Puoi mescolare diversi formati in un documento.',
      pt: 'Os formatos JPG, PNG e WebP são suportados. Pode misturar diferentes formatos num documento.',
      sv: 'Format JPG, PNG och WebP stöds. Du kan blanda olika format i ett dokument.',
      no: 'Formatene JPG, PNG og WebP støttes. Du kan blande forskjellige formater i ett dokument.',
      is: 'JPG, PNG og WebP snið eru studd. Þú getur blandað mismunandi sniðum í einu skjali.',
      tr: 'JPG, PNG ve WebP formatları desteklenir. Tek bir belgede farklı formatları karıştırabilirsiniz.',
      ar: 'تنسيقات JPG و PNG و WebP مدعومة. يمكنك خلط تنسيقات مختلفة في مستند واحد.',
      fa: 'فرمت‌های JPG، PNG و WebP پشتیبانی می‌شوند. می‌توانید فرمت‌های مختلف را در یک سند ترکیب کنید.',
      hi: 'JPG, PNG और WebP प्रारूप समर्थित हैं। आप एक दस्तावेज़ में विभिन्न प्रारूपों को मिश्रित कर सकते हैं।',
      ja: 'JPG、PNG、WebP形式に対応しています。1つの文書で異なる形式を混在させることができます。',
      zh: '支持JPG、PNG和WebP格式。您可以在一个文档中混合不同的格式。',
    }},
  ],
  canonicalOverride: undefined,
  publishedAt: '2025-06-28',
  updatedAt: '2025-07-02',
};

export default article;
